### ISSUE TITLE
pip-compile breaks when there are only wheels

### ISSUE THREAD

**Issue by nvie** [jazzband/pip-tools#106]
```
- Getting dependencies for click-2.5
    - Getting package location for click==2.5
          Archive cache hit: click-2.5-py2.py3-none-any.whl
    - Extracting dependencies for /Users/nvie/.pip-tools/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fc%2Fclick%2Fclick-2.5-py2.py3-none-any.whl
        - Unpacking /Users/nvie/.pip-tools/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fc%2Fclick%2Fclick-2.5-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/Users/nvie/Projects/sil/.direnv/virtualenv/bin/pip-compile", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/nvie/Projects/pip-tools/bin/pip-compile", line 184, in <module>
    main()
  File "/Users/nvie/Projects/pip-tools/bin/pip-compile", line 175, in main
    compile_specs(src_files, include_sources=args.include_sources, dry_run=args.dry_run)
  File "/Users/nvie/Projects/pip-tools/bin/pip-compile", line 122, in compile_specs
    pinned_spec_set = resolver.resolve()
  File "/Users/nvie/Projects/pip-tools/piptools/resolver.py", line 44, in resolve
    if not self.resolve_one_round():
  File "/Users/nvie/Projects/pip-tools/piptools/resolver.py", line 28, in resolve_one_round
    new_deps = self.find_new_dependencies()
  File "/Users/nvie/Projects/pip-tools/piptools/resolver.py", line 91, in find_new_dependencies
    all_deps = self.find_all_dependencies()
  File "/Users/nvie/Projects/pip-tools/piptools/resolver.py", line 74, in find_all_dependencies
    pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
  File "/Users/nvie/Projects/pip-tools/piptools/package_manager.py", line 341, in get_dependencies
    deps = self.extract_dependencies(path)
  File "/Users/nvie/Projects/pip-tools/piptools/package_manager.py", line 509, in extract_dependencies
    self.unpack_archive(path, unpack_dir)
  File "/Users/nvie/Projects/pip-tools/piptools/package_manager.py", line 431, in unpack_archive
    archive = zipfile.ZipFile(path)
  File "/Users/nvie/.pythonz/pythons/CPython-3.4.0/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/Users/nvie/.pythonz/pythons/CPython-3.4.0/lib/python3.4/zipfile.py", line 996, in _RealGetContents
    fp.seek(self.start_dir, 0)
OSError: [Errno 22] Invalid argument
```

**Comment by davidovich** [comment]
Closing old issue
