### ISSUE TITLE
pip-compile fails on apache-airflow package due to InstallationError

### ISSUE THREAD

**Issue by matthewpick** [jazzband/pip-tools#1095]
#### Environment Versions

1. macOS
1. Python version: `3.7.3`
1. pip version:  `19.0.3`
1. pip-tools version: `4.5.1`

#### Steps to replicate

1. `python3 -m venv venv && source venv/bin/activate`
2. `pip3 install pip-tools`
3. `echo "apache-airflow" > requirements.in`
4. `pip-compile`

#### Expected result

`requirements.txt` similar to [this one](https://github.com/apache/airflow/pull/4470/files).

#### Actual result

```
(venv) ➜  pip-compile
Traceback (most recent call last):
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 391, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 365, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 295, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 252, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 155, in _call_hook
    extra_environ={'PEP517_BUILD_BACKEND': build_backend}
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 511, in runner
    spinner=spinner
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/Users/mattpick/Documents/repos/pip-compile-test/venv/bin/python3 /Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/25/gq0dk2nd52j252jcmh_gpzk00000gn/T/tmpkj79ojfe" failed with error code 1 in /var/folders/25/gq0dk2nd52j252jcmh_gpzk00000gn/T/tmprz3v2454build/sqlalchemy
```

**Comment by atugushev** [comment]
Hello @matthewpick,

Thanks for the issue! Unfortunately, I couldn't reproduce it locally. Could you attach the full output from `pip-compile -v` command?

**Comment by matthewpick** [comment]
It appears it has to do with `alembic` not being in the cache. 
I was not able to reproduce this issue in a python3 docker container, could be something wonky with my macOS install!

That said, there could be something useful we uncover.

```
(venv) ➜  pip-compile-test pip-compile -v requirements.in
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  apache-airflow (from -r requirements.in (line 1))

Finding the best candidates:
  found candidate apache-airflow==1.10.9 (constraint was <any>)

Finding secondary dependencies:
  apache-airflow==1.10.9    requires alembic<2.0,>=1.0, argcomplete~=1.10, attrs~=19.3, cached-property~=1.5, cattrs~=0.9, colorlog==4.0.2, configparser<3.6.0,>=3.5.0, croniter<0.4,>=0.3.17, dill<0.4,>=0.2.2, flask-admin==1.5.4, flask-appbuilder~=2.2; python_version >= "3.6", flask-caching<1.4.0,>=1.3.3, flask-login<0.5,>=0.3, flask-swagger==0.2.13, flask-wtf<0.15,>=0.14.2, flask<2.0,>=1.1.0, funcsigs<2.0.0,>=1.0.0, future<0.17,>=0.16.0, graphviz>=0.12, gunicorn<20.0,>=19.5.0, iso8601>=0.1.12, jinja2<2.11.0,>=2.10.1, json-merge-patch==0.2, jsonschema~=3.0, lazy-object-proxy~=1.3, markdown<3.0,>=2.5.2, pandas<1.0.0,>=0.17.1, pendulum==1.4.4, psutil<6.0.0,>=4.2.0, pygments<3.0,>=2.0.1, python-daemon<2.2,>=2.1.1, python-dateutil<3,>=2.3, requests<3,>=2.20.0, setproctitle<2,>=1.1.8, sqlalchemy-jsonfield~=0.9; python_version >= "3.5", sqlalchemy~=1.3, tabulate<0.9,>=0.7.5, tenacity==4.12.0, termcolor==1.1.0, text-unidecode==1.2, thrift>=0.9.2, typing-extensions>=3.7.4; python_version < "3.8", tzlocal<2.0.0,>=1.4, unicodecsv>=0.14.1, werkzeug<1.0.0, zope.deprecation<5.0,>=4.0

New dependencies found in this round:
  adding ['alembic', '<2.0,>=1.0', '[]']
  adding ['argcomplete', '~=1.10', '[]']
  adding ['attrs', '~=19.3', '[]']
  adding ['cached-property', '~=1.5', '[]']
  adding ['cattrs', '~=0.9', '[]']
  adding ['colorlog', '==4.0.2', '[]']
  adding ['configparser', '<3.6.0,>=3.5.0', '[]']
  adding ['croniter', '<0.4,>=0.3.17', '[]']
  adding ['dill', '<0.4,>=0.2.2', '[]']
  adding ['flask', '<2.0,>=1.1.0', '[]']
  adding ['flask-admin', '==1.5.4', '[]']
  adding ['flask-appbuilder', '~=2.2', '[]']
  adding ['flask-caching', '<1.4.0,>=1.3.3', '[]']
  adding ['flask-login', '<0.5,>=0.3', '[]']
  adding ['flask-swagger', '==0.2.13', '[]']
  adding ['flask-wtf', '<0.15,>=0.14.2', '[]']
  adding ['funcsigs', '<2.0.0,>=1.0.0', '[]']
  adding ['future', '<0.17,>=0.16.0', '[]']
  adding ['graphviz', '>=0.12', '[]']
  adding ['gunicorn', '<20.0,>=19.5.0', '[]']
  adding ['iso8601', '>=0.1.12', '[]']
  adding ['jinja2', '<2.11.0,>=2.10.1', '[]']
  adding ['json-merge-patch', '==0.2', '[]']
  adding ['jsonschema', '~=3.0', '[]']
  adding ['lazy-object-proxy', '~=1.3', '[]']
  adding ['markdown', '<3.0,>=2.5.2', '[]']
  adding ['pandas', '<1.0.0,>=0.17.1', '[]']
  adding ['pendulum', '==1.4.4', '[]']
  adding ['psutil', '<6.0.0,>=4.2.0', '[]']
  adding ['pygments', '<3.0,>=2.0.1', '[]']
  adding ['python-daemon', '<2.2,>=2.1.1', '[]']
  adding ['python-dateutil', '<3,>=2.3', '[]']
  adding ['requests', '<3,>=2.20.0', '[]']
  adding ['setproctitle', '<2,>=1.1.8', '[]']
  adding ['sqlalchemy', '~=1.3', '[]']
  adding ['sqlalchemy-jsonfield', '~=0.9', '[]']
  adding ['tabulate', '<0.9,>=0.7.5', '[]']
  adding ['tenacity', '==4.12.0', '[]']
  adding ['termcolor', '==1.1.0', '[]']
  adding ['text-unidecode', '==1.2', '[]']
  adding ['thrift', '>=0.9.2', '[]']
  adding ['typing-extensions', '>=3.7.4', '[]']
  adding ['tzlocal', '<2.0.0,>=1.4', '[]']
  adding ['unicodecsv', '>=0.14.1', '[]']
  adding ['werkzeug', '<1.0.0', '[]']
  adding ['zope.deprecation', '<5.0,>=4.0', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  alembic<2.0,>=1.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  apache-airflow (from -r requirements.in (line 1))
  argcomplete~=1.10 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  attrs~=19.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  cached-property~=1.5 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  cattrs~=0.9 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  colorlog==4.0.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  configparser<3.6.0,>=3.5.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  croniter<0.4,>=0.3.17 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  dill<0.4,>=0.2.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask<2.0,>=1.1.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-admin==1.5.4 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-appbuilder~=2.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-caching<1.4.0,>=1.3.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-login<0.5,>=0.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-swagger==0.2.13 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  flask-wtf<0.15,>=0.14.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  funcsigs<2.0.0,>=1.0.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  future<0.17,>=0.16.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  graphviz>=0.12 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  gunicorn<20.0,>=19.5.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  iso8601>=0.1.12 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  jinja2<2.11.0,>=2.10.1 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  json-merge-patch==0.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  jsonschema~=3.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  lazy-object-proxy~=1.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  markdown<3.0,>=2.5.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  pandas<1.0.0,>=0.17.1 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  pendulum==1.4.4 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  psutil<6.0.0,>=4.2.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  pygments<3.0,>=2.0.1 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  python-daemon<2.2,>=2.1.1 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  python-dateutil<3,>=2.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  requests<3,>=2.20.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  setproctitle<2,>=1.1.8 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  sqlalchemy~=1.3 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  sqlalchemy-jsonfield~=0.9 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  tabulate<0.9,>=0.7.5 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  tenacity==4.12.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  termcolor==1.1.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  text-unidecode==1.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  thrift>=0.9.2 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  typing-extensions>=3.7.4 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  tzlocal<2.0.0,>=1.4 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  unicodecsv>=0.14.1 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  werkzeug<1.0.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))
  zope.deprecation<5.0,>=4.0 (from apache-airflow==1.10.9->-r requirements.in (line 1))

Finding the best candidates:
  found candidate alembic==1.4.2 (constraint was >=1.0,<2.0)
  found candidate apache-airflow==1.10.9 (constraint was <any>)
  found candidate argcomplete==1.11.1 (constraint was ~=1.10)
  found candidate attrs==19.3.0 (constraint was ~=19.3)
  found candidate cached-property==1.5.1 (constraint was ~=1.5)
  found candidate cattrs==0.9.0 (constraint was ~=0.9)
  found candidate colorlog==4.0.2 (constraint was ==4.0.2)
  found candidate configparser==3.5.3 (constraint was >=3.5.0,<3.6.0)
  found candidate croniter==0.3.31 (constraint was >=0.3.17,<0.4)
  found candidate dill==0.3.1.1 (constraint was >=0.2.2,<0.4)
  found candidate flask==1.1.1 (constraint was >=1.1.0,<2.0)
  found candidate flask-admin==1.5.4 (constraint was ==1.5.4)
  found candidate flask-appbuilder==2.3.1 (constraint was ~=2.2)
  found candidate flask-caching==1.3.3 (constraint was >=1.3.3,<1.4.0)
  found candidate flask-login==0.4.1 (constraint was >=0.3,<0.5)
  found candidate flask-swagger==0.2.13 (constraint was ==0.2.13)
  found candidate flask-wtf==0.14.3 (constraint was >=0.14.2,<0.15)
  found candidate funcsigs==1.0.2 (constraint was >=1.0.0,<2.0.0)
  found candidate future==0.16.0 (constraint was >=0.16.0,<0.17)
  found candidate graphviz==0.13.2 (constraint was >=0.12)
  found candidate gunicorn==19.10.0 (constraint was >=19.5.0,<20.0)
  found candidate iso8601==0.1.12 (constraint was >=0.1.12)
  found candidate jinja2==2.10.3 (constraint was >=2.10.1,<2.11.0)
  found candidate json-merge-patch==0.2 (constraint was ==0.2)
  found candidate jsonschema==3.2.0 (constraint was ~=3.0)
  found candidate lazy-object-proxy==1.4.3 (constraint was ~=1.3)
  found candidate markdown==2.6.11 (constraint was >=2.5.2,<3.0)
  found candidate pandas==0.25.3 (constraint was >=0.17.1,<1.0.0)
  found candidate pendulum==1.4.4 (constraint was ==1.4.4)
  found candidate psutil==5.7.0 (constraint was >=4.2.0,<6.0.0)
  found candidate pygments==2.6.1 (constraint was >=2.0.1,<3.0)
  found candidate python-daemon==2.1.2 (constraint was >=2.1.1,<2.2)
  found candidate python-dateutil==2.8.1 (constraint was >=2.3,<3)
  found candidate requests==2.23.0 (constraint was >=2.20.0,<3)
  found candidate setproctitle==1.1.10 (constraint was >=1.1.8,<2)
  found candidate sqlalchemy==1.3.15 (constraint was ~=1.3)
  found candidate sqlalchemy-jsonfield==0.9.0 (constraint was ~=0.9)
  found candidate tabulate==0.8.7 (constraint was >=0.7.5,<0.9)
  found candidate tenacity==4.12.0 (constraint was ==4.12.0)
  found candidate termcolor==1.1.0 (constraint was ==1.1.0)
  found candidate text-unidecode==1.2 (constraint was ==1.2)
  found candidate thrift==0.13.0 (constraint was >=0.9.2)
  found candidate typing-extensions==3.7.4.1 (constraint was >=3.7.4)
  found candidate tzlocal==1.5.1 (constraint was >=1.4,<2.0.0)
  found candidate unicodecsv==0.14.1 (constraint was >=0.14.1)
  found candidate werkzeug==0.16.1 (constraint was <1.0.0)
  found candidate zope.deprecation==4.4.0 (constraint was >=4.0,<5.0)

Finding secondary dependencies:
  markdown==2.6.11          requires -
  tabulate==0.8.7           requires -
  gunicorn==19.10.0         requires -
  json-merge-patch==0.2     requires -
  flask-swagger==0.2.13     requires Flask>=0.10, PyYAML>=3.0
  future==0.16.0            requires -
  croniter==0.3.31          requires python-dateutil
  dill==0.3.1.1             requires -
  termcolor==1.1.0          requires -
  typing-extensions==3.7.4.1 requires -
  python-dateutil==2.8.1    requires six>=1.5
  apache-airflow==1.10.9    requires alembic<2.0,>=1.0, argcomplete~=1.10, attrs~=19.3, cached-property~=1.5, cattrs~=0.9, colorlog==4.0.2, configparser<3.6.0,>=3.5.0, croniter<0.4,>=0.3.17, dill<0.4,>=0.2.2, flask-admin==1.5.4, flask-appbuilder~=2.2; python_version >= "3.6", flask-caching<1.4.0,>=1.3.3, flask-login<0.5,>=0.3, flask-swagger==0.2.13, flask-wtf<0.15,>=0.14.2, flask<2.0,>=1.1.0, funcsigs<2.0.0,>=1.0.0, future<0.17,>=0.16.0, graphviz>=0.12, gunicorn<20.0,>=19.5.0, iso8601>=0.1.12, jinja2<2.11.0,>=2.10.1, json-merge-patch==0.2, jsonschema~=3.0, lazy-object-proxy~=1.3, markdown<3.0,>=2.5.2, pandas<1.0.0,>=0.17.1, pendulum==1.4.4, psutil<6.0.0,>=4.2.0, pygments<3.0,>=2.0.1, python-daemon<2.2,>=2.1.1, python-dateutil<3,>=2.3, requests<3,>=2.20.0, setproctitle<2,>=1.1.8, sqlalchemy-jsonfield~=0.9; python_version >= "3.5", sqlalchemy~=1.3, tabulate<0.9,>=0.7.5, tenacity==4.12.0, termcolor==1.1.0, text-unidecode==1.2, thrift>=0.9.2, typing-extensions>=3.7.4; python_version < "3.8", tzlocal<2.0.0,>=1.4, unicodecsv>=0.14.1, werkzeug<1.0.0, zope.deprecation<5.0,>=4.0
  alembic==1.4.2 not in cache, need to check index
Traceback (most recent call last):
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 391, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/resolver.py", line 365, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 295, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 252, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 155, in _call_hook
    extra_environ={'PEP517_BUILD_BACKEND': build_backend}
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 511, in runner
    spinner=spinner
  File "/Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/Users/mattpick/Documents/repos/pip-compile-test/venv/bin/python3 /Users/mattpick/Documents/repos/pip-compile-test/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/25/gq0dk2nd52j252jcmh_gpzk00000gn/T/tmp6qh87736" failed with error code 1 in /var/folders/25/gq0dk2nd52j252jcmh_gpzk00000gn/T/tmpy2o51r1xbuild/alembic
```

**Comment by atugushev** [comment]
@matthewpick 

Thanks for the attached output. Could you also update pip to the latest version and try `pip-compile -v` once again?

**Comment by matthewpick** [comment]
@atugushev 
I could not reproduce this error after upgrading pip! 
I will go ahead and close out this issue. Thanks for your help.
