### ISSUE TITLE
ModuleNotFoundError: No module named 'pip.req'

### ISSUE THREAD

**Issue by SebastianoF** [jazzband/pip-tools#1096]
Hello there!

* pip version: latest versus 9.0.3
* Python version: 3.7
* OS: Ubuntu

**Description and how to reproduce**
The bug is:
```
$ pip-compile-multi

Locking requirements/requirements_base.in to requirements/requirements_base.txt. References: []
ERROR executing pip-compile --no-header --verbose --rebuild --upgrade --no-index --output-file requirements_base.txt requirements_base.in
Exit code: 1

Traceback (most recent call last):
  File "/home/XXX/venv/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/XXX/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from pip.req import InstallRequirement, parse_requirements
ModuleNotFoundError: No module named 'pip.req'

Traceback (most recent call last):
  File "/home/XXX/venv/lib/python3.7/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/home/XXX/venv/lib/python3.7/site-packages/pipcompilemulti/actions.py", line 21, in recompile
    if env.maybe_create_lockfile():
  File "/home/XXX/venv/lib/python3.7/site-packages/pipcompilemulti/environment.py", line 43, in maybe_create_lockfile
    self.create_lockfile()
  File "/home/XXX/venv/lib/python3.7/site-packages/pipcompilemulti/environment.py", line 66, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements/requirements_base.in

```

Latest version of pip fails on:
```
# venv/lib/python3.7/site-packages/piptools/scripts/compile.py
from pip.req import InstallRequirement, parse_requirements
```
Since pip made a non-backward compatible change, and you need to:
```
from pip._internal.req import parse_requirements
```
Or better
```
try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
```
As explained here:
https://stackoverflow.com/questions/25192794/no-module-named-pip-req

**Comment by SebastianoF** [comment]
Solved by installing the latest version, thanks for the retroactive fix!
