### ISSUE TITLE
SQLAlchemy version 1.3.15 fails compilation

### ISSUE THREAD

**Issue by parasvanjani** [jazzband/pip-tools#1103]
Seems like pip-compile is unable to compile SQLAlchemy 1.3.15
Here is the error - 

```
pip._internal.exceptions.InstallationError: Command "c:\projects\test\venv\scripts\python.exe c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\TESTUS~1\AppData\Local\Temp\tmpluccnix8" failed with error code 1 in C:\Users\TESTUS~1\AppData\Local\Temp\tmph496qq1qbuild\SQLAlchemy
```

Below is a detailed output
```
$ pip-compile.exe -v
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  SQLAlchemy==1.3.15 (from -r requirements.in (line 1))

Finding the best candidates:
  found candidate sqlalchemy==1.3.15 (constraint was ==1.3.15)

Finding secondary dependencies:
  sqlalchemy==1.3.15 not in cache, need to check index
Traceback (most recent call last):
  File "C:\install\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\install\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\projects\test\venv\Scripts\pip-compile.exe\__main__.py", line 9, in <module>
  File "c:\projects\test\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\projects\test\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\projects\test\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\projects\test\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\projects\test\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\projects\test\venv\lib\site-packages\piptools\scripts\compile.py", line 391, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "c:\projects\test\venv\lib\site-packages\piptools\resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\projects\test\venv\lib\site-packages\piptools\resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "c:\projects\test\venv\lib\site-packages\piptools\resolver.py", line 365, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\projects\test\venv\lib\site-packages\piptools\repositories\local.py", line 70, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "c:\projects\test\venv\lib\site-packages\piptools\repositories\pypi.py", line 295, in get_dependencies
    download_dir, ireq, wheel_cache
  File "c:\projects\test\venv\lib\site-packages\piptools\repositories\pypi.py", line 252, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\operations\prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\operations\prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_vendor\pep517\wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_vendor\pep517\wrappers.py", line 155, in _call_hook
    extra_environ={'PEP517_BUILD_BACKEND': build_backend}
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 511, in runner
    spinner=spinner
  File "c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\utils\misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "c:\projects\test\venv\scripts\python.exe c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3
.6.egg\pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\TESTUS~1\AppData\Local\Temp\tmpluccnix8" failed with error code 1 in C:\Users\TESTUS~1\AppD
ata\Local\Temp\tmph496qq1qbuild\SQLAlchemy
```

**Comment by parasvanjani** [comment]
On a side note, the compilation works fine till version 1.3.13 (fails from 1.3.14 onwards)

**Comment by atugushev** [comment]
> c:\projects\test\venv\lib\site-packages\pip-19.0.3-py3

Could you update pip (`python -m pip install --upgrade pip`) and try again?

**Comment by parasvanjani** [comment]
awesome works. Thanks
