### ISSUE TITLE
pip.download.get_file_content is passed a Link object instead of a string

### ISSUE THREAD

**Issue by gavinwahl** [jazzband/pip-tools#114]
On https://github.com/nvie/pip-tools/blob/db135d85d4f6ebc87449ebfa1590db1bcd79d0ba/piptools/package_manager.py#L422, `link` is a `Link` object, but get_file_content expects a string and fails with:

```
Traceback (most recent call last):
  File "pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
  File "click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "piptools/scripts/compile.py", line 174, in cli
    compile_specs(src_files, include_sources=include_sources, dry_run=dry_run)
  File "piptools/scripts/compile.py", line 106, in compile_specs
    pinned_spec_set = resolver.resolve()
  File "piptools/resolver.py", line 44, in resolve
    if not self.resolve_one_round():
  File "piptools/resolver.py", line 28, in resolve_one_round
    new_deps = self.find_new_dependencies()
  File "piptools/resolver.py", line 91, in find_new_dependencies
    all_deps = self.find_all_dependencies()
  File "piptools/resolver.py", line 74, in find_all_dependencies
    pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
  File "piptools/package_manager.py", line 341, in get_dependencies
    path = self.get_or_download_package(pinned_spec)
  File "piptools/package_manager.py", line 384, in get_or_download_package
    self.download_package(link, fullpath)
  File "piptools/package_manager.py", line 423, in download_package
    _, content = get_file_content(url, link, session=self._session)
  File "pip/download.py", line 250, in get_file_content
    and comes_from.startswith('http')):
AttributeError: 'Link' object has no attribute 'startswith'
```

Casting the link to a str works, but I'm not sure if this is the correct solution.

**Comment by davidovich** [comment]
This issue references obsolete/deleted code. Please reopen if you feel this is still an issue.
