### ISSUE TITLE
pip-compile fails to generate requirements.txt 

### ISSUE THREAD

**Issue by AthulMuralidhar** [jazzband/pip-tools#1157]
**Environment**
Docker container
* pip version: pip 20.1.1
* Python version: python 3.5
* pip-compile version:  version 4.4.0
* OS: Debian GNU/Linux 9.11 (stretch)

**Description**

- As standard practice, i was trying to generate a `requirements.txt` from a `requirements.in` file, I get an `AttributeError` instead
**Expected behavior**

- The file should be generated
**How to Reproduce**

1. Make a requirements.in file
2. Then run: `pip-compile --no-index --output-file=requirements.txt requirements.in` or ` pip-compile requirements.in` 
3. An error occurs: 

**Output**

```
root@578e94be84a0:~# pip-compile requirements.in
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/piptools/scripts/compile.py", line 300, in cli
    for ireq in filter(is_pinned_requirement, ireqs):
  File "/usr/local/lib/python3.5/dist-packages/piptools/utils.py", line 122, in is_pinned_requirement
    if ireq.editable:
AttributeError: 'ParsedRequirement' object has no attribute 'editable'
```

**Note** the same error occurs for both the commands used

**Comment by atugushev** [comment]
Hello @AthulMuralidhar,

Thanks for the issue! Could you attach your `requirements.in` to the issue, so that we could try to reproduce the bug?

**Comment by atugushev** [comment]
I see where is the problem, you should upgrade `pip-tools` to the latest version `5.2.0`.

**Comment by atugushev** [comment]
See also https://github.com/jazzband/pip-tools#versions-and-compatibility

**Comment by AthulMuralidhar** [comment]
thanks! @atugushev will do
