### ISSUE TITLE
concurrent access to pip-tools cache dir results in confusing errors

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#1180]
relates to: https://github.com/jazzband/pip-tools/issues/1083
#### Environment Versions

1. OS Type Linux
1. Python version: 3.8
1. pip version:  20.1.1 
1. pip-tools version: pip-compile, version 5.2.1

#### Steps to replicate

1. create several requirements.in/txt pairs
2. run pip-compile with xargs or pre-commit
3. various confusing error messages/stack traces and the requirements fail to compile

#### Expected result
running several pip-compile commands at the same time as the same user simply works
...

#### Actual result
running several pip-compile commands at the same time as the same user results in:
```
Finding secondary dependencies:
  virtualenv==20.0.9 not in cache, need to check index
  Collecting virtualenv==20.0.9
    Using cached virtualenv-20.0.9-py2.py3-none-any.whl (4.6 MB)
Traceback (most recent call last):
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/bin/pip-auto-compile", line 8, in <module>
    sys.exit(main())
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/pipautocompile.py", line 51, in main
    compile_file(f, other_args)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/pipautocompile.py", line 28, in compile_file
    compile.cli(
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/resolver.py", line 380, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/repositories/local.py", line 74, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 228, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 181, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/graingert/.cache/pre-commit/repo1dxf0pc3/py_env-python3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 499, in prepare_linked_requirement
    shutil.copy(local_file.path, download_location)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/graingert/.cache/pip-tools/wheels/virtualenv-20.0.9-py2.py3-none-any.whl'
```

**Comment by graingert** [comment]
This happens when passing `-r` in concurrent builds
