### ISSUE TITLE
Pip-compile fails on sub-directory as `find-links`

### ISSUE THREAD

**Issue by Abhishek-Dev09** [jazzband/pip-tools#1188]
Pip-compile not able to take subdirectory as find-links
#### Environment Versions

1. OS Type - macOS
1. Python version: ` python 3.6.8`
1. pip version:  `pip 20.0.2`
1. pip-tools version: `pip-compile, version 5.2.1`

#### Steps to replicate
```
(scancode-toolkit) mymac@ABHISHEKs-MacBook-Air scancode-toolkit % pip-compile --annotate --generate-hashes --find-links thirdparty/dev --no-emit-find-links --pip-args "--no-index" 
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/scripts/compile.py:297: FutureWarning: --index and --no-index are deprecated and will be removed in future versions. Use --emit-index-url/--no-emit-index-url instead.
  category=FutureWarning,
WARNING: Requirement 'funcsigs==1.0.2-py2.py3-none-any.whl' looks like a filename, but the file does not exist
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/scripts/compile.py", line 405, in cli
    options=repository.options,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/_compat/pip_compat.py", line 29, in parse_requirements
    yield install_req_from_parsed_requirement(parsed_req, isolated=isolated)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 462, in install_req_from_parsed_requirement
    line_source=parsed_req.line_source,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 396, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 337, in parse_req_from_line
    wheel = Wheel(link.filename)  # can raise InvalidWheelFilename
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/models/wheel.py", line 33, in __init__
    "{} is not a valid wheel filename.".format(filename)
pip._internal.exceptions.InvalidWheelFilename: funcsigs==1.0.2-py2.py3-none-any.whl is not a valid wheel filename.
```

#Expected result
It will write requirements.txt.

**Comment by Abhishek-Dev09** [comment]
@pombredanne: This is our major issue but this can solved by moving all wheel `thirdparty/dev` to `thirdparty` . So no worries .

**Comment by Abhishek-Dev09** [comment]
@atugushev : Please solve this bug ASAP

**Comment by atugushev** [comment]
@Abhishek-Dev09 PRs are welcomed 👍

**Comment by atugushev** [comment]
@Abhishek-Dev09 

I believe the issue is in command, please try this instead:
```
$ pip-compile --annotate --generate-hashes --find-links thirdparty/dev --no-emit-find-links --pip-args "--no-index"
```

**Comment by atugushev** [comment]
@Abhishek-Dev09 

> Please solve this bug ASAP

In the meantime, please, try to avoid phrases like "fix this bug ASAP" in open source. `pip-tools` is free/open-source software maintained by a non-profit [organization](https://jazzband.co) and a group of volunteer users. It's rude to ask people to fix urgently a bug for free. 

Here is a good article about [open-source etiquette](https://css-tricks.com/open-source-etiquette-guidebook/#for-the-user) you might find useful. Thanks!

**Comment by Abhishek-Dev09** [comment]
@atugushev : Sorry for using that phrases. I have updated the comments that i found bug.

**Comment by atugushev** [comment]
> pip._internal.exceptions.InvalidWheelFilename: funcsigs==1.0.2-py2.py3-none-any.whl is not a valid wheel filename.

Looks like you have `funcsigs==1.0.2-py2.py3-none-any.whl` in your `requirements.in`. It should be `funcsigs==1.0.2`.

**Comment by Abhishek-Dev09** [comment]
@atugushev i have already tried ur solution before .

**Comment by atugushev** [comment]
Could you attach your `requirements.in`?

**Comment by Abhishek-Dev09** [comment]
I m sure , my requirements.in is 100% correct.
