### ISSUE TITLE
pip-sync : no such option: -o 

### ISSUE THREAD

**Issue by xbeta** [jazzband/pip-tools#1203]
#### Environment Versions

1. OS Type: macos 10.15.6
1. Python version: 3.8.5 
1. pip version: pip 20.2.1 
1. pip-tools version: 5.3.1

#### Steps to replicate

1. `cp requirements.txt container/` and `cp requirements.txt lambda/`
2. `pip-sync requirements.txt container/requirements.txt lambda/requirements.txt`

the `requirements.in` that I used

```
autopep8
boto3
Flask
imbalanced-learn
ipython
joblib
matplotlib
numpy<=1.18.5
pandas>=1.0.3
s3transfer
scikit-learn
virtualenv
pip-tools
```

The `requirements.txt` that generated from previous `pip-compile` run

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile - --output-file=- < requirements.in > requirements.txt
#
appdirs==1.4.4            # via virtualenv
appnope==0.1.0            # via ipython
autopep8==1.5.4           # via -r -
backcall==0.2.0           # via ipython
boto3==1.14.43            # via -r -
botocore==1.17.43         # via boto3, s3transfer
certifi==2020.6.20        # via matplotlib
click==7.1.2              # via flask, pip-tools
cycler==0.10.0            # via matplotlib
decorator==4.4.2          # via ipython, traitlets
distlib==0.3.1            # via virtualenv
docutils==0.15.2          # via botocore
filelock==3.0.12          # via virtualenv
flask==1.1.2              # via -r -
imbalanced-learn==0.7.0   # via -r -
ipython-genutils==0.2.0   # via traitlets
ipython==7.17.0           # via -r -
itsdangerous==1.1.0       # via flask
jedi==0.17.2              # via ipython
jinja2==2.11.2            # via flask
jmespath==0.10.0          # via boto3, botocore
joblib==0.16.0            # via -r -, imbalanced-learn, scikit-learn
kiwisolver==1.2.0         # via matplotlib
markupsafe==1.1.1         # via jinja2
matplotlib==3.3.1         # via -r -
numpy==1.18.5             # via -r -, imbalanced-learn, matplotlib, pandas, scikit-learn, scipy
pandas==1.1.0             # via -r -
parso==0.7.1              # via jedi
pexpect==4.8.0            # via ipython
pickleshare==0.7.5        # via ipython
pillow==7.2.0             # via matplotlib
pip-tools==5.3.1          # via -r -
prompt-toolkit==3.0.6     # via ipython
ptyprocess==0.6.0         # via pexpect
pycodestyle==2.6.0        # via autopep8
pygments==2.6.1           # via ipython
pyparsing==2.4.7          # via matplotlib
python-dateutil==2.8.1    # via botocore, matplotlib, pandas
pytz==2020.1              # via pandas
s3transfer==0.3.3         # via -r -, boto3
scikit-learn==0.23.2      # via -r -, imbalanced-learn
scipy==1.5.2              # via imbalanced-learn, scikit-learn
six==1.15.0               # via cycler, pip-tools, python-dateutil, traitlets, virtualenv
threadpoolctl==2.1.0      # via scikit-learn
toml==0.10.1              # via autopep8
traitlets==4.3.3          # via ipython
urllib3==1.25.10          # via botocore
virtualenv==20.0.30       # via -r -
wcwidth==0.2.5            # via prompt-toolkit
werkzeug==1.0.1           # via flask

# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools


```

#### Expected result

```
▶ pip-sync requirements.txt container/requirements.txt lambda/requirements.txt
```
ran with success

#### Actual result

```
▶ pip-sync requirements.txt container/requirements.txt lambda/requirements.txt

Usage:   
  /usr/local/opt/python@3.8/bin/python3.8 -m pip uninstall [options] <package> ...
  /usr/local/opt/python@3.8/bin/python3.8 -m pip uninstall [options] -r <requirements file> ...

no such option: -o
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/piptools/scripts/sync.py", line 147, in cli
    sync.sync(
  File "/usr/local/lib/python3.8/site-packages/piptools/sync.py", line 194, in sync
    check_call(  # nosec
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', 'uninstall', '-y', '-oto3', 'chardet', 'faker', 'gdown', 'greenlet', 'hashpumpy', 'idna', 'ipykernel', 'jupyter-client', 'jupyter-core', 'msgpack', 'neovim', 'protobuf', 'pynvim', 'pysocks', 'pyzmq', 'requests', 'rope', 'ropemode', 'ropevim', 'tbb', 'text-unidecode', 'tornado', 'tqdm']' returned non-zero exit status 2.

```

**Comment by atugushev** [comment]
Hello @xbeta,

Thanks for the issue, good catch! `pip-sync` should wrap each package names by `"`. Sounds like a `good first issue`.

```
'/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', 'uninstall', '-y', '-oto3'
```

**Comment by atugushev** [comment]
@xbeta could you also attach the content of the following files if it's possible:

- container/requirements.txt 
- lambda/requirements.txt

**Comment by xbeta** [comment]
> @xbeta could you also attach the content of the following files if it's possible?
> 
> * container/requirements.txt
> * lambda/requirements.txt

Both are the same content. I already share it above.

**Comment by atugushev** [comment]
Aw, I see. However, I can't reproduce it locally. See the details below.

<details>

```console
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

$  pip --version
pip 20.2.2 from /private/var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp.I11iNG98/.venv/lib/python3.8/site-packages/pip (python 3.8)

$ pip-compile --version
pip-compile, version 5.3.1

$ cat requirements.txt
cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
appdirs==1.4.4            # via virtualenv
appnope==0.1.0            # via ipython
autopep8==1.5.4           # via -r requirements.in
backcall==0.2.0           # via ipython
boto3==1.14.43            # via -r requirements.in
botocore==1.17.43         # via boto3, s3transfer
certifi==2020.6.20        # via matplotlib
click==7.1.2              # via flask, pip-tools
cycler==0.10.0            # via matplotlib
decorator==4.4.2          # via ipython, traitlets
distlib==0.3.1            # via virtualenv
docutils==0.15.2          # via botocore
filelock==3.0.12          # via virtualenv
flask==1.1.2              # via -r requirements.in
imbalanced-learn==0.7.0   # via -r requirements.in
ipython-genutils==0.2.0   # via traitlets
ipython==7.17.0           # via -r requirements.in
itsdangerous==1.1.0       # via flask
jedi==0.17.2              # via ipython
jinja2==2.11.2            # via flask
jmespath==0.10.0          # via boto3, botocore
joblib==0.16.0            # via -r requirements.in, imbalanced-learn, scikit-learn
kiwisolver==1.2.0         # via matplotlib
markupsafe==1.1.1         # via jinja2
matplotlib==3.3.1         # via -r requirements.in
numpy==1.18.5             # via -r requirements.in, imbalanced-learn, matplotlib, pandas, scikit-learn, scipy
pandas==1.1.0             # via -r requirements.in
parso==0.7.1              # via jedi
pexpect==4.8.0            # via ipython
pickleshare==0.7.5        # via ipython
pillow==7.2.0             # via matplotlib
pip-tools==5.3.1          # via -r requirements.in
prompt-toolkit==3.0.6     # via ipython
ptyprocess==0.6.0         # via pexpect
pycodestyle==2.6.0        # via autopep8
pygments==2.6.1           # via ipython
pyparsing==2.4.7          # via matplotlib
python-dateutil==2.8.1    # via botocore, matplotlib, pandas
pytz==2020.1              # via pandas
s3transfer==0.3.3         # via -r requirements.in, boto3
scikit-learn==0.23.2      # via -r requirements.in, imbalanced-learn
scipy==1.5.2              # via imbalanced-learn, scikit-learn
six==1.15.0               # via cycler, pip-tools, python-dateutil, traitlets, virtualenv
threadpoolctl==2.1.0      # via scikit-learn
toml==0.10.1              # via autopep8
traitlets==4.3.3          # via ipython
urllib3==1.25.10          # via botocore
virtualenv==20.0.30       # via -r requirements.in
wcwidth==0.2.5            # via prompt-toolkit
werkzeug==1.0.1           # via flask

# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools

$ md5sum requirements.txt container/requirements.txt lambda/requirements.txt
88eafe3c032ea0c725988b79f1051817  requirements.txt
88eafe3c032ea0c725988b79f1051817  container/requirements.txt
88eafe3c032ea0c725988b79f1051817  lambda/requirements.txt

$ pip-sync requirements.txt container/requirements.txt lambda/requirements.txt -a
Would install:
  appdirs==1.4.4
  appnope==0.1.0
  autopep8==1.5.4
  backcall==0.2.0
  boto3==1.14.43
  botocore==1.17.43
  certifi==2020.6.20
  cycler==0.10.0
  decorator==4.4.2
  distlib==0.3.1
  docutils==0.15.2
  filelock==3.0.12
  flask==1.1.2
  imbalanced-learn==0.7.0
  ipython==7.17.0
  ipython-genutils==0.2.0
  itsdangerous==1.1.0
  jedi==0.17.2
  jinja2==2.11.2
  jmespath==0.10.0
  joblib==0.16.0
  kiwisolver==1.2.0
  markupsafe==1.1.1
  matplotlib==3.3.1
  numpy==1.18.5
  pandas==1.1.0
  parso==0.7.1
  pexpect==4.8.0
  pickleshare==0.7.5
  pillow==7.2.0
  prompt-toolkit==3.0.6
  ptyprocess==0.6.0
  pycodestyle==2.6.0
  pygments==2.6.1
  pyparsing==2.4.7
  python-dateutil==2.8.1
  pytz==2020.1
  s3transfer==0.3.3
  scikit-learn==0.23.2
  scipy==1.5.2
  threadpoolctl==2.1.0
  toml==0.10.1
  traitlets==4.3.3
  urllib3==1.25.10
  virtualenv==20.0.30
  wcwidth==0.2.5
  werkzeug==1.0.1
Would you like to proceed with these changes? [y/N]: y

Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting appnope==0.1.0
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting autopep8==1.5.4
  Using cached autopep8-1.5.4.tar.gz (121 kB)
Collecting backcall==0.2.0
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting boto3==1.14.43
  Using cached boto3-1.14.43-py2.py3-none-any.whl (129 kB)
Collecting botocore==1.17.43
  Using cached botocore-1.17.43-py2.py3-none-any.whl (6.5 MB)
Collecting certifi==2020.6.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting distlib==0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting docutils==0.15.2
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting filelock==3.0.12
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting imbalanced-learn==0.7.0
  Using cached imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
Collecting ipython==7.17.0
  Using cached ipython-7.17.0-py3-none-any.whl (786 kB)
Collecting ipython-genutils==0.2.0
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting itsdangerous==1.1.0
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting jedi==0.17.2
  Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting jinja2==2.11.2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting jmespath==0.10.0
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting joblib==0.16.0
  Using cached joblib-0.16.0-py3-none-any.whl (300 kB)
Collecting kiwisolver==1.2.0
  Using cached kiwisolver-1.2.0-cp38-cp38-macosx_10_9_x86_64.whl (60 kB)
Collecting markupsafe==1.1.1
  Using cached MarkupSafe-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (16 kB)
Collecting matplotlib==3.3.1
  Using cached matplotlib-3.3.1-cp38-cp38-macosx_10_9_x86_64.whl (8.5 MB)
Collecting numpy==1.18.5
  Using cached numpy-1.18.5-cp38-cp38-macosx_10_9_x86_64.whl (15.1 MB)
Collecting pandas==1.1.0
  Using cached pandas-1.1.0-cp38-cp38-macosx_10_9_x86_64.whl (10.6 MB)
Collecting parso==0.7.1
  Using cached parso-0.7.1-py2.py3-none-any.whl (109 kB)
Collecting pexpect==4.8.0
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare==0.7.5
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pillow==7.2.0
  Using cached Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Collecting prompt-toolkit==3.0.6
  Using cached prompt_toolkit-3.0.6-py3-none-any.whl (354 kB)
Collecting ptyprocess==0.6.0
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pygments==2.6.1
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz==2020.1
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting s3transfer==0.3.3
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting scikit-learn==0.23.2
  Using cached scikit_learn-0.23.2-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
Collecting scipy==1.5.2
  Using cached scipy-1.5.2-cp38-cp38-macosx_10_9_x86_64.whl (28.9 MB)
Collecting threadpoolctl==2.1.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting toml==0.10.1
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting traitlets==4.3.3
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting urllib3==1.25.10
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting virtualenv==20.0.30
  Using cached virtualenv-20.0.30-py2.py3-none-any.whl (7.1 MB)
Collecting wcwidth==0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting werkzeug==1.0.1
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: six in ./.venv/lib/python3.8/site-packages (from cycler==0.10.0->-r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp7ius6ig9 (line 8)) (1.15.0)
Requirement already satisfied: click>=5.1 in ./.venv/lib/python3.8/site-packages (from flask==1.1.2->-r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp7ius6ig9 (line 13)) (7.1.2)
Requirement already satisfied: setuptools>=18.5 in ./.venv/lib/python3.8/site-packages (from ipython==7.17.0->-r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp7ius6ig9 (line 15)) (46.1.3)
Building wheels for collected packages: autopep8
  Building wheel for autopep8 (setup.py) ... done
  Created wheel for autopep8: filename=autopep8-1.5.4-py2.py3-none-any.whl size=45286 sha256=1754c405c78f6bbd1df5bcd6f21251ca9e9713e0fa328743ce4acfbad77fb71a
  Stored in directory: /Users/albert/Library/Caches/pip/wheels/5f/b4/93/a30fa45720240e1106155083bac98146542dd614e1e6ce12da
Successfully built autopep8
Installing collected packages: appdirs, appnope, pycodestyle, toml, autopep8, backcall, python-dateutil, docutils, jmespath, urllib3, botocore, s3transfer, boto3, certifi, cycler, decorator, distlib, filelock, itsdangerous, markupsafe, jinja2, werkzeug, flask, numpy, scipy, joblib, threadpoolctl, scikit-learn, imbalanced-learn, pickleshare, ptyprocess, pexpect, pygments, ipython-genutils, traitlets, wcwidth, prompt-toolkit, parso, jedi, ipython, kiwisolver, pyparsing, pillow, matplotlib, pytz, pandas, virtualenv
Successfully installed appdirs-1.4.4 appnope-0.1.0 autopep8-1.5.4 backcall-0.2.0 boto3-1.14.43 botocore-1.17.43 certifi-2020.6.20 cycler-0.10.0 decorator-4.4.2 distlib-0.3.1 docutils-0.15.2 filelock-3.0.12 flask-1.1.2 imbalanced-learn-0.7.0 ipython-7.17.0 ipython-genutils-0.2.0 itsdangerous-1.1.0 jedi-0.17.2 jinja2-2.11.2 jmespath-0.10.0 joblib-0.16.0 kiwisolver-1.2.0 markupsafe-1.1.1 matplotlib-3.3.1 numpy-1.18.5 pandas-1.1.0 parso-0.7.1 pexpect-4.8.0 pickleshare-0.7.5 pillow-7.2.0 prompt-toolkit-3.0.6 ptyprocess-0.6.0 pycodestyle-2.6.0 pygments-2.6.1 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 s3transfer-0.3.3 scikit-learn-0.23.2 scipy-1.5.2 threadpoolctl-2.1.0 toml-0.10.1 traitlets-4.3.3 urllib3-1.25.10 virtualenv-20.0.30 wcwidth-0.2.5 werkzeug-1.0.1
WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
You should consider upgrading via the '/private/var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp.I11iNG98/.venv/bin/python -m pip install --upgrade pip' command.
```

</details>


Could you also show the output of `pip-sync -a`?

**Comment by xbeta** [comment]
Thanks, and that's super weird. I re-run it today and seems to be working.


```
$ pip-sync requirements.txt container/requirements.txt 
Everything up-to-date
(env) 
```
