### ISSUE TITLE
System packages are being uninstalled in Ubuntu 20.04

### ISSUE THREAD

**Issue by joshuaspence** [jazzband/pip-tools#1213]
Running `pip-sync` on Ubuntu 20.04 is removing the following packages, which seem to be installed by default.

```
Package       Version   
------------- ----------
appdirs       1.4.3     
CacheControl  0.12.6    
certifi       2019.11.28
chardet       3.0.4     
colorama      0.4.3     
contextlib2   0.6.0     
distlib       0.3.0     
distro        1.4.0     
html5lib      1.0.1     
idna          2.8       
ipaddr        2.2.0     
lockfile      0.12.2    
msgpack       0.6.2     
packaging     20.3      
pep517        0.8.2     
pip           20.0.2    
pkg-resources 0.0.0     
progress      1.5       
pyparsing     2.4.6     
pytoml        0.1.21    
requests      2.22.0    
retrying      1.3.3     
setuptools    44.0.0    
six           1.14.0    
urllib3       1.25.8    
webencodings  0.5.1     
wheel         0.34.2
```

#### Environment Versions

1. OS Type: Ubuntu 20.04
1. Python version: 3.8.2
1. pip version:  20.0.2
1. pip-tools version: 5.3.1

#### Steps to replicate

I've managed to reproduce the issue with the following `Dockerfile`:

```
ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}

ENV LC_ALL=C.UTF-8

RUN apt-get update && apt-get --yes install python3 python3-virtualenv
RUN python3 -m virtualenv --python python3 venv
RUN . venv/bin/activate && pip install pip-tools

RUN touch requirements.txt
RUN . venv/bin/activate && pip-sync && pip-sync
```

#### Expected result

Building the Docker image with `UBUNTU_VERSION=bionic` succeeds.

#### Actual result

Building the Docker image with `UBUNTU_VERSION=focal` fails.

```
Step 8/8 : RUN . venv/bin/activate && pip-sync && pip-sync
 ---> Running in 1e01f51202a6
Found existing installation: appdirs 1.4.3
Uninstalling appdirs-1.4.3:
  Successfully uninstalled appdirs-1.4.3
Found existing installation: CacheControl 0.12.6
Uninstalling CacheControl-0.12.6:
  Successfully uninstalled CacheControl-0.12.6
Found existing installation: certifi 2019.11.28
Uninstalling certifi-2019.11.28:
  Successfully uninstalled certifi-2019.11.28
Found existing installation: chardet 3.0.4
Uninstalling chardet-3.0.4:
  Successfully uninstalled chardet-3.0.4
Found existing installation: colorama 0.4.3
Uninstalling colorama-0.4.3:
  Successfully uninstalled colorama-0.4.3
Found existing installation: contextlib2 0.6.0
Uninstalling contextlib2-0.6.0:
  Successfully uninstalled contextlib2-0.6.0
Found existing installation: distlib 0.3.0
Uninstalling distlib-0.3.0:
  Successfully uninstalled distlib-0.3.0
Found existing installation: distro 1.4.0
Uninstalling distro-1.4.0:
  Successfully uninstalled distro-1.4.0
Found existing installation: html5lib 1.0.1
Uninstalling html5lib-1.0.1:
  Successfully uninstalled html5lib-1.0.1
Found existing installation: idna 2.8
Uninstalling idna-2.8:
  Successfully uninstalled idna-2.8
Found existing installation: ipaddr 2.2.0
Uninstalling ipaddr-2.2.0:
  Successfully uninstalled ipaddr-2.2.0
Found existing installation: lockfile 0.12.2
Uninstalling lockfile-0.12.2:
  Successfully uninstalled lockfile-0.12.2
Found existing installation: msgpack 0.6.2
Uninstalling msgpack-0.6.2:
  Successfully uninstalled msgpack-0.6.2
Found existing installation: packaging 20.3
Uninstalling packaging-20.3:
  Successfully uninstalled packaging-20.3
Found existing installation: pep517 0.8.2
Uninstalling pep517-0.8.2:
  Successfully uninstalled pep517-0.8.2
Found existing installation: progress 1.5
Uninstalling progress-1.5:
  Successfully uninstalled progress-1.5
Found existing installation: pyparsing 2.4.6
Uninstalling pyparsing-2.4.6:
  Successfully uninstalled pyparsing-2.4.6
Found existing installation: pytoml 0.1.21
Uninstalling pytoml-0.1.21:
  Successfully uninstalled pytoml-0.1.21
Found existing installation: requests 2.22.0
Uninstalling requests-2.22.0:
  Successfully uninstalled requests-2.22.0
Found existing installation: retrying 1.3.3
Uninstalling retrying-1.3.3:
  Successfully uninstalled retrying-1.3.3
Found existing installation: urllib3 1.25.8
Uninstalling urllib3-1.25.8:
  Successfully uninstalled urllib3-1.25.8
Found existing installation: webencodings 0.5.1
Uninstalling webencodings-0.5.1:
  Successfully uninstalled webencodings-0.5.1
Traceback (most recent call last):
  File "/venv/bin/pip-sync", line 5, in <module>
    from piptools.scripts.sync import cli
  File "/venv/lib/python3.8/site-packages/piptools/scripts/sync.py", line 10, in <module>
    from pip._internal.utils.misc import get_installed_distributions
  File "/venv/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 23, in <module>
    from pip._vendor.retrying import retry  # type: ignore
ModuleNotFoundError: No module named 'pip._vendor.retrying'
The command '/bin/sh -c . venv/bin/activate && pip-sync && pip-sync' returned a non-zero code: 1
```

**Comment by joshuaspence** [comment]
On Ubuntu 16.04, these are the Python packages installed within a newly created virtualenv:

```
Package       Version
------------- -------
pip           20.2.3
pkg-resources 0.0.0
setuptools    50.3.0
wheel         0.35.1
```

On Ubuntu 20.04:

```
Package       Version   
------------- ----------
appdirs       1.4.3     
CacheControl  0.12.6    
certifi       2019.11.28
chardet       3.0.4     
colorama      0.4.3     
contextlib2   0.6.0     
distlib       0.3.0     
distro        1.4.0     
html5lib      1.0.1     
idna          2.8       
ipaddr        2.2.0     
lockfile      0.12.2    
msgpack       0.6.2     
packaging     20.3      
pep517        0.8.2     
pip           20.0.2    
pkg-resources 0.0.0     
progress      1.5       
pyparsing     2.4.6     
pytoml        0.1.21    
requests      2.22.0    
retrying      1.3.3     
setuptools    44.0.0    
six           1.14.0    
urllib3       1.25.8    
webencodings  0.5.1     
wheel         0.34.2
```

**Comment by vasinkd** [comment]
Pretty much the same thing happend to me. After pip-sync I started to receive this message:
```
ModuleNotFoundError: No module named 'pip._vendor.contextlib2'
``
Replacing virtualenv with venv as a tool for creating Python virtual environments solved a problem.

**Comment by hmpf** [comment]
I'm trying to use pip-tools from tox, but tox fails with

```
ImportError: cannot import name 'appdirs' from 'pip._vendor' 
```

for assumedly the same reason.

**Comment by AndydeCleyre** [comment]
I'm not totally clear on this yet, but it seems upgrading `pip` to `>=20.1` within the venv avoids this issue.

`pip-tools` master currently requires `pip >= 20.1`, while the release `5.3.1` requires only `pip >= 20.0`. 

@atugushev Is it simply time to cut a new, small release, the last one before the new resolver shakes everything up next week?

**Comment by AndydeCleyre** [comment]
Actually, this isn't particular to `pip-tools`. Look at this, inside an `ubuntu:20.04` container:

```console
# apt -y update &>/dev/null
# apt -y --no-install-recommends install python3-virtualenv &>/dev/null
# virtualenv venv
# . ./venv/bin/activate
# pip --version
Traceback (most recent call last):
  File "/venv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 26, in <module>
    from pip._internal.models.format_control import FormatControl
  File "/venv/lib/python3.8/site-packages/pip/_internal/models/format_control.py", line 4, in <module>
    from pip._vendor.packaging.utils import canonicalize_name
ModuleNotFoundError: No module named 'pip._vendor.packaging'
```

But with `venv`:

```console
# apt -y update &>/dev/null
# apt -y --no-install-recommends install python3-venv &>/dev/null
# python3 -m venv venv
# . ./venv/bin/activate
# pip --version
pip 20.0.2 from /venv/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by AndydeCleyre** [comment]
So based on my last comment I'm thinking this is a virtualenv/ubuntu issue, that we can close it here, and that users should use venv rather than virtualenv.

Ok to close?

@joshuaspence @atugushev

**Comment by atugushev** [comment]
@AndydeCleyre  

I think the issue could be closed since it doesn't look like there's any action required regarding pip-tools. Workarounds:
 - create virtualenv without seeds `virtualenv --no-seed`
 - use `venv`
 - use `pip install -r requirements.txt` instead of `pip-sync`

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
