### ISSUE TITLE
No local imports into setup.py?

### ISSUE THREAD

**Issue by njiles** [jazzband/pip-tools#1221]
`pip-compile` fails if there are any local imports in setup.py. See below for traceback.

#### Environment Versions

1. OS Type: macOS
1. Python version: 3.9.0
1. pip version: 20.2.4
1. pip-tools version: 5.3.1

#### Steps to replicate

Structure:
```
src/
    __init__.py  # empty
    _version.py
setup.py
```

_version.py:
```python
__version__ = "0.0.1"
```

setup.py:
```python
from setuptools import find_packages, setup
from src._version import __version__

setup(
    name=“package-name”,
    version=__version__,
    packages=find_packages(),
)
```

Install pip-tools into a clean virtual environment, then run `pip-compile`.

#### Expected result

`pip-compile` runs and generates a requirements.txt file (empty in this MWE, as setup.py doesn't define any requirements).

#### Actual result

```
Traceback (most recent call last):
  File "/Users/njiles/anaconda3/envs/pip-tools-example/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/site-packages/piptools/scripts/compile.py", line 393, in cli
    dist = run_setup(src_file)
  File "/Users/njiles/anaconda3/envs/pip-tools-example/lib/python3.9/distutils/core.py", line 215, in run_setup
    exec(f.read(), g)
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'src'
```

**Comment by atugushev** [comment]
Hello @njiles,

Thanks for the issue. Invoking `pip-tools` as a module might help:

```
python -m piptools compile
```

You can read more information about the difference between `pip-compile` and `python -m piptools compile` [here](https://blog.ganssle.io/articles/2019/08/test-as-installed.html) (in pytets context).

Also, AFAIK, it's not recommend to import any module that is not installed at the build time in `setup.py` file.

**Comment by njiles** [comment]
Thanks for the workaround - invoking pip-tools as a module to add the current location to `sys.path` solves the problem for me! From my point of view I'm happy for this to be closed, thank you 🙂 

---

> Also, AFAIK, it's not recommend to import any module that is not installed at the build time in setup.py file.

This approach is number 6 on [this list](https://packaging.python.org/guides/single-sourcing-package-version) from the PyPA Python Packaging User Guide - it does come with the warning

> Warning
> Although this technique is common, beware that it will fail if `sample/__init__.py` imports packages from `install_requires` dependencies, which will very likely not be installed yet when `setup.py` is run.

but this doesn't seem (to me at least) to apply to this case?

**Comment by atugushev** [comment]
I'll close this based on the above. Thanks for the issue!
