### ISSUE TITLE
pip 20.3b1: TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'

### ISSUE THREAD

**Issue by JulienPalard** [jazzband/pip-tools#1228]
#### Environment Versions

1. OS: Debian Bullseye
1. Python version: `cpython 3.9.0`, compiled myself.
1. pip version:  `20.3b1`
1. pip-tools version: `5.3.1`

#### Steps to replicate

```
python3.9 -m venv .venv; source .venv/bin/activate
echo jedi > requirements-dev.in
pip install --upgrade --pre pip wheel setuptools pip-tools
pip-compile requirements-dev.in
```

Note that it does happen with `jedi` but not with `black` (had not tested other packages).

#### Result

```Traceback (most recent call last):
  File "/tmp/.venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/tmp/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/.venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/scripts/compile.py", line 458, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/resolver.py", line 173, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/resolver.py", line 278, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/resolver.py", line 388, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/repositories/local.py", line 75, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 231, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/tmp/.venv/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 155, in resolve_reqs
    preparer = self.command.make_requirement_preparer(
TypeError: make_requirement_preparer() got an unexpected keyword argument 'wheel_download_dir'
/home/mdk/.local/lib/python3.9/tempfile.py:817: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpawdrn2ytsource'>
  _warnings.warn(warn_message, ResourceWarning)
/home/mdk/.local/lib/python3.9/tempfile.py:817: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp3sv7im0lbuild'>
  _warnings.warn(warn_message, ResourceWarning)
/home/mdk/.local/lib/python3.9/tempfile.py:817: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmps3_jugijsource'>
  _warnings.warn(warn_message, ResourceWarning)
/home/mdk/.local/lib/python3.9/tempfile.py:817: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpfnqnztwpbuild'>
  _warnings.warn(warn_message, ResourceWarning)
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.0.13', 50038), raddr=('151.101.192.223', 443)>
```

**Comment by atugushev** [comment]
Thanks, @JulienPalard for the issue! `pip-20.3` support is on the way. See #1216.

**Comment by zhangchi1** [comment]
It seems like pip==21.1.2 has the same issue? Not sure if we have another open ticket for this?

**Comment by atugushev** [comment]
@zhangchi1 can't reproduce locally. Did you use the latest pip-tools?

**Comment by ofekisr** [comment]
@atugushev 
me too
pip               21.1.3
pip-compile-multi 2.4.1   
pip-tools         6.2.0
wheel             0.36.2
setuptools        57.0.0

**Comment by sergey-zakharov** [comment]
only pip-tools 5.4.0+ supports pip 20.3+
In my case update pip-tools-6.2.0 with pip-21.1.3 solved a problem

**Comment by Evergreenies** [comment]
@sergey-zakharov I have the same issue.
 Does anybody found any solution?

**Comment by zhangchi1** [comment]
Are you using pip= 21.1.2? Maybe try pip upgrade to pip=21.1.3 or above? > @sergey-zakharov I have the same issue.
> 
>  Does anybody found any solution?

**Comment by Evergreenies** [comment]
Using `pip==21.2.4` and `pip-tools==6.2.0`.
I also tried, `pip==21.2.3` with `pip-tools==5.5.0`.

**Comment by DOsinga** [comment]
@Evergreenies `pip==21.2.4` and `pip-tools==6.2.0` worked for me ...
