### ISSUE TITLE
pip-compile fails on egg_info with --build-isolation

### ISSUE THREAD

**Issue by stefansjs** [jazzband/pip-tools#1296]
pip-compile fails to compile dependencies when --build-isolation is specified and a dependency requires something installed to run setup.py. Since this is the whole point of pyproject.toml, I would expect `python setup.py egg_info` to be run in the dependencie's build backend.

I don't have any idea how to fix this, but it's clear that `python setup.py egg_info` is not a supported use case of PEP517 build isolation.

#### Environment Versions

1. Mac OS
1. Python version: 3.6.8
1. pip version:  20.3.3
1. pip-tools version: 5.5.0

#### Steps to replicate

1. put madmom in `requirements.in`
2. pip-compile --build-isolation
3. profit

#### Expected result

a requirements.txt

#### Actual result

```
  Collecting madmom==0.16.1
    Using cached madmom-0.16.1.tar.gz (20.0 MB)
      ERROR: Command errored out with exit status 1:
       command: /Users/stefansullivan/.pyenv/versions/3.6.8/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rs/5kc_ycpd3pl3xh9j0jztbpl80000gp/T/pip-resolver-nlos8qa6/madmom/setup.py'"'"'; __file__='"'"'/private/var/folders/rs/5kc_ycpd3pl3xh9j0jztbpl80000gp/T/pip-resolver-nlos8qa6/madmom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rs/5kc_ycpd3pl3xh9j0jztbpl80000gp/T/pip-pip-egg-info-gfndmk4i
           cwd: /private/var/folders/rs/5kc_ycpd3pl3xh9j0jztbpl80000gp/T/pip-resolver-nlos8qa6/madmom/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/rs/5kc_ycpd3pl3xh9j0jztbpl80000gp/T/pip-resolver-nlos8qa6/madmom/setup.py", line 12, in <module>
          from Cython.Build import cythonize, build_ext
      ModuleNotFoundError: No module named 'Cython'
      ----------------------------------------
Traceback (most recent call last):
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/scripts/compile.py", line 452, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/resolver.py", line 178, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/resolver.py", line 275, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/resolver.py", line 385, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/repositories/local.py", line 76, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 248, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 203, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 385, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 337, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/Users/stefansullivan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by stefansjs** [comment]
Looking at the stack trace, I see two important lines:

From metadata_legacy.py:69
```python
    with build_env:
        call_subprocess(
            args,
            cwd=source_dir,
            command_desc='python setup.py egg_info',
        )
```

and from req_install.py:527
```python
        if not self.use_pep517:
            assert self.unpacked_source_directory

            return generate_metadata_legacy(
                build_env=self.build_env,
                setup_py_path=self.setup_py_path,
                source_dir=self.unpacked_source_directory,
                isolated=self.isolated,
                details=self.name or "from {}".format(self.link)
            )
```

I can't explain why I'm in the `not self.use_pep517` branch. Shouldn't the `--build-isolation` flag put me into that state?

**Comment by atugushev** [comment]
Hello @stefansjs,

Thanks for the report! According to [setup.py](https://github.com/CPJKU/madmom/blob/215adc81426498422e895e4c0a436bf6b7fe618f/setup.py#L12-L15), `madmom` imports  `ctyhon` and `numpy` at the build time (see the log below), so you have to satisfy those requirements first.

```
ModuleNotFoundError: No module named 'Cython'
```

Could you try to install `cython` and `numpy` (see the list of full [prequisites](https://github.com/CPJKU/madmom#prerequisites)), and run `pip-compile`?

**Comment by stefansjs** [comment]
Yeah, cython is definitely listed in pyproject.toml. I did successfully `pip-compile` madmom after `pip install`ing cython. But shouldn't `--build-isolation` handle this and run egg_info in the build backend for madmom?

**Comment by atugushev** [comment]
Even though `madmom` has `pyproject.toml` in VCS, but the source package [uploaded on PyPI](https://pypi.org/project/madmom) hasn't:

```console
$ wget -q https://files.pythonhosted.org/packages/c7/a3/9f3de3e8068a3606331134d96b84c8db4f7624d6715be8ab3c1f56e6731d/madmom-0.16.1.tar.gz

$ tar -ztvf madmom-0.16.1.tar.gz | egrep '(pyproject\.toml|setup\.py)'
-rw-r--r--  0 sb     staff    3375 Nov 14  2018 madmom-0.16.1/setup.py
```

That's why pip uses `setup.py` instead of `pyproject.toml`.

**Comment by atugushev** [comment]
The fix is to add the following line to the `MANIFEST.in` to include `pyproject.toml` to the source dist:

```
include pyproject.toml
```

@stefansjs would you mind to raise an issue or open a PR on https://github.com/CPJKU/madmom?

**Comment by stefansjs** [comment]
Oh, thank you for finding that. Yes I'll raise an issue with madmom maintainers.

**Comment by atugushev** [comment]
See also https://github.com/CPJKU/madmom/issues/463
