### ISSUE TITLE
Can`t generate requirements.txt with graphene or graphene-django in `.in` file

### ISSUE THREAD

**Issue by ValkoVolodya** [jazzband/pip-tools#1327]
#### Environment Versions

1. OS Type - Fedora
1. Python version: `Python 3.6.9`
1. pip version: `pip 21.0.1`
1. pip-tools version: `version 5.2.0`

#### Steps to replicate

1. Add graphene dependencies to `requirements.in` file:
```
graphene-django==2.10.1
graphene==2.1.8
```

2. run `pip-compile requirements.in`

#### Expected result

Successfully generated `requirements.txt`

#### Actual result

Got an error:

```python-traceback
 ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-kqmhwpxe/promise/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-kqmhwpxe/promise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4l9__1sf
           cwd: /tmp/pip-resolver-kqmhwpxe/promise/
      Complete output (1 lines):
      error in promise setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in typing>=3.6.4; python_version < '3.5' at ; python_version < '3.5'
      ----------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/lib/python3.7/site-packages/piptools/resolver.py", line 380, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.7/site-packages/piptools/repositories/local.py", line 74, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 229, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/usr/local/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 181, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/home/v.valko/.local/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by webknjaz** [comment]
@ValkoVolodya the information you submitted is probably not enough to judge what happened but it seems like the package called "promise" has invalid metadata.
When a package in the tree does not have a wheel available, pip would attempt to build it from sdist to get its metadata and dependencies. It looks like it hit such a package but it's broken. There's nothing pip-tools can do about it, the package in question must be fixed.

**Comment by webknjaz** [comment]
Looking at https://pypi.org/project/promise/#files it seems like my judgment was correct. I bet you can reproduce this with a simple `pip install promise` on your machine.
OTOH I noticed that the earlier versions actually have wheels published so your workaround could be capping it like `promise < 2.3`.

P.S. I think pip-tools will be able to provide more control over this when resolvelib is used instead of calling pip directly.

**Comment by webknjaz** [comment]
Oh, and you could also ask the maintainers of "promise" to simply upload a wheel for that version.

**Comment by ValkoVolodya** [comment]
@webknjaz thanks for help)
