### ISSUE TITLE
pip-compile consumes up to 10.5 GB RAM when resolving PyTorch 1.8.1 with CUDA

### ISSUE THREAD

**Issue by martinkonopka** [jazzband/pip-tools#1371]
When trying to compile requirements with PyTorch 1.8.1 with CUDA using the `pip-compile`, it consumes huge amount of RAM (with spike up to 10.5 GB). The package itself is of 3 GB size on Windows.

If the package is already cached by `pip`, it happens immediately when running `pip-compile` which did not processed this package before (or anytime when rebuilding the cache with `-r`). If the package is not cached by `pip`, it is first downloaded and the problem occurs. Windows on PC with 16 GB RAM starts swapping 3 times, but the `pip-compile` manages to finish it. After the results are cached by `pip-compile`, it does not happen.

I tried to replicate it on Ubuntu-20.04 running in WSL2 with 3GB allocated RAM, `pip-compile` crashes with `MemoryError` (see stack trace at the end of the post).

![pip-compile_memory_torch-cuda](https://user-images.githubusercontent.com/9091988/113208465-1c150a00-9272-11eb-8304-55c5a7fb7136.png)

#### Environment Versions

Occurs both on Windows and Ubuntu in WSL2. 

1. OS Type: Windows 10 Version 20H2 (OS Build 19042.867, 16 GB RAM) or Ubuntu-20.04 in WSL2 (3 GB RAM)
1. Python version: 3.7.9, occurs also on 3.8.7
1. pip version: 21.0.1
1. pip-tools version: 6.0.1, occurs also on 5.5.0

#### Steps to replicate

1. Create `requirements.in` with PyTorch 1.8.1 with CUDA:
```shell
-f https://download.pytorch.org/whl/torch_stable.html
torch==1.8.1+cu111
```
2. Create a virtual environment with Python 3.7 (or 3.8):
```shell
# Windows
py -3.7 -m venv .env
.\.env\Scripts\activate

# Ubuntu
python3.7 -m venv .env
source .env/bin/activate
```
3. Install `pip-tools==6.0.1` (or 5.5.0, other versions were not tested):
```
python -m pip install pip-tools==6.0.1
```
4. Try to compile `requirements.txt`:
```
pip-compile requirements.in -r
```
5. The PyTorch package with CUDA will be downloaded (~3 GB on Windows, ~2 GB on Ubuntu).
6. Observe memory usage spikes.

The problem can also occur if the package is already cached by pip. Before compiling requirements, run:
```
python -m pip install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip-compile requirements.in -r
```

#### Expected result

Lower memory usage that does not hog the computer with total 16 GB RAM installed. 

#### Actual result

High memory usage with spikes up to 10 GB for `pip-compile`. 

On Ubuntu with limited amount of RAM, the process fails with `Memory Error` (in this test I had other packages in requirements, but they have no or little effect on the result):

```
$ pip-compile requirements.in --verbose
Using indexes:
  https://pypi.org/simple

Using links:
  https://download.pytorch.org/whl/torch_stable.html

                          ROUND 1
Current constraints:
  matplotlib==3.4.0 (from -r requirements.in (line 5))
  numpy==1.20.1 (from -r requirements.in (line 3))
  seaborn==0.11.1 (from -r requirements.in (line 6))
  torch==1.8.1+cu111 (from -r requirements.in (line 2))
  transformers==4.4.2 (from -r requirements.in (line 4))

Finding the best candidates:
  found candidate matplotlib==3.4.0 (constraint was ==3.4.0)
  found candidate numpy==1.20.1 (constraint was ==1.20.1)
  found candidate seaborn==0.11.1 (constraint was ==0.11.1)
  found candidate torch==1.8.1+cu111 (constraint was ==1.8.1+cu111)
  found candidate transformers==4.4.2 (constraint was ==4.4.2)

Finding secondary dependencies:
  numpy==1.20.1 not in cache, need to check index
  Collecting numpy==1.20.1
    Using cached numpy-1.20.1-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
  numpy==1.20.1             requires -
  transformers==4.4.2       requires filelock, importlib-metadata; python_version < "3.8", numpy>=1.17, packaging, regex!=2019.12.17, requests, sacremoses, tokenizers<0.11,>=0.10.1, tqdm>=4.27
  torch==1.8.1+cu111 not in cache, need to check index
  Collecting torch==1.8.1+cu111
    Downloading https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp37-cp37m-linux_x86_64.whl (1982.2 MB)
       |████████████████████████████████| 1982.2 MB 5.0 MB/s eta 0:00:01Traceback (most recent call last):
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/scripts/compile.py", line 419, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/resolver.py", line 178, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/resolver.py", line 277, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/resolver.py", line 386, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 224, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 186, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 385, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 337, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in _prepare_linked_requirement
    self.download_dir, hashes,
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 234, in unpack_url
    hashes=hashes,
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 108, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/network/download.py", line 163, in __call__
    for chunk in chunks:
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 159, in iter
    for x in it:
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 88, in response_chunks
    decode_content=False,
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 65, in read
    self._close()
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 309, in cache_response
    cache_url, self.serializer.dumps(request, response, body=body)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 72, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 960, in pack
    self._pack(obj)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 944, in _pack
    len(obj), dict_iteritems(obj), nest_limit - 1
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 1045, in _pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 944, in _pack
    len(obj), dict_iteritems(obj), nest_limit - 1
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 1044, in _pack_map_pairs
    self._pack(k, nest_limit - 1)
  File "/mnt/c/Users/user/Projects/pip-tools_torch_cuda/.env/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 896, in _pack
    return self._buffer.write(obj)
MemoryError
```

**Comment by AndydeCleyre** [comment]
FWIW I tried this on my laptop (Arch, 7.65GiB RAM) with Python 3.8.7 and 3.9.2 and pip-tools master, 5.5.0, and 6.0.1. It always succeeded, but did take ~1m30s-1m40s each time, and collect all available memory temporarily:

![image](https://user-images.githubusercontent.com/1787385/113599466-a6f85a80-960c-11eb-8925-55064ac6d5b1.png)

![image](https://user-images.githubusercontent.com/1787385/113599878-3e5dad80-960d-11eb-81db-bd66d639f51f.png)

**Comment by martinkonopka** [comment]
After further testing with my colleague, it seems the root cause of this behavior is actually `pip`, not `pip-tools`. It occurs with `pip-sync` but also with bare `pip install -r requirements.txt` if the `torch` package is cached by the `pip`. Setting `pip` to not use its cache or purging it prior to running `pip-sync` partially solves this problem, but the package must be redownloaded everytime. 

https://github.com/ionrock/cachecontrol/issues/145 

Passing args to `pip` from `pip-tools` commands could help in this situation.

**Comment by atugushev** [comment]
I'll close this since it doesn't look like there's any action required regarding pip-tools. Thanks for the issue!
