### ISSUE TITLE
future: OSError with invalid zip/wheel file (Python 3)

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#147]
Running `cram tests/pip-compile-allows-inheritance.t` (from https://github.com/nvie/pip-tools/pull/146) on Python 3.4.3 will result in the following error:

```
Traceback (most recent call last):

  File "FOO/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
  File "/tmp/cramtests-R1yZAN/pip-compile-allows-inheritance.t/FOO/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/cramtests-R1yZAN/pip-compile-allows-inheritance.t/FOO/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/tmp/cramtests-R1yZAN/pip-compile-allows-inheritance.t/FOO/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/cramtests-R1yZAN/pip-compile-allows-inheritance.t/FOO/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "…/pip-tools/piptools/scripts/compile.py", line 185, in cli
    compile_specs(src_files, include_sources=include_sources, dry_run=dry_run)
  File "…/pip-tools/piptools/scripts/compile.py", line 117, in compile_specs
    pinned_spec_set = resolver.resolve()
  File "…/pip-tools/piptools/resolver.py", line 44, in resolve
    if not self.resolve_one_round():
  File "…/pip-tools/piptools/resolver.py", line 28, in resolve_one_round
    new_deps = self.find_new_dependencies()
  File "…/pip-tools/piptools/resolver.py", line 91, in find_new_dependencies
    all_deps = self.find_all_dependencies()
  File "…/pip-tools/piptools/resolver.py", line 74, in find_all_dependencies
    pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
  File "…/pip-tools/piptools/package_manager.py", line 314, in get_dependencies
    deps = self.extract_dependencies(path)
  File "…/pip-tools/piptools/package_manager.py", line 471, in extract_dependencies
    self.unpack_archive(path, unpack_dir)
  File "…/pip-tools/piptools/package_manager.py", line 393, in unpack_archive
    archive = zipfile.ZipFile(path)
  File "…/pyenv/3.4.3/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "…/pyenv/3.4.3/lib/python3.4/zipfile.py", line 996, in _RealGetContents
    fp.seek(self.start_dir, 0)
OSError: [Errno 22] Invalid argument
[1]
```

This is caused by an invalid zip/wheel file, which cannot be listed using `unzip -l`, too:

```
Archive:  /tmp/cramtests-S5o3ev/pip-compile-allows-inheritance.t/.pip-tools/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fany%2Fp%2Fpython-dateutil%2Fpython_dateutil-2.4.2-py2.py3-none-any.whl

caution:  zipfile comment truncated
error [/tmp/cramtests-S5o3ev/pip-compile-allows-inheritance.t/.pip-tools/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fany%2Fp%2Fpython-dateutil%2Fpython_dateutil-2.4.2-py2.py3-none-any.whl]:  missing 4092298748 bytes in zipfile
  (attempting to process anyway)
error [/tmp/cramtests-S5o3ev/pip-compile-allows-inheritance.t/.pip-tools/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fany%2Fp%2Fpython-dateutil%2Fpython_dateutil-2.4.2-py2.py3-none-any.whl]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

I think this might be related to (the code touched in) 780ea25e.

It appears to work properly in Python 2.

**Comment by davidovich** [comment]
Closing as old, and not using cram anymore.
