### ISSUE TITLE
pip-compile causes AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by jace** [jazzband/pip-tools#1541]
After upgrading to macOS Monterey, pip-compile no longer works. I've created a fresh virtualenv and confirmed that the problem is not caused by a stale virtualenv.

#### Environment Versions

1. OS Type: macOS Monterey 12.0.1
1. Python version: 3.9.9
1. pip version: 21.3.1
1. pip-tools version: 6.4.0

#### Steps to replicate

1. `brew install python` to get 3.9.9
2. `mkvirtualenv pip-tools-test`
3. `workon pip-tools-test`
4. `pip-compile requirements.in`

#### Expected result

pip-compile runs normally.

#### Actual result

```
    ERROR: Command errored out with exit status 1:
     command: /Users/jace/.virtualenvs/pip-tools-test/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setup.py'"'"'; __file__='"'"'/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-pip-egg-info-ut96fk2g
         cwd: /private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/hk/3vk8wsrd70bcv13bxwpfctkc0000gn/T/pip-resolver-j08_ltsp/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
Traceback (most recent call last):
  File "/Users/jace/.virtualenvs/pip-tools-test/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/scripts/compile.py", line 466, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/resolver.py", line 175, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/resolver.py", line 319, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/resolver.py", line 428, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 236, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 199, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 332, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 561, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 59, in generate_metadata
    call_subprocess(
  File "/Users/jace/.virtualenvs/pip-tools-test/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jace** [comment]
I think this may have been caused by one of my dependencies having an obsolete requirement. The problem has gone away before I could figure out which dependency was causing this. Closing this issue for now.
