### ISSUE TITLE
pip-compile error

### ISSUE THREAD

**Issue by tonnyhideyori** [jazzband/pip-tools#1544]
#### Environment Versions

1. Ubuntu 20
1. Python version: `Python 3.8.10`
1. pip version: `21.3.1`
1. pip-tools version: `6.4.0`

#### Steps to replicate

1. create a base.txt with all module required.
2. then create another text file (eg development.txt) file with a line start `-r base.tx`
2. `pip-compile development.txt`

#### Expected result

The result of the compile 

#### Actual result
```
ERROR: Command errored out with exit status 1:
     command: /app/xx/DependencyTrackpython_xxx/requirements/env/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-deo9y29d/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-deo9y29d/psycopg2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-epd9rbhb
         cwd: /tmp/pip-resolver-deo9y29d/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-epd9rbhb/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-epd9rbhb/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-epd9rbhb/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-epd9rbhb/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-epd9rbhb/psycopg2.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
Traceback (most recent call last):
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/scripts/compile.py", line 466, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/resolver.py", line 175, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/resolver.py", line 319, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/resolver.py", line 428, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 236, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 199, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 332, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 561, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 59, in generate_metadata
    call_subprocess(
  File "/app/xx/DependencyTrackpython_xxx/requirements/env/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
    I installed `psycopg2-binary` as the error suggested but the problem persisted. 
**NB**: I run this in venv
Hence what could be the problem. Thanks

**Comment by alflanagan** [comment]
Looks like you're missing the PostgreSQL development library -- it includes pg_config. That's not a pip install, it's in your package manager, `apt` or `yum` or `dnf` or .... What OS?

**Comment by AndydeCleyre** [comment]
Thanks!

Are you sure you've removed `psycopg2` from all input and output files, and can you share them for a reliable reproduction?

**Comment by AndydeCleyre** [comment]
Hello! Just adding a friendly ping to @tonnyhideyori to please provide more details on reproducing this issue. Thanks!

**Comment by cristina0botez** [comment]
Hi! I'm getting this same error. I have the following in my `requirements.in` file:
```
SQLAlchemy
psycopg2
```
 and I ran `pip-compile requirements.in`
I want to install these dependencies on a docker container, but I am generating `requirements.txt` on the host machine.

**Comment by AndydeCleyre** [comment]
The psycopg2 package has extra non-python requirements for doing any useful inspection, so you'll need those on the system running pip-compile.

https://www.psycopg.org/docs/install.html

Alternatively, you may use the psycopg2-binary package to avoid that.

**Comment by AndydeCleyre** [comment]
See also: #1583
