### ISSUE TITLE
Inconsistent `pip-compile` behavior for package upgrade using `lt` (less than) constraint

### ISSUE THREAD

**Issue by alichaudry** [jazzband/pip-tools#1568]
Inconsistent behavior with `lt` (less than) constraint in `pip-compile` with `mypy` package. Specifically, `"mypy<0.9"` throws an error whereas `"mypy<0.900"` works as intended. I have a suspicion that this may be a `pip` problem and not specifically a `pip-tools` bug, but I don't know how to test for that as I'm unfamiliar with pip (I almost exclusively use `conda` for python + package management).

#### Environment Versions

1. OS: `Ubuntu 18.04.06 LTS` (running on WSL2)
1. Python version: `Python 3.7.12`
1. pip version: `pip 21.3 from ~/miniconda3/envs/env/lib/python3.7/site-packages/pip (python 3.7)`
1. pip-tools version: `pip-compile, version 6.4.0`

#### Steps to replicate

1. (optional) activate python env, make sure pip is available
1. (optional) if requirements.in is not already available: `touch requirements.in`
1. `pip install mypy==0.790`
1. `pip-compile --upgrade-package "mypy<0.9"`

#### Expected result

```python
(env) user@machine:~/repo/test$ pip-compile --upgrade-package "mypy<0.9"
#
# This file is autogenerated by pip-compile with python 3.7
# To update, run:
#
#    pip-compile
#
mypy==0.812
mypy-extensions==0.4.3
    # via mypy
typed-ast==1.4.1
    # via mypy
typing-extensions==3.7.4.2
    # via mypy
```

#### Actual result

```python
(env) user@machine:~/repo/test$ pip-compile --upgrade-package "mypy<0.9"
    ERROR: Command errored out with exit status 1:
     command: ~/miniconda3/envs/env/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-o6ysh1bi/wsgiref/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-o6ysh1bi/wsgiref/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2ppyhju3
         cwd: /tmp/pip-resolver-o6ysh1bi/wsgiref/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-resolver-o6ysh1bi/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-resolver-o6ysh1bi/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
Traceback (most recent call last):
  File "~/miniconda3/envs/env/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/scripts/compile.py", line 466, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/resolver.py", line 175, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/resolver.py", line 319, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/resolver.py", line 428, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 237, in get_dependencies
    download_dir, ireq, wheel_cache
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 199, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 332, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 481, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 549, in _prepare_linked_requirement
    self.build_isolation,
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 37, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 592, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 578, in _generate_metadata
    details=self.name or f"from {self.link}",
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 63, in generate_metadata
    spinner=spinner,
  File "~/miniconda3/envs/env/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by atugushev** [comment]
Hey @alichaudry!

Requirement "mypy<0.9" is essentially "mypy==0.1", which is pretty old to install (or compile with pip-tools) now. Try `pip install  "mypy<0.9"` and you'll get the same error with `wsgiref`.

**Comment by alichaudry** [comment]
@atugushev thanks for the response! Maybe this issue stems from my lack of understanding of how pip packages work; I (naively) assumed that `"mypy<0.9"` would match with `"mypy==0.812"` as per the `mypy` PyPI listing [here](https://pypi.org/project/mypy/#history). Is that not the case? Why does `"mypy<0.9"` match with `"mypy==0.1"` and nothing in-between 0.1 and 0.9?

**Comment by wbolster** [comment]
i think your misunderstanding is that you treat version numbers as ‘floating point numbers’. that is not what they actually are.

0.9 means `(0, 9)`, and 0.812 means `(0, 812)`. and 821 is a larger number than 9.

**Comment by wbolster** [comment]
closing this for now since i believe this issue is now resolved. (if not, let us know)

**Comment by alichaudry** [comment]
That's helpful, thank you @wbolster and @atugushev. I appreciate your explanation and that clears up my misunderstanding.
