### ISSUE TITLE
FileNotFoundError when used with a package wich bundles sub-packages

### ISSUE THREAD

**Issue by rmillet-rs** [jazzband/pip-tools#1597]
While trying to build a requirements.txt file with vsphere-automation-sdk-python, pip-compile raises a FileNotFoundError.

#### Environment Versions

1. OS Type: Linux / Ubuntu 18.04
1. Python version: `3.7.5`
1. pip version: `22.0.4`
1. pip-tools version: `6.5.1`

#### Steps to replicate

```sh
cat requirements.in
https://github.com/vmware/vsphere-automation-sdk-python/archive/v7.0.3.0.tar.gz
```
or

```sh
cat requirements.in
git+https://github.com/vmware/vsphere-automation-sdk-python.git@v7.0.3.0#egg=vSphere-Automation-SDK
```
```sh
pip-compile requirements.in --output-file requirements.txt
```

#### Expected result

A correct `requirements.txt` is generated. As it works with

```
pip install -r requirements.in
```

#### Actual result

```
Traceback (most recent call last):
  File "/tmp/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/tmp/venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tmp/venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 466, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/tmp/venv/lib/python3.7/site-packages/piptools/resolver.py", line 175, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/tmp/venv/lib/python3.7/site-packages/piptools/resolver.py", line 319, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/tmp/venv/lib/python3.7/site-packages/piptools/resolver.py", line 414, in _iter_dependencies
    yield from self.repository.get_dependencies(ireq)
  File "/tmp/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 239, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/tmp/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 201, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 332, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 560, in _prepare_linked_requirement
    self.build_isolation,
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 59, in _get_prepared_distribution
    return abstract_dist.get_metadata_distribution()
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/distributions/wheel.py", line 26, in get_metadata_distribution
    return get_wheel_distribution(wheel, canonicalize_name(self.req.name))
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/metadata/__init__.py", line 62, in get_wheel_distribution
    return Distribution.from_wheel(wheel, canonical_name)
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/metadata/pkg_resources.py", line 105, in from_wheel
    with wheel.as_zipfile() as zf:
  File "/tmp/venv/lib/python3.7/site-packages/pip/_internal/metadata/base.py", line 537, in as_zipfile
    return zipfile.ZipFile(self.location, allowZip64=True)
  File "/usr/lib/python3.7/zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '//tmp/pip-req-build-2k8ka38g/lib/nsx-python-sdk/nsx_python_sdk-3.1.2.1.1-py2.py3-none-any.whl'
```

**Comment by AndydeCleyre** [comment]
Thanks!

I just want to add for now that I can reproduce this, both in `master` and in my path-related PR, but found that it works well with @atugushev's #1539 when using `--resolver backtracking`.

**Comment by rmillet-rs** [comment]
Hello, thank you for the fast answer.

I tested with #1539, the file is generated, but it contains paths to temporary directories:
```
nsx-policy-python-sdk @ file://localhost//tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
    # via vsphere-automation-sdk
nsx-python-sdk @ file://localhost//tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-python-sdk/nsx_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
    # via vsphere-automation-sdk
nsx-vmc-aws-integration-python-sdk @ file://localhost//tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
    # via vsphere-automation-sdk
nsx-vmc-policy-python-sdk @ file://localhost//tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
    # via vsphere-automation-sdk
```

and that prevent installation with `pip install -r requirements.txt`:
```
Processing //tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '//tmp/pip-resolve-ehumdwah/vsphere-automation-sdk_a3f4013e6ddf4bc2a7c6a2cb49639288/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl
```

I don't known well the requirements.txt format, so I am wondering if it supports referencing files in other packages?

It would have been simpler if VMWare was packaging in a more conventional way.

**Comment by atugushev** [comment]
Considering the unusual `install_requires ` in [setup.py](https://github.com/vmware/vsphere-automation-sdk-python/blob/master/setup.py) I'm not sure how it should work with pip-tools.
```python
install_requires=[
    'lxml >= 4.3.0',
    'pyVmomi >= 6.7',
    'vapi-runtime @ file://localhost/{}/lib/vapi-runtime/vapi_runtime-2.30.0-py2.py3-none-any.whl'.format(os.getcwd()),
    'vapi-client-bindings @ file://localhost/{}/lib/vapi-client-bindings/vapi_client_bindings-3.7.0-py2.py3-none-any.whl'.format(os.getcwd()),
    'vapi-common-client @ file://localhost/{}/lib/vapi-common-client/vapi_common_client-2.30.0-py2.py3-none-any.whl'.format(os.getcwd()),
    'vmc-client-bindings @ file://localhost/{}/lib/vmc-client-bindings/vmc_client_bindings-1.52.0-py2.py3-none-any.whl'.format(os.getcwd()),
    'nsx-python-sdk @ file://localhost/{}/lib/nsx-python-sdk/nsx_python_sdk-3.1.2.1.1-py2.py3-none-any.whl'.format(os.getcwd()),
    'nsx-policy-python-sdk @ file://localhost/{}/lib/nsx-policy-python-sdk/nsx_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl'.format(os.getcwd()),
    'nsx-vmc-policy-python-sdk @ file://localhost/{}/lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-3.1.2.1.1-py2.py3-none-any.whl'.format(os.getcwd()),
    'nsx-vmc-aws-integration-python-sdk @ file://localhost/{}/lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-3.1.2.1.1-py2.py3-none-any.whl'.format(os.getcwd()),
    'vmc-draas-client-bindings @ file://localhost/{}/lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.18.0-py2.py3-none-any.whl'.format(os.getcwd()),
]
```

**Comment by AndydeCleyre** [comment]
Oh wow, yeah I definitely wouldn't hold back the resolver release to manage that dynamic but absolute path URI business.

**Comment by rmillet-rs** [comment]
OK, I completely understand your point.
This lib is so a mess to install, I decided to use other libs.

Thank you for your time, no need to waste more for this unusual case.
