### ISSUE TITLE
Keep arguments on requirements.in

### ISSUE THREAD

**Issue by gforcada** [jazzband/pip-tools#1631]
We bumped from pip-tools version `5.5.0` to `6.6.2` and noticed that parameters set on `requirements.in` are now not parsed/understood 😕 

We had:

```
--extra-index-url=https://my-server.com/pypi/simple

beautifulsoup4
celery[redis]<5
```

And we updated it to

```
--pip-args "--extra-index-url=https://my-server.com/pypi/simple"

beautifulsoup4
celery[redis]<5
```
But it fail every time we tried. `--pip-args` was not recognized, but same happened with any `pip-compile` argument as well 😕 

**Note** that it does work if the argument is passed on the command line itself:

i.e. rather than `pip-compile requirements.in` we do `pip-compile requirements.in --pip-args "--extra-index-url=https://my-server.com/pypi/simple"`

**Thanks** for the `pip-tools` project, we ❤️ it!! 🤩 

#### Environment Versions

1. OS Type: Linux Fedora 35
1. Python version: 3.7.13
1. pip version: 21.2.3
1. pip-tools version: 6.6.2

#### Steps to replicate

1. Create a venv and install pip-tools on it
2. Create a `requirements.in` with some packages and arguments for pip-compile
3. Run `pip-compile requirements.in`

#### Expected result

In our case, that the `--pip-args` option was read and passed to pip so our custom packages on our extra index URL would be installed.

#### Actual result

This traceback:
```
Usage: pip-compile [options]

Traceback (most recent call last):
  File "/usr/lib64/python3.7/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python3.7/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python3.7/optparse.py", line 1480, in _process_long_opt
    opt = self._match_long_opt(opt)
  File "/usr/lib64/python3.7/optparse.py", line 1465, in _match_long_opt
    return _match_abbrev(opt, self._long_opt)
  File "/usr/lib64/python3.7/optparse.py", line 1670, in _match_abbrev
    raise BadOptionError(s)
optparse.BadOptionError: no such option: --pip-args

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 359, in _parse_file
    args_str, opts = self._line_parser(line)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 386, in parse_line
    opts, _ = parser.parse_args(shlex.split(options_str), defaults)
  File "/usr/lib64/python3.7/optparse.py", line 1389, in parse_args
    self.error(str(err))
  File "/usr/lib64/python3.7/optparse.py", line 1569, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 429, in parser_exit
    raise OptionParsingError(msg)
pip._internal.req.req_file.OptionParsingError: pip-compile: error: no such option: --pip-args


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gil/project//venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/gil/project//venv/lib64/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/piptools/scripts/compile.py", line 422, in cli
    options=repository.options,
  File "/home/gil/project//venv/lib64/python3.7/site-packages/piptools/_compat/pip_compat.py", line 30, in parse_requirements
    filename, session, finder=finder, options=options, constraint=constraint
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 135, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 319, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 324, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/home/gil/project//venv/lib64/python3.7/site-packages/pip/_internal/req/req_file.py", line 363, in _parse_file
    raise RequirementsFileParseError(msg)
pip._internal.exceptions.RequirementsFileParseError: Invalid requirement: --pip-args "--extra-index-url=https://my-server.com/pypi/simple"
pip-compile: error: no such option: --pip-args
```

**Comment by AndydeCleyre** [comment]
The requirements files don't support `--pip-args` within, but we *should* continue to support the syntax as you had it initially, and as is described at https://pip.pypa.io/en/latest/reference/requirements-file-format/

**Comment by AndydeCleyre** [comment]
Trying your example input (the "We had:" one) still seems to work here, both in master and `6.6.2`.

Can you show the output you get with that first input example you provide?

**Comment by AndydeCleyre** [comment]
@gforcada 

Are still able to reproduce this issue?

**Comment by gforcada** [comment]
@AndydeCleyre no, seems that somehow the error is no longer there, thanks for double checking and taking the time to look at my report 🙇🏾 ✨
