### ISSUE TITLE
pip-compile BAR_TYPES error

### ISSUE THREAD

**Issue by pythonmobile** [jazzband/pip-tools#1651]
Related to : https://github.com/jazzband/pip-tools/issues/1617

```
pip-compile --allow-unsafe --output-file=./setup/my_requirements.txt ./setup/requirements.in
Traceback (most recent call last):
  File "/home/uname/.local/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 23, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/home/uname/.local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py)
```
#### Environment Versions

1. OS Type
Distributor ID: Ubuntu
Description:  Ubuntu 20.04.4 LTS
Release:  20.04
Codename: focal

1. Python version: `$ python -V`

Python 3.10.5

1. pip version: `$ pip --version`

pip 22.1.2 from /home/uname/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip (python 3.10)

1. pip-tools version: `$ pip-compile --version`
```
pip-compile --version
Traceback (most recent call last):
  File "/home/uname/.local/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 23, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/home/uname/.local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py)
```

#### Steps to replicate

1. Just install pip-tools and run pip-compile --version

#### Expected result

version number

#### Actual result

Pasted above.

**Comment by atugushev** [comment]
Could you show `python -m pip-tool compile --version`?

**Comment by pythonmobile** [comment]
@atugushev Thanks. python -m pip install -U pip-tools -- this was already updated and on the latest version. Said already-satisfied for everything. 

```
$ python -m piptools compile --version
python -m piptools, version 6.8.0
```
```
$ python3 -m pip show pip-tools
Name: pip-tools
Version: 6.8.0
Summary: pip-tools keeps your pinned dependencies fresh.
Home-page: https://github.com/jazzband/pip-tools/
Author: Vincent Driessen
Author-email: me@nvie.com
License: BSD 3 Clause
Location: /home/piyush/.pyenv/versions/3.10.5/lib/python3.10/site-packages
Requires: build, click, pip, setuptools, wheel
Required-by:
```

**Comment by atugushev** [comment]
You probably run old pip-compile from different venv. Note `/home/uname/.local/lib/ -->> python3.8 <<-- /site-packages/piptools/` in the traceback:
```
pip-compile --version
Traceback (most recent call last):
....
  File "/home/uname/.local/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 23, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/home/uname/.local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py)
```


and note correct location of pip-tools==6.8.0:
```
Location: /home/piyush/.pyenv/versions/ -->> 3.10.5 <<-- /lib/python3.10/site-packages
```

Try to compile using `python -m piptools compile`.

**Comment by pythonmobile** [comment]
@atugushev Thanks! Indeed that solved the issue. Perhaps the environment was running something random.
