### ISSUE TITLE
pip-sync errors when merging multiple requirements.txt files that point at the same editable install

### ISSUE THREAD

**Issue by vivster7** [jazzband/pip-tools#1710]
pip-sync raises an `AttributeError: 'NoneType' object has no attribute 'specifier'` error when you try and run it with multiple requirements files that each include an editable install for the same package.

#### Environment Versions

1. OS Type: Linux
1. Python version: Python 3.9.11
1. pip version: pip 22.3
1. pip-tools version: pip-compile, version 6.9.0

#### Steps to replicate
1. Create a setup.py, dev_requirements.in, requirements.in file
```
# setup.py
from setuptools import find_packages, setup
setup(name="a", version="0.0.1", packages=find_packages())

# dev_requirements.in
-e file:.

# requirements.in
-e file:.
```
2. Run pip-compile
```
pip-compile requirements.in
pip-compile dev_requirements.in
```
3. Run pip-sync
```
pip-sync requirements.in  dev_requirements.in
```

#### Expected result
I expected the editable package to install once. Similar to running `pip install -r requirements.txt -r dev_requirements.txt`

#### Actual result
`pip-sync` raised an error
Full stack trace
```
➜  scratch pip-sync  requirements.txt dev_requirements.txt 
Traceback (most recent call last):
  File "/home/vivek/.pyenv/versions/3.9.11/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/piptools/scripts/sync.py", line 146, in cli
    merged_requirements = sync.merge(requirements, ignore_conflicts=force)
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/piptools/sync.py", line 115, in merge
    if ireq.specifier != existing_ireq.specifier:
  File "/home/vivek/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 245, in specifier
    return self.req.specifier
AttributeError: 'NoneType' object has no attribute 'specifier'
```

...

**Comment by atugushev** [comment]
Alas, can't reproduce the bug. Could you show the `pip --version` output? This does look like you're using some old pip version.

**Comment by vivster7** [comment]
```
➜  /src git:(main) pip --version
pip 22.3 from /home/vivek/.pyenv/versions/3.9.11/envs/chrono/lib/python3.9/site-packages/pip (python 3.9)
```

Would it help if I pushed a Docker image with the repro in it?

**Comment by richafrank** [comment]
(Added tests and fix in [PR](https://github.com/jazzband/pip-tools/pull/1802))
