### ISSUE TITLE
--pip-args not passed to pip installing setuptools

### ISSUE THREAD

**Issue by neaxi** [jazzband/pip-tools#1781]
I have to use custom/private pypi index as our network setup blocks access to https://pypi.org. Passing `--pip-args="--index_url https://pypi.private.url"` (aka `pip -i`) is not applied when `setuptools` and `wheel` are being installed. The issue is also visible with other args like `--timeout 1`, etc...

As this seems to be an issue out of scope of `pip-tools` I'm not sure it can be fixed/handled. I wanted to provide a writeup with observed behavior and workarounds I've tested for devs facing the same issues in future, because I've failed to find a simple answer/solution when searching through issues myself.

#### Environment Versions

1. OS Type: Windows 10.0.19044
2. Python version: `$ python -V`: Python 3.10.6
3. pip version: `$ pip --version`: pip 22.3.1
4. pip-tools version: `$ pip-compile --version`: pip-compile, version 6.12.0

#### Steps to replicate

1. create `venv`
2. update `pip`, install `piptools`
3. create `pyproject.toml`. nothing fancy, barebones setup

  ```toml
  # pyproject.toml

  [project]
  name = "modulename"
  version = "1.0.0"

  dependencies = []
  requires-python = ">=3.8"

  [build-system]
  requires      = ["setuptools>=61.0.0", "wheel"]
  build-backend = "setuptools.build_meta"
  ```

4. try to compile `pyproject.toml`:  
`pip-compile --verbose pyproject.toml --resolver=backtracking --pip-args="-i https://pypi.private.url'`

My findings so far

1. `click` loads `--pip-args` succcessfuly -> no issues with CLI parsing
2. the variable `pip_args` is available until `piptools\scripts\compile.py", line 483, metadata = project_wheel_metadata()`
3. It seems the `-i` is not passed to `\build\util.py", line 53, project_wheel_metadata()` in any way and there is no interface to make it happen.
4. and that's why `build\env.py", line 211, in install; _subprocess(cmd)` executes without `-i` and fails

#### Expected result

Successful result obtained via [Workaround](###workaround)

```
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools>=61.0.0, wheel)
Getting build dependencies for wheel...
Installing packages in isolated environment... (wheel)
Getting metadata for wheel...
Using indexes:
  https://pypi.private.url
  Looking in indexes: https://pypi.private.url
```

#### Actual result

`subprocess` executes `pip` without `-i`, tries to reach `pypi.org` despite `--pip-args="-i https://pypi.private.url"` and obviously fails. 

<details>
<summary>
output + traceback:
</summary>

```
Creating venv isolated environment...
Installing packages in isolated environment... (setuptools>=61.0.0, wheel)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/setuptools/
...

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\pip-compile.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Python38\lib\site-packages\piptools\scripts\compile.py", line 483, in cli
    metadata = project_wheel_metadata(
  File "C:\Python38\lib\site-packages\build\util.py", line 53, in project_wheel_metadata
    env.install(builder.build_system_requires)
  File "C:\Python38\lib\site-packages\build\env.py", line 211, in install
    _subprocess(cmd)
  File "C:\Python38\lib\site-packages\build\env.py", line 76, in _subprocess
    raise e
  File "C:\Python38\lib\site-packages\build\env.py", line 73, in _subprocess
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Python38\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\USERNAME\\AppData\\Local\\Temp\\build-env-nltqvjdv\\Scripts\\python.exe', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', 'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\build-reqs-wthveb8h.txt']' returned non-zero exit status 1.
```

</details>

### Workarounds

1. Use `PIP_INDEX_URL` environment variable

2. Force system global pip index in:  
Win: `%HOME%/pip/pip.ini`  
nix: `$HOME/.config/pip/pip.conf`

  ```ini
  [global]
  index_url = https://pypi.private.url

  [search]
  index_url = https://pypi.private.url
  ```

**Comment by iggyfisk** [comment]
Experiencing the same problem when trying to use a constraints file with pip-compile requirements.in --upgrade --resolver=backtracking --pip-args "-c constraints.txt".

My workaround has been (temporarily) adding `-c constraints.txt` to `requirements.in`

**Comment by atugushev** [comment]
Actually pip [passes some options](https://github.com/pypa/pip/blob/5ee7caf92ae6135b8ae8fdad4cd2cc28d5f81b8a/src/pip/_internal/build_env.py#L187-L202) to the isolated build environments, but pip-tool [does not](https://github.com/jazzband/pip-tools/blob/0c1ddcc6466c255675fa8b4f3db7d68f8808a74d/piptools/scripts/compile.py#L493-L496) (except `--build-isolation`). At first glance pip-tools could monkeypatch pip option environments (e.g., `PIP_INDEX_URL`) before calling `build.utils.project_wheel_metadata()` to fix the issue.

Setting `PIP_INDEX_URL` should definitely help. As another workaround, you could disable build isolation via `pip-compile --no-build-isolation` and manage the build environment manually.

**Comment by chrysle** [comment]
@atugushev Maybe we could introduce an own `--index-url` CLI option? 

That would simplify things.

**Comment by atugushev** [comment]
> Maybe we could introduce an own `--index-url` CLI option?

@chrysle `pip-compile` already has `--index-url` option:

```
$ pip-compile --help | grep -A1 -- --index-url
  -i, --index-url TEXT            Change index URL (defaults to
                                  https://pypi.org/simple)
```

However, the main issue is figuring out how to pass the index URL properly to `build.utils.project_wheel_metadata()`.

**Comment by chrysle** [comment]
> However, the main issue is figuring out how to pass the index URL properly to [build.utils.project_wheel_metadata()](https://github.com/jazzband/pip-tools/blob/4b9cc327f1352b94ba763a9dafe17c1a0fd1dc60/piptools/scripts/compile.py#L536-L539).

Wasn't there the golden rule that if StackOverflow [doesn't know the answer](https://stackoverflow.com/questions/72190089/extra-index-url-in-wheel-metadata), it's impossible? I think we should really set `PIP_INDEX_URL` then.

If you passed `--index-url` directly, but not via pip args, should that be used for the wheel metadata?

**Comment by liiight** [comment]
I think I have an issue in this domain as well. 
When I add `neo4j` to my requirements.in and run `pip-compile` i get the following error:

```
Collecting neo4j (from -r requirements.in (line 30))
    Using cached neo4j-5.10.0.tar.gz (187 kB)
    Preparing metadata (pyproject.toml) ... error
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [13 lines of output]
        Traceback (most recent call last):
          File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/opt/pipx/shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/opt/pipx/shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 29, in <module>
        ModuleNotFoundError: No module named 'tomlkit'
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 718, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/piptools/scripts/compile.py", line 630, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
  File "/opt/pipx/venvs/pip-tools/lib/python3.9/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 653, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 562, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/opt/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
```

This is because neo4j apparently uses tomlkit in its build system: https://github.com/neo4j/neo4j-python-driver/blob/5.0/pyproject.toml#L57

I already run using no-isolated-build it still fails. 
If I run `pip wheel neo4j` it download the build dependencies and after that pip-compile works.

If this is unrelated then I apologize, I'll open a new issue.

**Comment by atugushev** [comment]
@liiight in your case the issue is [here](https://github.com/neo4j/neo4j-python-driver/blob/4a975afb07865fc113111caa860d075d04567298/setup.py#L29). `toolkit` is used during build time in `setup.py` before it has been installed.
