### ISSUE TITLE
Running tox fails due to 'ModuleNotFoundError: No module named 'tox.venv''

### ISSUE THREAD

**Issue by Jagdish1287** [jazzband/pip-tools#1800]
#### Environment Versions

1. OS Type - RHEL9.0
1. Python version: `$ python -V` Python 3.9.10
1. pip version: `$ pip --version`  pip 22.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
1. pip-tools version: `$ pip-compile --version`

#### Steps to replicate

1. pip install tox
2. pip install tox.venv
3. Run tox command

[root@abc ~]# tox
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /root
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/usr/local/lib/python3.9/site-packages/tox/run.py", line 38, in main
    state = setup_state(args)
  File "/usr/local/lib/python3.9/site-packages/tox/run.py", line 53, in setup_state
    options = get_options(*args)
  File "/usr/local/lib/python3.9/site-packages/tox/config/cli/parse.py", line 38, in get_options
    guess_verbosity, log_handler, source = _get_base(args)
  File "/usr/local/lib/python3.9/site-packages/tox/config/cli/parse.py", line 61, in _get_base
    MANAGER.load_plugins(source.path)
  File "/usr/local/lib/python3.9/site-packages/tox/plugin/manager.py", line 90, in load_plugins
    self._register_plugins(inline)
  File "/usr/local/lib/python3.9/site-packages/tox/plugin/manager.py", line 38, in _register_plugins
    self.manager.load_setuptools_entrypoints(NAME)
  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/tox_pip_version/hooks.py", line 4, in <module>
    import tox.venv
ModuleNotFoundError: No module named 'tox.venv'

#### Expected result

Tox command should work

#### Actual result

...

**Comment by AndydeCleyre** [comment]
It doesn't look like pip-tools is being used here.

**Comment by webknjaz** [comment]
I've never heard of `pip install tox.venv`. Also, the issue doesn't mention anything related to this project.
