### ISSUE TITLE
Cannot install Django-rq-scheduler with pip-tools

### ISSUE THREAD

**Issue by mjmare** [jazzband/pip-tools#1852]
I manage my requirements with pip-tools. I do a pip-compile on my requirements.in to create a requirements.txt, then a pip-sync to update the env. Works fine, usually. 

Now I added django-rq-scheduler to the reqs and I get a weird error:
```
❯ pip-compile
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/scripts/compile.py", line 580, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/resolver.py", line 253, in resolve
    has_changed, best_matches = self._resolve_one_round()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/resolver.py", line 343, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/resolver.py", line 456, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/repositories/local.py", line 87, in get_dependencies
    return self.repository.get_dependencies(ireq)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mjm/Dropbox/Devel/ACHN/Vraagbaak/venv/lib/python3.11/site-packages/piptools/repositories/pypi.py", line 237, in get_dependencies
    wheel_cache = WheelCache(self._cache_dir, self.options.format_control)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WheelCache.__init__() takes 2 positional arguments but 3 were given
```
I tried fixing the version, but no effect. 

Doing just a plain ```pip install Django-rq-scheduler``` in the same venv (with all other dependencies pip-tools installed) works normally. 

Initially I created an [issue](https://github.com/dsoftwareinc/django-rq-scheduler/issues/124) in the Django-rq-schduler repo, but the author did not think it was django-rq-scheduler, except for possibly it being caused by Poetry packaging?

**Comment by atugushev** [comment]
Update pip-tools to `6.13.0` version.
