### ISSUE TITLE
UserWarning: Setuptools is replacing distutils

### ISSUE THREAD

**Issue by tekumara** [jazzband/pip-tools#1857]
#### Environment Versions

1. OS Type: macos
1. Python version: python 3.9.16
1. pip version: 22.3.1
1. pip-tools version: 6.13.0

#### Steps to replicate

Run any pip-compile command.

#### Expected result

No warning

#### Actual result

```
❯ pip-compile --version
/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
pip-compile, version 6.13.0
```

**Comment by webknjaz** [comment]
pip-tools can't do anything about that, report to the said project instead..

**Comment by gwerbin** [comment]
For anyone else encountering this, you should not see it in a clean venv with only `pip-tools` installed. It's caused by one of your other packages still using Distutils in some way.

I spent a little while trying to "bisect" my dependency list to figure out where it came from, but I didn't find the culprit. It seems to happen in almost every nontrivial Python project where I've used pip-tools, so it's likely to be some common lower-level package that a lot of other things depend on.

In any case, you can silence it by setting the env var `PYTHONWARNINGS='ignore:Setuptools is replacing distutils:UserWarning:_distutils_hack'`.

Unfortunately setting `PYTHONWARNINGS='error'` didn't seem to help isolate the source:

```bash
PYTHONWARNINGS='error' ./venv/bin/pip-compile --version

Traceback (most recent call last):
  File "/Users/.../.venv/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/Users/.../.venv/lib/python3.10/site-packages/piptools/scripts/compile.py", line 15, in <module>
    from pip._internal.commands import create_command
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/Users/.../.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 97, in find_spec
    return method()
  File "/Users/.../.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 147, in spec_for_pip
    clear_distutils()
  File "/Users/.../.venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 33, in clear_distutils
    warnings.warn("Setuptools is replacing distutils.")
UserWarning: Setuptools is replacing distutils.
```
