### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'package_name'

### ISSUE THREAD

**Issue by raj-trustlab** [jazzband/pip-tools#1908]
Here is what I see when running pip-compile:
```
$ pip-compile requirements.txt -o requirements_lock.txt --allow-unsafe
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/usr/local/lib/python3.8/dist-packages/piptools/scripts/compile.py", line 305, in <module>
    def cli(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 282, in decorator
    return option(*(param_decls or ('--version',)), **attrs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

#### Environment Versions

1. OS Type - Ubuntu 20.04.1
1. Python version: `3.8.10`
1. pip version: `pip 23.1.2 from /home/ubuntu/.venv/lib/python3.8/site-packages/pip (python 3.8)`
1. pip-tools version: Doesn't work, I get:
```
$ pip-compile --version
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/usr/local/lib/python3.8/dist-packages/piptools/scripts/compile.py", line 305, in <module>
    def cli(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 282, in decorator
    return option(*(param_decls or ('--version',)), **attrs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```
#### Steps to replicate

Type in "pip-compile" and this always shows up.

#### Expected result

Actually running pip-compile

#### Actual result

```
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/usr/local/lib/python3.8/dist-packages/piptools/scripts/compile.py", line 305, in <module>
    def cli(
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 282, in decorator
    return option(*(param_decls or ('--version',)), **attrs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

**Comment by atugushev** [comment]
Does `pip install --upgrade click` help?

**Comment by atugushev** [comment]
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!
