### ISSUE TITLE
Incompatible with pip 23.2: ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze'

### ISSUE THREAD

**Issue by hofrob** [jazzband/pip-tools#1916]
#### Environment Versions

1. Ubuntu 22.04 LTS
1. Python version: Python 3.11.4
1. pip version: pip 23.2
1. pip-tools version: pip-compile, version 6.14.0

#### Steps to replicate

1. pip-sync --version

#### Expected result

Show version number just like `pip-compile --version`.

#### Actual result

```
Traceback (most recent call last):
  File "/path/to/project/venv/bin/pip-sync", line 5, in <module>
    from piptools.scripts.sync import cli
  File "/path/to/project/venv/lib/python3.11/site-packages/piptools/scripts/sync.py", line 17, in <module>
    from .. import sync
  File "/path/to/project/venv/lib/python3.11/site-packages/piptools/sync.py", line 11, in <module>
    from pip._internal.commands.freeze import DEV_PKGS
ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze' (/path/to/project/venv/lib/python3.11/site-packages/pip/_internal/commands/freeze.py)
```

**Comment by webknjaz** [comment]
This has been fixed in the recent release.

**Comment by hofrob** [comment]
Sorry, for some reason I thought I was on the latest release.

Thanks!
