### ISSUE TITLE
pip-compile -U crashed

### ISSUE THREAD

**Issue by tonal** [jazzband/pip-tools#1924]
#### Environment Versions

1. KDE Neon 5.27  (ubuntu 22.04 with all updates)
1. Python 3.11.4
1. pip 23.2
1. pip-compile, version 7.1.0

#### Steps to replicate

1. Create new venv and install latest pip-tools
2. <details>
    <summary>requirements.txt</summary>

    ```
    #
    # This file is autogenerated by pip-compile with Python 3.11
    # by the following command:
    #
    #    pip-compile
    #
    aiohttp==3.8.4
        # via
        #   aiohttp-cors
        #   ray
    aiohttp-cors==0.7.0
        # via ray
    aiosignal==1.3.1
        # via
        #   aiohttp
        #   ray
    aiosqlite==0.19.0
        # via prefect
    alembic==1.11.1
        # via prefect
    anyio==3.7.1
        # via
        #   httpcore
        #   prefect
        #   starlette
    apprise==1.4.5
        # via prefect
    asgi-lifespan==2.1.0
        # via prefect
    async-timeout==4.0.2
        # via aiohttp
    asyncpg==0.28.0
        # via prefect
    attrs==23.1.0
        # via
        #   aiohttp
        #   automat
        #   jsonschema
        #   ray
        #   referencing
        #   service-identity
        #   twisted
    automat==22.10.0
        # via twisted
    blessed==1.20.0
        # via gpustat
    boto3==1.28.3
        # via
        #   -r requirements.in
        #   prefect-aws
    botocore==1.31.3
        # via
        #   boto3
        #   prefect-aws
        #   s3transfer
    brotli==1.0.9
        # via httpx
    cachetools==5.3.1
        # via google-auth
    certifi==2023.5.7
        # via
        #   apprise
        #   httpcore
        #   httpx
        #   kubernetes
        #   requests
        #   sentry-sdk
    cffi==1.15.1
        # via cryptography
    charset-normalizer==3.2.0
        # via
        #   aiohttp
        #   requests
    click==8.1.5
        # via
        #   -r requirements.in
        #   apprise
        #   prefect
        #   ray
        #   typer
        #   uvicorn
    cloudpickle==2.2.1
        # via prefect
    colorama==0.4.6
        # via griffe
    colorful==0.5.5
        # via ray
    constantly==15.1.0
        # via twisted
    coolname==2.2.0
        # via prefect
    croniter==1.4.1
        # via prefect
    cryptography==41.0.2
        # via
        #   prefect
        #   pyopenssl
        #   scrapy
        #   service-identity
    cssselect==1.2.0
        # via
        #   parsel
        #   scrapy
    dateparser==1.1.8
        # via prefect
    distlib==0.3.6
        # via virtualenv
    dnspython==2.4.0
        # via
        #   email-validator
        #   pymongo
    docker==6.1.3
        # via prefect
    email-validator==2.0.0.post2
        # via pydantic
    et-xmlfile==1.1.0
        # via openpyxl
    fastapi==0.100.0
        # via prefect
    filelock==3.12.2
        # via
        #   ray
        #   tldextract
        #   virtualenv
    frozenlist==1.4.0
        # via
        #   aiohttp
        #   aiosignal
        #   ray
    fsspec==2023.6.0
        # via prefect
    geojson-pydantic==0.6.3
        # via -r requirements.in
    google-api-core==2.11.1
        # via opencensus
    google-auth==2.22.0
        # via
        #   google-api-core
        #   kubernetes
    googleapis-common-protos==1.59.1
        # via google-api-core
    gpustat==1.1
        # via ray
    greenlet==2.0.2
        # via sqlalchemy
    griffe==0.32.2
        # via prefect
    grpcio==1.51.3
        # via ray
    h11==0.14.0
        # via
        #   httpcore
        #   uvicorn
    h2==4.1.0
        # via httpx
    hpack==4.0.0
        # via h2
    httpcore==0.17.3
        # via
        #   dnspython
        #   httpx
    httpx[brotli,http2]==0.24.1
        # via
        #   -r requirements.in
        #   prefect
    hyperframe==6.0.1
        # via h2
    hyperlink==21.0.0
        # via twisted
    idna==3.4
        # via
        #   anyio
        #   email-validator
        #   httpx
        #   hyperlink
        #   requests
        #   tldextract
        #   yarl
    incremental==22.10.0
        # via twisted
    itemadapter==0.8.0
        # via
        #   itemloaders
        #   scrapy
    itemloaders==1.1.0
        # via scrapy
    jinja2==3.1.2
        # via prefect
    jmespath==1.0.1
        # via
        #   boto3
        #   botocore
        #   itemloaders
        #   parsel
    jsonpatch==1.33
        # via prefect
    jsonpointer==2.4
        # via jsonpatch
    jsonschema==4.18.3
        # via
        #   prefect
        #   ray
    jsonschema-specifications==2023.6.1
        # via jsonschema
    kubernetes==26.1.0
        # via prefect
    lxml==4.9.3
        # via
        #   parsel
        #   scrapy
    mako==1.2.4
        # via alembic
    markdown==3.4.3
        # via apprise
    markdown-it-py==3.0.0
        # via rich
    markupsafe==2.1.3
        # via
        #   jinja2
        #   mako
    mdurl==0.1.2
        # via markdown-it-py
    more-itertools==9.1.0
        # via -r requirements.in
    msgpack==1.0.5
        # via ray
    multidict==6.0.4
        # via
        #   aiohttp
        #   yarl
    mypy-boto3-s3==1.28.3.post2
        # via prefect-aws
    mypy-boto3-secretsmanager==1.28.3.post2
        # via prefect-aws
    mysqlclient==2.2.0
        # via -r requirements.in
    numpy==1.25.1
        # via
        #   -r requirements.in
        #   ray
        #   shapely
    nvidia-ml-py==12.535.77
        # via gpustat
    oauthlib==3.2.2
        # via requests-oauthlib
    opencensus==0.11.2
        # via ray
    opencensus-context==0.1.3
        # via opencensus
    openpyxl==3.1.2
        # via -r requirements.in
    orjson==3.9.2
        # via prefect
    packaging==23.1
        # via
        #   docker
        #   parsel
        #   prefect
        #   ray
        #   scrapy
    parsel==1.8.1
        # via
        #   itemloaders
        #   scrapy
    pathspec==0.11.1
        # via prefect
    pendulum==2.1.2
        # via prefect
    platformdirs==3.9.1
        # via virtualenv
    prefect==2.10.21
        # via
        #   -r requirements.in
        #   prefect-aws
        #   prefect-ray
    prefect-aws==0.3.5
        # via -r requirements.in
    prefect-ray==0.2.5
        # via -r requirements.in
    prometheus-client==0.17.1
        # via ray
    protego==0.2.1
        # via scrapy
    protobuf==4.23.4
        # via
        #   google-api-core
        #   googleapis-common-protos
        #   ray
    psutil==5.9.5
        # via gpustat
    py-spy==0.3.14
        # via ray
    pyasn1==0.5.0
        # via
        #   pyasn1-modules
        #   rsa
        #   service-identity
    pyasn1-modules==0.3.0
        # via
        #   google-auth
        #   service-identity
    pycparser==2.21
        # via cffi
    pydantic[dotenv,email]==1.10.11
        # via
        #   -r requirements.in
        #   fastapi
        #   geojson-pydantic
        #   prefect
        #   ray
    pydispatcher==2.0.7
        # via scrapy
    pygments==2.15.1
        # via rich
    pymongo[snappy,srv,zstd]==4.4.1
        # via -r requirements.in
    pyopenssl==23.2.0
        # via scrapy
    python-dateutil==2.8.2
        # via
        #   -r requirements.in
        #   botocore
        #   croniter
        #   dateparser
        #   kubernetes
        #   pendulum
    python-dotenv==1.0.0
        # via pydantic
    python-slugify==8.0.1
        # via prefect
    python-snappy==0.6.1
        # via pymongo
    pytz==2023.3
        # via
        #   dateparser
        #   prefect
    pytzdata==2020.1
        # via pendulum
    pyyaml==6.0
        # via
        #   -r requirements.in
        #   apprise
        #   kubernetes
        #   prefect
        #   ray
    queuelib==1.6.2
        # via scrapy
    ray[default]==2.5.1
        # via -r requirements.in
    readchar==4.0.5
        # via prefect
    referencing==0.29.1
        # via
        #   jsonschema
        #   jsonschema-specifications
    regex==2023.6.3
        # via dateparser
    requests==2.31.0
        # via
        #   apprise
        #   docker
        #   google-api-core
        #   kubernetes
        #   ray
        #   requests-file
        #   requests-oauthlib
        #   tldextract
    requests-file==1.5.1
        # via tldextract
    requests-oauthlib==1.3.1
        # via
        #   apprise
        #   kubernetes
    rich==13.4.2
        # via prefect
    rpds-py==0.8.10
        # via
        #   jsonschema
        #   referencing
    rsa==4.9
        # via google-auth
    ruamel-yaml==0.17.32
        # via prefect
    ruamel-yaml-clib==0.2.7
        # via ruamel-yaml
    s3transfer==0.6.1
        # via boto3
    scrapy==2.9.0
        # via -r requirements.in
    sentry-sdk==1.28.1
        # via -r requirements.in
    service-identity==23.1.0
        # via scrapy
    shapely==2.0.1
        # via tzwhere
    six==1.16.0
        # via
        #   automat
        #   blessed
        #   google-auth
        #   kubernetes
        #   protego
        #   python-dateutil
        #   requests-file
    smart-open==6.3.0
        # via ray
    sniffio==1.3.0
        # via
        #   anyio
        #   asgi-lifespan
        #   dnspython
        #   httpcore
        #   httpx
    sqlalchemy[asyncio]==2.0.19
        # via
        #   alembic
        #   prefect
    starlette==0.27.0
        # via fastapi
    text-unidecode==1.3
        # via python-slugify
    tldextract==3.4.4
        # via scrapy
    toml==0.10.2
        # via prefect
    twisted==22.10.0
        # via scrapy
    typer==0.9.0
        # via prefect
    typing-extensions==4.7.1
        # via
        #   alembic
        #   fastapi
        #   prefect
        #   pydantic
        #   sqlalchemy
        #   twisted
        #   typer
    tzlocal==5.0.1
        # via dateparser
    tzwhere @ git+https://github.com/pegler/pytzwhere.git
        # via -r requirements.in
    urllib3==1.26.16
        # via
        #   botocore
        #   docker
        #   google-auth
        #   kubernetes
        #   requests
        #   sentry-sdk
    uvicorn==0.23.0
        # via prefect
    virtualenv==20.21.0
        # via ray
    w3lib==2.1.1
        # via
        #   itemloaders
        #   parsel
        #   scrapy
    wcwidth==0.2.6
        # via blessed
    websocket-client==1.6.1
        # via
        #   docker
        #   kubernetes
    websockets==11.0.3
        # via prefect
    yarl==1.9.2
        # via aiohttp
    zope-interface==6.0
        # via
        #   scrapy
        #   twisted
    zstandard==0.21.0
        # via pymongo
    
    # The following packages are considered to be unsafe in a requirements file:
    # setuptools
    ```
    </details>
1. `$pip install --no-deps -r requirements.txt`
1. requirements.in:
    ```
    # -*- coding: utf-8 -*-

    boto3
    click
    geojson-pydantic
    httpx[brotli]
    more-itertools
    mysqlclient
    numpy
    openpyxl
    prefect
    prefect-aws
    prefect-ray
    # pydantic[dotenv, email]<2
    pydantic
    pydantic-settings
    pymongo[srv, snappy, zstd]
    python-dateutil
    PyYAML
    ray[default]
    scrapy
    sentry-sdk
    ```
3. `$ pip-compile -U`

#### Expected result

regen requirements.txt

#### Actual result

```
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [68 lines of output]
        /tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 271, in <module>
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-ynxxgyfv/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/home/tonal/.pyenv/versions/epool-pip-tools-err/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/piptools/scripts/compile.py", line 630, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
                  ^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 529, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 644, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 697, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
 /bin/sh /tmp/mc-tonal/mcusr0EVD81
```

**Comment by atugushev** [comment]
This looks like related to https://github.com/yaml/pyyaml/issues/601, not pip-tools.

**Comment by tonal** [comment]
Real conflict - **pydantic**.
If comment line with **pydantic** **pydantic-settings** and uncomment **pydantic[dotenv, email]<2** all work.

**Comment by atugushev** [comment]
From what I understand, there isn't much that pip-tools can do, given that the issue arises from overly restrictive dependencies.

**Comment by webknjaz** [comment]
Maybe hide the traceback in non-verbose Mode and have a human-oriented explanation?

**Comment by tonal** [comment]
Pip, in cases like this, shows restrictions that prevent the package from being installed.
In this case, for example:
```
$ pip install -U pydantic
Requirement already satisfied: pydantic in /home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages (1.10.11)
Collecting pydantic
  Obtaining dependency information for pydantic from https://files.pythonhosted.org/packages/1f/1a/71b404f9acb44402f5b581ade106e9219d6d83824d50943e630fc0ca12e5/pydantic-2.0.3-py3-none-any.whl.metadata
  Using cached pydantic-2.0.3-py3-none-any.whl.metadata (128 kB)
Collecting annotated-types>=0.4.0 (from pydantic)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/d8/f0/a2ee543a96cc624c35a9086f39b1ed2aa403c6d355dfe47a11ee5c64a164/annotated_types-0.5.0-py3-none-any.whl.metadata
  Using cached annotated_types-0.5.0-py3-none-any.whl.metadata (11 kB)
Collecting pydantic-core==2.3.0 (from pydantic)
  Obtaining dependency information for pydantic-core==2.3.0 from https://files.pythonhosted.org/packages/8e/f7/dfe0c5d3337dbcc21f1ad14fa5271357b21a4654a1209ca6822024b84fc1/pydantic_core-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached pydantic_core-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/tonal/.pyenv/versions/3.11.4/envs/epool-pip-tools-err/lib/python3.11/site-packages (from pydantic) (4.7.1)
Using cached pydantic-2.0.3-py3-none-any.whl (364 kB)
Using cached pydantic_core-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
Using cached annotated_types-0.5.0-py3-none-any.whl (11 kB)
Installing collected packages: pydantic-core, annotated-types, pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.11
    Uninstalling pydantic-1.10.11:
      Successfully uninstalled pydantic-1.10.11
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
geojson-pydantic 0.6.3 requires pydantic~=1.0, but you have pydantic 2.0.3 which is incompatible.
prefect 2.10.21 requires pydantic<2.0.0,>=1.10.0, but you have pydantic 2.0.3 which is incompatible.
Successfully installed annotated-types-0.5.0 pydantic-2.0.3 pydantic-core-2.3.0
```

**Comment by atugushev** [comment]
@tonal it allows installation, but warns about incompatibilities. Also,  `pip install -r requirements.in` (same as `pip-compile -U`) would result in a "resolution impossible" error.

**Comment by atugushev** [comment]
> Maybe hide the traceback in non-verbose Mode and have a human-oriented explanation?

@webknjaz sounds good. Opened an issue https://github.com/jazzband/pip-tools/issues/1929.
