### ISSUE TITLE
pip-compile cant take a directory.

### ISSUE THREAD

**Issue by SanketDG** [jazzband/pip-tools#207]
When I input `pip-compile` with a directory,

``` shell
❯ pip-compile requirements 
Traceback (most recent call last):
  File "/home/sanket/.virtualenvs/djangohub/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 73, in cli
    for line in parse_requirements(src_file, finder=repository.finder, session=repository.session):
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/pip/req/req_file.py", line 75, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/home/sanket/.virtualenvs/djangohub/local/lib/python2.7/site-packages/pip/download.py", line 416, in get_file_content
    'Could not open requirements file: %s' % str(exc)
pip.exceptions.InstallationError: Could not open requirements file: [Errno 21] Is a directory: 'requirements'
```

It would be great if `pip-compile` would find all the *.in files and compile them when a directory is given as a parameter.

**Comment by tysonclugg** [comment]
I'm not sure of the use case for this over compiling from a master requirements.in specified like this:
```
-r requirements/foo.in
-r requirements/bar.in
```

Given the lack of activity for nearly 3 years, and the suggested alternative, I'm closing this for now.

**Comment by merwok** [comment]
I have independent requirements files for runtime (requires), test deps, deployment deps.  I need a four-line shell script wrapper to compile them all to their respective target.

**Comment by rpkilby** [comment]
@merwok - that sounds like a different feature. This issue was requesting that a directory of `*.in` files be compiled into a *single* target requirements file, not one-to-one respective targets for each input.

**Comment by merwok** [comment]
You are right!  #532 is that other feature.

**Comment by SanketDG** [comment]
Haha, this was almost three years back. I apologize for my naivety back then. I have since then realized you can just use the suggested alternative. :)

**Comment by atugushev** [comment]
FYI, there is a `pip-compile-multi` project for this particular case.
