### ISSUE TITLE
Stability-focused test infra strategy

### ISSUE THREAD

**Issue by webknjaz** [jazzband/pip-tools#2140]
#### What's the problem this feature will solve?

The CI has been prone to external influence for a long time. This is due to unpinned deps. Pip specifically. Historically, we've been running the tests against a pip version that was pinned to a minor release, and the latest release, plus the `main` branch of the pip repo.

This turned out to be unsustainable since it causes PR runs to become unpredictable over time. Frankly, this is at odds with the reproducibility promise that pip-tools itself seeks to implement for its users.

It also contributes to other CI problems accumulating over time and blocks progress in many other aspects.

#### Describe the solution you'd like

I want to make sure that the CI runs in PRs and pushes use pinned pip, short term. With the future possibility to have more lock files, long-term.

With that in mind, I want to let the nightly runs keep hitting newer pip versions.

#### Alternative Solutions

…suffering the status quo?

#### Additional context

N/A

**Comment by webknjaz** [comment]
One of the problems found while looking into fixing the CI: https://github.com/jazzband/pip-tools/pull/2141.

N.B. I'm going to prepare a series of separate PRs and then a PR merging-in all those branches into one. The combined one is what will need to be approved and merged.

**Comment by webknjaz** [comment]
Found out that we're hitting a problem with the conditionals relying on `${{ github.job_workflow_sha }}` which would have to be rewritten as a hack: https://github.com/actions/runner/issues/2417#issuecomment-1741105197.

**Comment by webknjaz** [comment]
Another PR: #2142.

**Comment by webknjaz** [comment]
I've found a weird behavior that I thought might be a bug in `contextlib.contextmanager`: https://github.com/jazzband/pip-tools/pull/2106/files#r1870250007. But I can't replicate it outside the `pip-compile` invocation (by importing and making the underlying calls separately). I now suspect that Click might be influencing that.
Here's how the problem manifests itself:
```python-traceback
$ pip-compile --build-deps-for wheel --find-links tests/test_data/minimal_wheels /tmp/pytest-of-${USER}/pytest-current/test_compile_build_targets_setcurrent/pyproject.toml --output-file - -vvvvvv
Using pip-tools configuration defaults found in 'pyproject.toml'.
Traceback (most recent call last):
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/${USER}/src/github/jazzband/pip-tools/some-venv-py313/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/${USER}/src/github/jazzband/pip-tools/piptools/scripts/compile.py", line 370, in cli
    metadata = build_project_metadata(
        src_file=Path(src_file),
    ...<4 lines>...
        quiet=log.verbosity <= 0,
    )
  File "/home/${USER}/src/github/jazzband/pip-tools/piptools/build.py", line 164, in build_project_metadata
    with _create_project_builder(
    ...<22 lines>...
        )
  File "/home/${USER}/.pyenv/versions/3.13.0rc1/lib/python3.13/contextlib.py", line 143, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```
I've made a branch to preserve the breaking state: https://github.com/webknjaz/pip-tools/tree/maintenance/contextlib.contextmanager-repro. Perhaps, I'll get to inspect it deeper one day.

**Comment by webknjaz** [comment]
UPD: the CI has been made green. The issue remains open to track long-term improvements.

**Comment by sirosen** [comment]
Overall our CI status is much better than it used to be, but it's still flaky. And it's easy for someone to contribute a flaky test without anyone realizing that it's flaky.

I see two main issues at present, which are related:

- Relying on the network (actual package installation, notably `setuptools`)
- Unstable run times, which sometimes unexpectedly spends our full time limit and makes jobs fail (notable on Windows pypy, which seems to be our worst performer anecdotally)

---

The one major improvement I have in mind for us is to use in-tree build backends for our testing. I need to allocate time to work on this, but I want single-file backends with the following behaviors:

- `fails-if-invoked-backend`: implements PEP 517 hooks and raises errors whenever they are called (testing failure modes, testing that static metadata reads are really static)
  👍 I'm confident this is useful.
- `dynamic-only-backend`: implements PEP 517 hooks and only supports dynamic fields for everything other than `name`, where all fields are actually pulled from some easy source for tests to write (maybe a `tool` table), good for testing dynamic metadata behaviors
  👍 I'm confident this is useful.
- `static-only-backend`: implements PEP 517 hooks but only supports static fields; absolutely nothing is dynamic -- useful for trees of fake packages, where real builds of wheels may be invoked (you could do this with `dynamic-only`, but I think the pair makes sense)
  🤔 I think this is useful?
- `wrapper-backend`: a backend which requires a `tool` config to tell it which backend to actually run, provides hooks which literally just call some other backend's hooks -- good for testing of second-order build deps
  🤷 This makes sense, but I'm not really sure it's useful?

I have another project where I'd like these backends as well. They might be useful for other packaging projects.

I would very much like to learn all of the details of the hook APIs. So this is also, personally, a learning opportunity.

**Comment by webknjaz** [comment]
> * `wrapper-backend`: a backend which requires a `tool` config to tell it which backend to actually run, provides hooks which literally just call some other backend's hooks -- good for testing of second-order build deps
>   🤷 This makes sense, but I'm not really sure it's useful?

I have a bunch of projects with such backend wrappers as in-tree backends so it'd be useful for me to know this approach is regression-tested here, I think. It may mean some testing overhead, but it's probably fine.
