### ISSUE TITLE
pip-sync: fatal error with subprocess.CalledProcessError

### ISSUE THREAD

**Issue by shakaran** [jazzband/pip-tools#284]
I am receiving this stacktrace:

```
# pip-sync 
Uninstalling alabaster-0.7.7:
  Successfully uninstalled alabaster-0.7.7
Uninstalling autobahn-0.11.0:
  Successfully uninstalled autobahn-0.11.0
Uninstalling Babel-2.1.1:
  Successfully uninstalled Babel-2.1.1
Uninstalling backports-abc-0.4:
  Successfully uninstalled backports-abc-0.4
Uninstalling chardet-2.3.0:
  Successfully uninstalled chardet-2.3.0
Uninstalling cloudpickle-0.1.1:
  Successfully uninstalled cloudpickle-0.1.1
Uninstalling contextlib2-0.4.0:
  Successfully uninstalled contextlib2-0.4.0
Uninstalling cssselect-0.9.1:
  Successfully uninstalled cssselect-0.9.1
Uninstalling distribute-0.7.3:
  Successfully uninstalled distribute-0.7.3
Uninstalling django-contrib-comments-1.6.2:
  Successfully uninstalled django-contrib-comments-1.6.2
Uninstalling django-user-accounts-1.3.1:
  Successfully uninstalled django-user-accounts-1.3.1
Uninstalling husl-4.0.3:
  Successfully uninstalled husl-4.0.3
Uninstalling microsofttranslator-0.7:
  Successfully uninstalled microsofttranslator-0.7
Uninstalling pyOpenSSL-0.15.1:
  Successfully uninstalled pyOpenSSL-0.15.1
Uninstalling service-identity-14.0.0:
  Successfully uninstalled service-identity-14.0.0
Uninstalling snowballstemmer-1.2.1:
  Successfully uninstalled snowballstemmer-1.2.1
Uninstalling sphinx-rtd-theme-0.1.9:
  Successfully uninstalled sphinx-rtd-theme-0.1.9
Uninstalling txaio-2.2.0:
  Successfully uninstalled txaio-2.2.0
/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting Beaker==1.6.4
/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Beaker-1.6.4.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 1.4MB/s 
Collecting Cython==0.21
  Downloading Cython-0.21.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 281kB/s 
Collecting Django==1.7
  Downloading Django-1.7-py2.py3-none-any.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 64kB/s 
Collecting Fabric==1.10.0
  Downloading Fabric-1.10.0.tar.gz (208kB)
    100% |████████████████████████████████| 212kB 1.4MB/s 
Collecting Jinja2==2.7.3
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |████████████████████████████████| 380kB 1.6MB/s 
Collecting Logbook==0.7.0
  Downloading Logbook-0.7.0.tar.gz (147kB)
    100% |████████████████████████████████| 147kB 2.9MB/s 
Collecting Mako==1.0.0
  Downloading Mako-1.0.0.tar.gz (470kB)
    100% |████████████████████████████████| 471kB 710kB/s 
Collecting Markdown==2.5.1
  Downloading Markdown-2.5.1.tar.gz (288kB)
    100% |████████████████████████████████| 290kB 1.7MB/s 
Collecting Mezzanine==3.1.10
  Downloading Mezzanine-3.1.10-py2.py3-none-any.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 80kB/s 
Collecting Nikola==7.1.0
  Downloading nikola-7.1.0.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 306kB/s 
Collecting Paste==1.7.5.1
  Downloading Paste-1.7.5.1.tar.gz (523kB)
    100% |████████████████████████████████| 524kB 937kB/s 
Collecting Pillow==2.5.3
  Downloading Pillow-2.5.3.zip (6.9MB)
    100% |████████████████████████████████| 6.9MB 68kB/s 
Collecting PyMySQL==0.6.2
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 65kB 6.3MB/s 
Collecting Pygments==1.6
  Downloading Pygments-1.6.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 305kB/s 
Collecting Pyro4==4.28
  Downloading Pyro4-4.28-py2.py3-none-any.whl (141kB)
    100% |████████████████████████████████| 143kB 1.3MB/s 
Collecting RBTools==0.6.2
  Could not find a version that satisfies the requirement RBTools==0.6.2 (from versions: 0.7.5)
No matching distribution found for RBTools==0.6.2
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 68, in cli
    pip_flags=pip_flags))
  File "/usr/local/lib/python2.7/site-packages/piptools/sync.py", line 145, in sync
    check_call(['pip', 'install'] + pip_flags + sorted(to_install))
  File "/usr/local/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', 'Beaker==1.6.4', 'Cython==0.21', 'Django==1.7', 'Fabric==1.10.0', 'Jinja2==2.7.3', 'Logbook==0.7.0', 'Mako==1.0.0', 'Markdown==2.5.1', 'Mezzanine==3.1.10', 'Nikola==7.1.0', 'Paste==1.7.5.1', 'Pillow==2.5.3', 'PyMySQL==0.6.2', 'Pygments==1.6', 'Pyro4==4.28', 'RBTools==0.6.2', 'Radicale==0.9', 'SQLAlchemy==0.9.7', 'Scrapy==0.22.0', 'South==1.0', 'Sphinx==1.2.3', 'Trac==1.0.1', 'Twisted==14.0.2', 'Unidecode==0.04.16', 'WTForms==2.0.1', 'WebOb==1.4', 'WebTest==2.0.16', 'Werkzeug==0.9.6', 'Whoosh==2.5.7', 'Yapsy==1.10.423', 'argh==0.25.0', 'argparse==1.2.1', 'aspen==0.34', 'backports.ssl-match-hostname==3.4.0.2', 'beautifulsoup4==4.3.2', 'bleach==1.4', 'blinker==1.3', 'bootstrap-admin==0.3.0', 'buildbot==0.8.9', 'certifi==14.05.14', 'colorama==0.3.2', 'commando==0.3.4', 'cssutils==1.0', 'decorator==3.4.0', 'django-admin-tools==0.5.2', 'django-ajax-selects==1.3.5', 'django-appconf==0.6', 'django-autofixture==0.9.1', 'django-autoslug==1.7.2', 'django-classy-tags==0.5.1', 'django-compressor==1.4', 'django-crispy-forms==1.4.0', 'django-dajaxice==0.6', 'django-debug-toolbar==1.2.1', 'django-evolution==0.6.9', 'django-extensions==1.4.0', 'django-facebook==6.0.1', 'django-fluent-dashboard==0.3.6', 'django-geoip==0.5.1', 'django-inplaceedit==1.3.0', 'django-jsonfield==0.9.13', 'django-mptt==0.6.1', 'django-notification==1.2.0', 'django-pdb==0.4.0', 'django-pipeline==1.3.25', 'django-registration==1.0', 'django-rosetta==0.7.4', 'django-simple-captcha==0.4.2', 'django-su==0.4.7', 'django-tagging==0.3.2', 'django-tastypie==0.12.0', 'django-threadedcomments==0.9.0', 'django-tinymce==1.5.3', 'doit==0.26.0', 'dynpool==1.0.5', 'easy-thumbnails==2.1', 'ecdsa==0.11', 'eventlet==0.15.2', 'feedparser==5.1.3', 'filebrowser-safe==0.3.6', 'filesystem-tree==1.0.1', 'fswrap==0.1.2', 'future==0.13.1', 'futures==2.2.0', 'grappelli-safe==0.3.13', 'greenlet==0.4.4', 'html5lib==0.999', 'httplib2==0.9', 'hyde==0.8.8', 'lockfile==0.10.2', 'mailer==0.7', 'natsort==3.5.1', 'nose==1.3.4', 'numpy==1.9.0', 'oauth2==1.5.211', 'oauthlib==0.6.3', 'paramiko==1.15.1', 'pbr==0.10.0', 'pecan==0.7.0', 'pelican==3.4.0', 'pep8==1.5.7', 'pexif==0.13', 'pip-tools==0.3.5', 'polib==1.0.5', 'progressbar==2.3dev', 'pyactiveresource==2.1.0', 'pyinotify==0.9.4', 'pymongo==2.7.2', 'pyparsing==2.0.2', 'pysqlite==2.6.3', 'python-daemon==1.5.5', 'python-dateutil==2.2', 'python-memcached==1.53', 'python-twitter==2.0', 'pytz==2014.7', 'queuelib==1.2.2', 'raven==5.0.0', 'reportlab==3.1.8', 'requests-oauthlib==0.4.1', 'requests==2.4.1', 'serpent==1.7', 'simplejson==3.6.3', 'six==1.8.0', 'sorl-thumbnail==11.12.1b', 'sqlalchemy-migrate==0.9.2', 'sqlparse==0.1.12', 'tornado==4.0.2', 'tzlocal==1.1.1', 'virtualenv==1.11.6', 'w3lib==1.10.0', 'waitress==0.8.9', 'watchdog==0.8.1', 'wsgiref==0.1.2']' returned non-zero exit status 1
```

**Comment by vphilippon** [comment]
This was a while ago. I'll close for now. If a similar issue still occurs with the latest version, fell free to reopen with your requirements.in/txt.

**Comment by shakaran** [comment]
@vphilippon I would like that you reopen, after update again all the packages, I get the following now:

```
# pip-sync
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 53, in cli
    requirements = sync.merge(requirements, ignore_conflicts=force)
  File "/usr/local/lib/python2.7/site-packages/piptools/sync.py", line 73, in merge
    key = ireq.link or ireq.req.key
AttributeError: 'Requirement' object has no attribute 'key'
```

**Comment by vphilippon** [comment]
That's a different issue, yet a known issue that should be fixed in the upcoming v1.10. Could try it with the master branch (or wait for 1.10 to come out and then try it)?

I'll reopen for tracking purposes.

**Comment by shakaran** [comment]
Not sure which is the proper way to update, since it seems revert back to 1.4.2:

```
[~]# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
[~]# pip install pip-tools
Requirement already satisfied: pip-tools in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: first in /usr/local/lib/python2.7/site-packages (from pip-tools)
Requirement already satisfied: click>=6 in /usr/local/lib/python2.7/site-packages (from pip-tools)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from pip-tools)
[~]# pip install -U  pip-tools
Collecting pip-tools
  Downloading pip_tools-1.10.1-py2.py3-none-any.whl
Collecting setuptools (from pip-tools)
  Downloading setuptools-36.5.0-py2.py3-none-any.whl (478kB)
    100% |████████████████████████████████| 481kB 868kB/s 
Requirement already up-to-date: first in /usr/local/lib/python2.7/site-packages (from pip-tools)
Collecting click>=6 (from pip-tools)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 5.0MB/s 
Collecting six (from pip-tools)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: setuptools, click, six, pip-tools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Found existing installation: click 6.2
    Uninstalling click-6.2:
      Successfully uninstalled click-6.2
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: pip-tools 1.4.2
    Uninstalling pip-tools-1.4.2:
      Successfully uninstalled pip-tools-1.4.2
Successfully installed click-6.7 pip-tools-1.10.1 setuptools-36.5.0 six-1.11.0
[~]# pip-sync 
Uninstalling cycler-0.10.0:
  Successfully uninstalled cycler-0.10.0
Uninstalling pycrypto-2.6.1:
  Successfully uninstalled pycrypto-2.6.1
Not uninstalling wsgiref at /usr/local/lib/python2.7, as it is in the standard library.
Collecting click==6.2
  Using cached click-6.2-py2.py3-none-any.whl
Collecting pip-tools==1.4.2
  Using cached pip_tools-1.4.2-py2.py3-none-any.whl
Collecting six==1.10.0
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: first in /usr/local/lib/python2.7/site-packages (from pip-tools==1.4.2)
Installing collected packages: click, six, pip-tools
  Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: pip-tools 1.10.1
    Uninstalling pip-tools-1.10.1:
      Successfully uninstalled pip-tools-1.10.1
Successfully installed click-6.2 pip-tools-1.4.2 six-1.10.0
[~]# pip-sync
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 53, in cli
    requirements = sync.merge(requirements, ignore_conflicts=force)
  File "/usr/local/lib/python2.7/site-packages/piptools/sync.py", line 73, in merge
    key = ireq.link or ireq.req.key
AttributeError: 'Requirement' object has no attribute 'key'
```

**Comment by vphilippon** [comment]
`pip-tools` seems to be in the requirements.txt, pinned to 1.4.2. Either it got included by mistake by a previous pip-tools version, or it's in your requirement.in.

So
1 - Make sure `pip-tools` is not in your requirements.in*
2 - Re-run `pip-compile` to freshen your requirements.txt
3 - Run `pip-sync`

* If you actually want to have `pip-tools` in your requirements.in (and know what you're doing), then keep it, but run `pip-compile --upgrade-package pip-tools`, then run `pip-sync`.

**Comment by shakaran** [comment]
I only have a requirements.txt file. After remove pip-tools 1.4.2 from the requirements file and update pip-tools to latest, when I run pip-sync, it seems to work perfectly now without traces.

**Comment by vphilippon** [comment]
Allrighty, I'm glad you're on the road.
Closing

**Comment by lsiden** [comment]
I would like to re-open this. I am attempting to run this while building a Docker image based on python:3.10.3-bullseye. It breaks intermittently. pip-compile prints:

```
#15 7.764 Traceback (most recent call last):
#15 7.764   File "/venv/bin/pip-compile", line 8, in <module>
#15 7.764     sys.exit(cli())
#15 7.764   File "/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
#15 7.765     return self.main(*args, **kwargs)
#15 7.765   File "/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
#15 7.765     rv = self.invoke(ctx)
#15 7.765   File "/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
#15 7.765     return ctx.invoke(self.callback, **ctx.params)
#15 7.765   File "/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
#15 7.766     return __callback(*args, **kwargs)
#15 7.766   File "/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
#15 7.766     return f(get_current_context(), *args, **kwargs)
#15 7.766   File "/venv/lib/python3.10/site-packages/piptools/scripts/compile.py", line 408, in cli
#15 7.766     dist = meta.load(os.path.dirname(os.path.abspath(src_file)))
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/meta.py", line 71, in load
#15 7.766     path = Path(build_as_zip(builder))
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/meta.py", line 58, in build_as_zip
#15 7.766     builder(dest=out_dir)
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/meta.py", line 53, in build
#15 7.766     _prep_meta(hooks, env, dest)
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/meta.py", line 28, in _prep_meta
#15 7.766     reqs = hooks.get_requires_for_build_wheel({})
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
#15 7.766     return self._call_hook('get_requires_for_build_wheel', {
#15 7.766   File "/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 322, in _call_hook
#15 7.767     self._subprocess_runner(
#15 7.767   File "/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 75, in quiet_subprocess_runner
#15 7.767     check_output(cmd, cwd=cwd, env=env, stderr=STDOUT)
#15 7.767   File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
#15 7.767     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#15 7.767   File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
#15 7.767     raise CalledProcessError(retcode, process.args,
#15 7.767 subprocess.CalledProcessError: Comm
[Dockerfile.txt](https://github.com/jazzband/pip-tools/files/8391959/Dockerfile.txt)
and '['/venv/bin/python3', '/venv/lib/python3.10/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp_pbx08qh']' returned non-zero exit status 1.
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c pip install pip-tools     && pip-compile --generate-hashes     && pip install -r requirements.txt     && pip install pytest black]: runc did not terminate sucessfully
make: *** [image] Error 1
```

I uploaded my dockerfile as Dockerfile.txt (so the file uploader would accept it).

**Comment by AndydeCleyre** [comment]
@lsiden Please share your `setup.py`, it may not be quite valid with current versions of setuptools. You may want to look at [these comments](https://github.com/jazzband/pip-tools/issues/1603#issuecomment-1082882907).

**Comment by AndydeCleyre** [comment]
@lsiden Please note that this issue is very old, and was created for a problem encountered in usage of `pip-sync`, while your issue occurs during `pip-compile`.

I think probably it's the same stuff discussed at #1603, but if it's not, please open a new issue. Thanks!
