### ISSUE TITLE
pip-compile fails with pip-tools 1.5 and pip 8.0.2

### ISSUE THREAD

**Issue by lukeorland** [jazzband/pip-tools#307]
similar to #304.
This time, with python==2.7.10

It works with python==3.5.1.

```
$ pip install -U pip pip-tools setuptools
Collecting pip
  Using cached pip-8.0.2-py2.py3-none-any.whl
Collecting pip-tools
  Using cached pip_tools-1.5-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-19.6-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached click-6.2-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached first-2.0.1-py2.py3-none-any.whl
Installing collected packages: pip, click, six, first, pip-tools, setuptools
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed click-6.2 first-2.0.1 pip-8.0.2 pip-tools-1.5 setuptools-19.6 six-1.10.0

$ pip-compile requirements.in
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 141, in cli
    results = resolver.resolve()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 78, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 154, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 154, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 201, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 94, in find_best_match
    all_candidates = self.find_all_versions(ireq.name)
  File "/usr/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 83, in find_all_versions
    self._available_versions_cache[req_name] = self.finder._find_all_versions(req_name)
AttributeError: 'PackageFinder' object has no attribute '_find_all_versions'
```

**Comment by vphilippon** [comment]
Likely fixed in pip-tools 1.5 and pip 8.
Feel free to reopen if needed.
