### ISSUE TITLE
pip-tools doesn't work with Seep

### ISSUE THREAD

**Issue by GMLudo** [jazzband/pip-tools#375]
If I have this dependency in requirements.in:
-e git+https://github.com/Julian/Seep.git@667dfd57949b1caed3031ac3da37b0f34c06002a#egg=seep

I've this traceback: 

```
Traceback (most recent call last):
  File "/opt/john_doe/pyvenv/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/scripts/compile.py", line 161, in cli
    results = resolver.resolve()
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/resolver.py", line 103, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/resolver.py", line 185, in _resolve_one_round
    for best_match in best_matches
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/resolver.py", line 186, in <genexpr>
    for dep in self._iter_dependencies(best_match))
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/resolver.py", line 243, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/repositories/local.py", line 65, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/piptools/repositories/pypi.py", line 132, in get_dependencies
    dependencies = reqset._prepare_file(self.finder, ireq)
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/pip/req/req_set.py", line 489, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/john_doe/pyvenv/lib/python3.4/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 2 in /tmp/tmp0zyzejwysource/seep/
```

But, if I do that manually: 

```
# python setup.py egg_info
zip_safe flag not set; analyzing archive contents...

Installed /opt/Seep/.eggs/vcversioner-2.16.0.0-py3.4.egg
running egg_info
creating seep.egg-info
writing dependency_links to seep.egg-info/dependency_links.txt
writing seep.egg-info/PKG-INFO
writing requirements to seep.egg-info/requires.txt
writing top-level names to seep.egg-info/top_level.txt
writing manifest file 'seep.egg-info/SOURCES.txt'
reading manifest file 'seep.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'seep.egg-info/SOURCES.txt'
```

To me, it should be linked that **setup_requires** shouldn't be respected by pip-tools.

Thanks for your answer.

**Comment by nvie** [comment]
Can you verify that this is not a Python version issue? We've seen this in the past. Seems like you're using Python 3 for running `pip-compile`. In the second snippet, is the `python` command you're running also Python 3?

**Comment by GMLudo** [comment]
Good catch, I was in the middle of Python 3.5 migration, I'll test that again to validate your hypothesis.

**Comment by davidovich** [comment]
@GMLudo is this still a problem ? It may be the same issue as #369, which is about a bug when setup_requires is used to install local eggs.

**Comment by vphilippon** [comment]
No follow up, I'll close this, feel free to mention if it's still an issue.

**Comment by GMLudo** [comment]
Sorry, I have forgotten to close this issue, the problem was gone a long time ago.

Regards.
