### ISSUE TITLE
--trusted-host causes pip-sync to fail

### ISSUE THREAD

**Issue by Groxx** [jazzband/pip-tools#380]
pip-compiling with `pip-tools==1.7.0` produces a file with:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --no-index --output-file tmp_all_requirements.txt requirements.txt requirements-docs.txt requirements-dev.txt requirements-test.txt
#
--trusted-host pypi.local.internal
--trusted-host archive.local.internal
...
```

which then fails to sync with an error:

```
Usage: pip-sync [options]

Traceback (most recent call last):
  File "/mnt/jenkins/workspace/test-irslib/env/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 52, in cli
    requirements = sync.merge(requirements, ignore_conflicts=force)
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/piptools/sync.py", line 70, in merge
    for ireq in requirements:
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/pip/req/req_file.py", line 119, in process_line
    opts, _ = parser.parse_args(shlex.split(options_str), defaults)
  File "/usr/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/mnt/jenkins/workspace/test-irslib/env/local/lib/python2.7/site-packages/pip/req/req_file.py", line 238, in parser_exit
    raise RequirementsFileParseError(msg)
pip.exceptions.RequirementsFileParseError: pip-sync: error: no such option: --trusted-host
```

Is `--trusted-host` not supported in pip-sync?

**Comment by markfink** [comment]
same here

**Comment by davidovich** [comment]
This should be supported now if you use a recent version of pip. In fact, it is in pip 8.0 which is the lowest version supported by pip-tools. See: https://pip.pypa.io/en/stable/news/

**Comment by Groxx** [comment]
I can open a new issue for this, but it'd still be useful to have a `--no-trusted-host` option.  Local / CI / production use different pypi hosts for us (for.... reasons?  I have no idea, I just live with it), and CI and production don't have access to the local ones, so we can't allow `--trusted-host` in our output.  All pypi access is done via pip.conf files.

Right now I'm just removing those lines, but it'd be great to not have to do that.

**Comment by Groxx** [comment]
Ah, nevermind, there is one!  Awesome.  Using it now!
