### ISSUE TITLE
RequirementParseError if mock is included

### ISSUE THREAD

**Issue by genericmoniker** [jazzband/pip-tools#390]
If I include "mock" in my requirements.in file, I get a RequirementParseError when running pip-compile. If I include other dependencies, but not mock, things work as expected.

pip-tools 1.7.0
python 2.7.9
windows 10
##### Steps to replicate
1. Create a requirements.in file with mock as the only entry
2. Run pip-compile
##### Expected result

Output requirements.txt containing mock
##### Actual result

```
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Users\Eric\Envs\chorebot\Scripts\pip-compile.exe\__main__.py", line 9, in <module>
  File "d:\users\eric\envs\chorebot\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "d:\users\eric\envs\chorebot\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "d:\users\eric\envs\chorebot\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\users\eric\envs\chorebot\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\scripts\compile.py", line 195, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\resolver.py", line 267, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\utils.py", line 191, in lookup_table
    for value in values:
  File "d:\users\eric\envs\chorebot\lib\site-packages\piptools\cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "d:\users\eric\envs\chorebot\lib\site-packages\pkg_resources\__init__.py", line 2986, in parse
    reqs = list(parse_requirements(s))
  File "d:\users\eric\envs\chorebot\lib\site-packages\pkg_resources\__init__.py", line 2930, in parse_requirements
    "version spec")
  File "d:\users\eric\envs\chorebot\lib\site-packages\pkg_resources\__init__.py", line 2906, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in funcsigs>=1; python_version < "3.3" at ; python_version < "3.3"
```

**Comment by felipemontoya** [comment]
I get the same thing. It looks like pip-tools breaks on [this line](https://github.com/testing-cabal/mock/blob/master/requirements.txt#L1)

**Comment by johnlinvc** [comment]
Update setuptools to 28.7.1 solved this issue for me.

**Comment by vphilippon** [comment]
This should be fixed with newer versions of setuptools (update setuptools to 28.7.1 and higher as @jasonm 
 mentionned).
Closing, feel free to reopen if it happens again.
