### ISSUE TITLE
pip-sync appears to get confused about editable packages

### ISSUE THREAD

**Issue by triplepoint** [jazzband/pip-tools#399]
When a requirements.txt file includes editable local packages, pip-sync seems to want to uninstall them and reinstall them.

Also, the pip install command that pip-sync attempts to perform is missing the `-e` editable flags, resulting in an error.
##### Steps to replicate
- Create a new virtualenv for testing

``` bash
virtualenv --no-site-packages testvenv
source ./testvenv/bin/activate
pip list
```

returns:

```
pip (8.1.2)
setuptools (28.3.0)
wheel (0.30.0a0)
```
- Generate a requirements.txt file (obfuscated from our actual names):

```
-e file:///vagrant/projects/someproject
```
- Install the editable project into the virtualenv

``` bash
pip install -r requirements.txt --no-deps
```
- Install pip-tools into the venv (because the globally installed pip-tools doesn't seem to deal with virtualenvironents well (another bug?) )

``` bash
pip install pip-tools
deactivate
source ./testvenv/bin/activate
```
- See what pip-sync thinks

``` bash
pip-sync -n requirements.txt
```

returns _unexpected results_:

```
Would uninstall:
  our.package.name
Would install:
  file:///vagrant/projects/packagename
```
- Try to do the sync

```
pip-sync requirements.txt
```

returns

```
Uninstalling our.package.name-1.2.3+dirty:
  Successfully uninstalled our.package.name-1.2.3+dirty
Processing /vagrant/projects/packagename
    Complete output from command python setup.py egg_info:

*** Bunch of errors we generate related to our package's assumptions about being a git repo ***

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ls2yuR-build/
Traceback (most recent call last):
  File "/home/vagrant/testvenv/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 72, in cli
    install_flags=install_flags))
  File "/home/vagrant/testvenv/local/lib/python2.7/site-packages/piptools/sync.py", line 157, in sync
    check_call([pip, 'install'] + pip_flags + install_flags + sorted(to_install))
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', 'file:///vagrant/projects/packagename']' returned non-zero exit status 1
```
##### Expected result

A) The tool shouldn't be attempting to uninstall the editable package and then reinstall it
B) Installing editable packages should have a `-e` option

**Comment by ulope** [comment]
Indeed this makes it really difficult to use pip-sync while developing packages.
