### ISSUE TITLE
pip-compile unable to handle requests[security]

### ISSUE THREAD

**Issue by chrispbailey** [jazzband/pip-tools#419]
Can't use `requests[security]` in my requirements.in file

##### Steps to replicate
Using pip 9.0.1 & pip-tools 1.8.0
requirements.in:
```
requests[security]
```

##### Expected result
Not exactly sure, but something like:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
cffi==1.9.1               # via cryptography
cryptography==1.6         # via pyopenssl
enum34==1.1.6             # via cryptography
idna==2.1                 # via cryptography
ipaddress==1.0.17         # via cryptography
ndg-httpsclient==0.4.2
pyasn1==0.1.9
pycparser==2.17           # via cffi
pyOpenSSL==16.2.0         # via ndg-httpsclient
requests==2.12.1
six==1.10.0               # via cryptography, pyopenssl

# The following packages are considered to be unsafe in a requirements file:
# setuptools                # via cryptography
```

##### Actual result
```
/tmp > ve/bin/pip-compile requirements.in 
Traceback (most recent call last):
  File "ve/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/tmp/ve/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/ve/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/tmp/ve/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/ve/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 223, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/resolver.py", line 273, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/utils.py", line 192, in lookup_table
    for value in values:
  File "/tmp/ve/local/lib/python2.7/site-packages/piptools/cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2986, in parse
    reqs = list(parse_requirements(s))
  File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/tmp/ve/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2906, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in cryptography>=1.3.4; extra == "security" at ; extra == "security"
```

**Comment by woozyking** [comment]
I think the bundle format support is generally not working, for example, broken also for `celery[redis]`

**Comment by RazerM** [comment]
I can't reproduce, did I understand the issue correctly?

```
root@22f7b4dea128:/# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
root@22f7b4dea128:/# echo "requests[security]" > requirements.in
root@22f7b4dea128:/# pip-compile requirements.in
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
cffi==1.9.1               # via cryptography
cryptography==1.6         # via pyopenssl, requests
enum34==1.1.6             # via cryptography
idna==2.1                 # via cryptography, requests
ipaddress==1.0.17         # via cryptography
pyasn1==0.1.9             # via cryptography
pycparser==2.17           # via cffi
pyopenssl==16.2.0         # via requests
requests[security]==2.12.3
six==1.10.0               # via cryptography, pyopenssl

# The following packages are considered to be unsafe in a requirements file:
# setuptools                # via cryptography
```

**Comment by woozyking** [comment]
@RazerM yes you understood it correctly.

I've been able to reproduce this issue on both `Python 2.7` and `Python 3.5`, `macOS Sierra 10.12.1` and `Ubuntu 14.04.4`

**Comment by RazerM** [comment]
@woozyking I used the docker python container. I will try to reproduce on macOS later.

**Comment by cancan101** [comment]
See: https://github.com/nvie/pip-tools/issues/390#issuecomment-258356585

**Comment by davidovich** [comment]
This should be fixed with newer versions of setuptools (Update setuptools to 28.7.1 and higher). Closing, feel free to reopen if still present.
