### ISSUE TITLE
pip-compile breaks because of missing option values in pip

### ISSUE THREAD

**Issue by hgylfason** [jazzband/pip-tools#432]
pip-compile command doesn't run successfully because pip complains about missing attributes for options --no-binary/--only-binary.

##### Steps to replicate

1. Install pip-tools
2. Run pip-compile command

##### Expected result
An updated requirements.txt file
...

##### Actual result
An error

```
Traceback (most recent call last):
  File "/usr/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/piptools/scripts/compile.py", line 140, in cli
    for ireq in ireqs:
  File "/usr/lib/python3.5/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/lib/python3.5/site-packages/pip/req/req_file.py", line 150, in process_line
    cmdoptions.check_install_build_global(options, opts)
  File "/usr/lib/python3.5/site-packages/pip/cmdoptions.py", line 56, in check_install_build_global
    control = options.format_control
AttributeError: 'Values' object has no attribute 'format_control'
```

**Comment by vphilippon** [comment]
Hi, could you:
- Check if the issue still occurs?
- If it does, give the pip version and a sample `requirements.in`?
Thanks!

**Comment by hgylfason** [comment]
The problem still persists.

I'm not sure if it matters but my environment is in a virtual machine run managed by Vagrant.

**Comment by hgylfason** [comment]
- pip-tools version `1.9.0`
- pip version `9.0.1`
- python version `3.5.3`

#### requirements.in
It doesn't seem to matter what is inside the requirements.in file. But here is a short sample that fails.
```
Django>=1.8,<1.9
```

#### traceback
```
ssh://vagrant@127.0.0.1:2222/bin/python3.5 -u /usr/bin/pip-compile requirements.in
Traceback (most recent call last):
  File "/usr/bin/pip-compile", line 11, in <module>
    load_entry_point('pip-tools==1.9.0', 'console_scripts', 'pip-compile')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/piptools/scripts/compile.py", line 136, in cli
    for ireq in ireqs
  File "/usr/lib/python3.5/site-packages/piptools/scripts/compile.py", line 135, in <dictcomp>
    existing_pins = {key_from_req(ireq.req): ireq
  File "/usr/lib/python3.5/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/lib/python3.5/site-packages/pip/req/req_file.py", line 150, in process_line
    cmdoptions.check_install_build_global(options, opts)
  File "/usr/lib/python3.5/site-packages/pip/cmdoptions.py", line 56, in check_install_build_global
    control = options.format_control
AttributeError: 'Values' object has no attribute 'format_control'

Process finished with exit code 1
```

**Comment by nazavode** [comment]
Exactly the same here.

**Comment by vphilippon** [comment]
I'll close this as an error introduced in the `requirements.txt` somehow. If someone thinks there's something to be done here, speak up and we'll see.
