### ISSUE TITLE
pip-compile does not support python_version limits

### ISSUE THREAD

**Issue by blr246** [jazzband/pip-tools#435]
The `s3transfer` package changed recently to add some `python_version` limits (https://github.com/boto/s3transfer/commit/d68f662ec6a997b74ea4d241708728da03a62c95).

When `pip-compile` tries to parse these requirements, it passes the additional `python_version` strings to `pkg_resources.parse`, causing the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 223, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 273, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "/usr/local/lib/python2.7/site-packages/piptools/utils.py", line 192, in lookup_table
    for value in values:
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3044, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2988, in parse_requirements
    "version spec")
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2964, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" at ; python_version == "2.6" or python_version == "2.7"
```

##### Steps to replicate

1. Run a simple test:
```bash
$ echo s3transfer==0.1.10 >requirements.in && pip-compile
```

##### Expected result

We expect `pip-compile` to generate a valid `requirements.txt`.

##### Actual result

`pip-compile` fails in `pkg_resources.parse` due to passing of extra `python_version` constraints.

**Comment by vphilippon** [comment]
I can't reproduce this, I'm tried using:
```
pip-tools: 1.8.2
pip: 9.0.1 and 8.1.1
```
Can you confirm if it's already fixed, or give some additionnal info?
Thanks!

**Comment by blr246** [comment]
I can't reproduce this anymore. Perhaps the referenced package was broken in some way?

I'm closing this. If others following have another path to reproduce, then we can re-open or create a new issue.
