### ISSUE TITLE
Fails with exception on `eve-mongoengine`

### ISSUE THREAD

**Issue by pmatos** [jazzband/pip-tools#496]
With the following `requirements.in`:
```
Eve                
Flask           
rollbar           
blinker        
eve-mongoengine    
flask-mongoengine
```

I get an error. 

##### Environment Versions

1. OS Type
`Linux andromeda.desktop 4.10.8-200.fc25.x86_64 #1 SMP Fri Mar 31 13:20:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
2. Python version: `$ python -V`
Python 3.6.0
3. pip version:  `$ pip --version`
pip 9.0.1 from /home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages (python 3.6)
4. pip-tools version: `$ pip-compile --version`
$ pip-compile --version
pip-compile, version 1.9.0

##### Steps to replicate

1. Check `requirements.in` above
2. `$ pip-compile -o requirements.txt requirements.in`
3. See failure

##### Expected result

`requirements.txt` generated

##### Actual result

```
$ pip-compile -o requirements/viz-requirements.txt requirements/viz-requirements.in 
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/cfd-venv/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/repositories/local.py", line 62, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp27o50y9pbuild/flask-mongoengine/
```

**Comment by pmatos** [comment]
Actually `eve-mongoengine` is the problematic package and you just need to have that in the requirements for pip-compile to blowup.

**Comment by davidovich** [comment]
can you try upgrading setuptools in your venv and see if that helps ?

**Comment by jonafato** [comment]
I'm unable to reproduce this. Is it still an issue?

**Comment by pmatos** [comment]
OK, I have updated, retried and saw no more failures.
