### ISSUE TITLE
Running `pip-compile` with a tabular dependency causes an error

### ISSUE THREAD

**Issue by alexwlchan** [jazzband/pip-tools#504]
If I have the "tabulate" package in my `requirements.in` and run `pip-compile`, I get an error.

#### Environment Versions

1. OS Type: macOS 10.12.1 (16B2657)
1. Python version: `Python 3.6.1`
1. pip version: `pip 9.0.1 from /Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages (python 3.6)`
1. pip-tools version: `pip-compile, version 1.9.0`

#### Steps to replicate

1. Create a `requirements.in` file as follows:

    ```console
    $ echo 'tabular' > requirements.in
    $ cat requirements.in
    tabular
    ```

2. Run `pip-compile`.

#### Expected result

`pip-compile` will print the contents of an auto-generated requirements.txt to stdout.

#### Actual result

It errors out:

```console
$ pip-compile
Traceback (most recent call last):
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/repositories/local.py", line 62, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/chana/.virtualenvs/tempenv-2c423021471bf/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/d5/343w9s3571b83byxtmm3x55xmmchgj/T/tmpclnqkku8build/tabular/
```

I can replicate on Python 2.

(This particular package is at least four years old, so might have an old `setup.py` or something; I only discovered this when I misspelt the name of a different package.)

**Comment by vphilippon** [comment]
Out of curiosity, I checked if `tabular` was "pip-installable":

```
$ pip install tabular
Collecting tabular
<snip>
  Downloading tabular-0.1.tar.gz (1.1MB)
    100% |################################| 1.1MB 787kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "e:\tmp\pip-build-gqxnbg\tabular\setup.py", line 50, in <module>
        raise ImportError("distribute was not found and fallback to setuptools was not allowed")
    ImportError: distribute was not found and fallback to setuptools was not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in e:\tmp\pip-build-gqxnbg\tabular\
```
If `pip install` fails, I'd say it's not something wrong with pip-tools.

Again, out of curiosity, I looked at the `setup.py`, and it got some logic trying to import `distribute_setup`, which I believe requires to have a `distribute_setup.py` script (which isn't there) or the installed setuptools version to offer some support for distribute, which isn't the case for me (`setuptools==35.0.2`). I'm not a distribute pro, so I might be missing something, but as @alexwlchan suggested, that's something with the `setup.py` and most likely out of pip-tools hands.

I'll go ahead and close the issue.
@alexwlchan if you (or anyone else encountering this) find out there's actually something wrong with pip-tools regarding this, feel free to reopen the issue.
Thanks for reporting!
