### ISSUE TITLE
pip-compile: environment markers directly in the requirements.in file are not taken into account

### ISSUE THREAD

**Issue by ran-z** [jazzband/pip-tools#536]
I have the following line in my `requirements.in` file:

`pypiwin32==219 ; sys_platform == 'win32'`

when running `pip-compile`, I'm getting the following error message:

`pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpFCWEt3build/pypiwin32/`

I've made sure it's not because of the second half (environment markers), but rather the problem seems to be related to the version of the package.

##### Environment Versions

OS Type: Ubuntu 16.04
Python version: 2.7.12
pip version:  9.0.1
pip-tools version: 1.9.0

**Comment by vphilippon** [comment]
Odd, I have the same package (with the same version) working allright with `pip-compile`, on Windows.

I have a strong feeling the error is due to `pip` trying to build the package (which is Windows Only) on linux, but I would expect the environment marker to prevent that.

Question: How have you made sure it's not due to the environment marker?

**Comment by ran-z** [comment]
Oh, I simply meant I tried removing the environment marker section and running `pip-compile`. I was on a Linux machine, but the error that I got was the same.

According to the stack trace, it indeed looks like it tries to get the dependencies list:

```
Traceback (most recent call last):
  File "<some-path>/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "<some-path>/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "<some-path>/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "<some-path>/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<some-path>/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "<some-path>/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "<some-path>/local/lib/python2.7/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "<some-path>/local/lib/python2.7/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "<some-path>/local/lib/python2.7/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "<some-path>/local/lib/python2.7/site-packages/piptools/repositories/local.py", line 62, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "<some-path>/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "<some-path>/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "<some-path>/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "<some-path>/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "<some-path>/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp1t2Q00build/pypiwin32/
```

**Comment by vphilippon** [comment]
I did a bit of testing, and it confirmed my original thought: The environment markers directly in the `requirements.in` file are not taken into account by `pip-compile`. But, those in the sub-dependencies are.

Ex: (warning: do not read before your first coffee)
With this `setup.py`:
```
setup(
    name='dummy-test',
    version='1.0.0',
    extras_require={
        ':sys_platform == "win32"': ['pypiwin32==219'],
    },
)
```
and this `requirements.in`:
```
dummy-test
```
We get this `requirements.txt` (on windows):
```
dummy-test==1.0.0
pypiwin32==219            # via dummy-test
```
and on linux (or if I change the condition to `sys_platform != "win32"`:
```
dummy-test==1.0.0
```

But if I put `pypiwin32==219; sys_platform == "win32"` in the `requirements.in` instead, and remove the `extras_require`, I get:
```
dummy-test==1.0.0
pypiwin32==219 ; sys_platform == "win32"
```
and if I change the condition to `sys_platform != "win32" (still on windows)`:
```
dummy-test==1.0.0
pypiwin32==219 ; sys_platform != "win32"
```

Also, as you would expect now, if the top-level package has dependencies too, they will get in the `requirements.txt` too. In other words, in the examples above where we put the marker in the `requirements.in`, change `pypiwin32==219` by `requests`, and you'll get `requests`' dependencies on both platform. The environment markers in the `requirements.in` are _really_ not taken into consideration, and merely copy-pasted to the `requirements.txt`.

Result: We'll need to standardise the behaviour here and parse/compute the markers in the input file.

**Comment by vphilippon** [comment]
I digged a bit more into this: `pip-tools` does no handling whatsoever to exclude "unsupported requirements". It just happens that setuptools takes care of the marker evaluation before returning the requirements, which isn't done for plain requirements.in file. we have to do that ourselves.

I could filter out "unsupported requirements", but then I have to make a choice on whether to keep or remove the feature that adds the requirements with their markers in the requirements.txt.

**Comment by vphilippon** [comment]
Dealth with by #647
