### ISSUE TITLE
pip-sync 1.10: TypeError: '<' not supported between instances of 'InstallRequirement' and 'InstallRequirement'

### ISSUE THREAD

**Issue by jdufresne** [jazzband/pip-tools#569]
Describe the issue briefly here.

After upgrading to 1.10, `pip-sync` fails with the error:

```
$ venv/bin/pip-sync dev-requirements.txt
Traceback (most recent call last):
  File "venv/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "venv/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "venv/lib64/python3.6/site-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "venv/lib64/python3.6/site-packages/piptools/sync.py", line 159, in sync
    for ireq in sorted(to_install):
TypeError: '<' not supported between instances of 'InstallRequirement' and 'InstallRequirement'
```

##### Environment Versions

1. OS Type: Linux
1. Python version: `$ python -V`: Python 3.6.2
1. pip version:  `$ pip --version`: pip 9.0.1 from venv/lib64/python3.6/site-packages (python 3.6)
1. pip-tools version: `$ pip-compile --version`: pip-compile, version 1.10.0

##### Steps to replicate

```
$ cat requirements.in
Django
```

```
$ cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --generate-hashes --output-file requirements.txt requirements.in
#
django==1.11.5 \
    --hash=sha256:1836878162dfdf865492bacfdff0321e4ee8f1e7d51d93192546000b54982b29 \
    --hash=sha256:89162f70a74aac62a53f975128faba6099a7ef2c9d8140a41ae9d6210bda05cd
pytz==2017.2 \
    --hash=sha256:d1d6729c85acea5423671382868627129432fba9a89ecbb248d8d1c7a9f01c67 \
    --hash=sha256:f5c056e8f62d45ba8215e5cb8f50dfccb198b4b9fbea8500674f3443e4689589 \
    # via django
```

To reproduce:

```
$ rm -rf venv
$ python3 -m venv venv
$ venv/bin/pip install --upgrade pip setuptools
$ venv/bin/pip install pip-tools
$ venv/bin/pip-sync requirements.txt
Traceback (most recent call last):
  File "venv/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "venv/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "venv/lib64/python3.6/site-packages/piptools/scripts/sync.py", line 74, in cli
    install_flags=install_flags))
  File "venv/lib64/python3.6/site-packages/piptools/sync.py", line 159, in sync
    for ireq in sorted(to_install):
TypeError: '<' not supported between instances of 'InstallRequirement' and 'InstallRequirement'
```
##### Expected result

Packages installed without error.

##### Actual result

Receive unhandled exception:

`TypeError: '<' not supported between instances of 'InstallRequirement' and 'InstallRequirement'`

**Comment by jonatkinson** [comment]
We can replicate this on Amazon Linux 2016.03 running on Python 3.4.4, pip-tools 1.10.0.

**Comment by leonsmith** [comment]
Seem to be related to #566 there is also a note around the code in that section that regarding equality

```
# NOTE: We need to compare RequirementSummary objects, since
# InstallRequirement does not define equality
```

**Comment by vphilippon** [comment]
The error occurs only in Python 3+.
I do not think this is related to #566. The error occurs in sync.py, the traceback is pretty explicit here.
InstallRequirement does not define `<`, so it fails.
I seems like Py2 has no issue with that and falls back to a default '<', while Py3 raises a TypeError instead (I don't know a lot about Py2 vs Py3).
Its pretty bad the tests did not catch that. I'll try to fix that ASAP.

**Comment by jdufresne** [comment]
> I seems like Py2 has no issue with that and falls back to a default '<', while Py3 raises a TypeError instead (I don't know a lot about Py2 vs Py3).

FYI, This change Python3 comparison behavior is described here: https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons
