### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'specifier'

### ISSUE THREAD

**Issue by elcolie** [jazzband/pip-tools#576]
`AttributeError: 'NoneType' object has no attribute 'specifier'`

##### Environment Versions

1. OS Type
`OSX: 10.12.6`
1. Python version: `$ python -V`
`Python 3.6.2`
1. pip version:  `$ pip --version`
`pip 9.0.1 from /Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages (python 3.6)`
1. pip-tools version: `$ pip-compile --version`
`pip-compile, version 1.10.1`
##### Steps to replicate

1. `pip-compile requirements.in`

##### Expected result
`requirements.txt` has been created

##### Actual result
```
$ pip-compile requirements.in
Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/soken/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/piptools/scripts/compile.py", line 136, in cli
    for ireq in ireqs
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/piptools/scripts/compile.py", line 137, in <dictcomp>
    if is_pinned_requirement(ireq) and key_from_req(ireq.req) not in upgrade_pkgs_key}
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/piptools/utils.py", line 121, in is_pinned_requirement
    if len(ireq.specifier._specs) != 1:
  File "/Users/el/.pyenv/versions/3.6.2/envs/soken/lib/python3.6/site-packages/pip/req/req_install.py", line 287, in specifier
    return self.req.specifier
AttributeError: 'NoneType' object has no attribute 'specifier'
```

`requirements.in`
```bash
# Core
Django
django-environ

# Image
Pillow

# Django REST framework and JSON Web Token Authentication
djangorestframework
djangorestframework-jwt

# Debugging only on Local environment
django-debug-toolbar
django-extensions

# postgres adapter
psycopg2

# Production running
gunicorn
gevent

# Header for API
django-cors-headers

# AWS S3
django-s3-folder-storage
Collectfast

django-reversion
django-model-controller
djangorestframework-recursive
djangorestframework-filters
django-extensions
django-filter
django-mptt
django-choices
django-geoposition
django-import-export
django-logging-json
jaconv
certifi
py-moneyed
django-money
markdown
model_mommy
freezegun
Werkzeug
```

**Comment by vphilippon** [comment]
I don't have access to an OSX machine, but I'm unable to reproduce this on Linux.
One other difference I spotted is that you're using pyenv. I don't know if it could cause any issue here.

Other than that, you can try using the `--rebuild` flag and/or deleting the existing `requirements.txt` if one already exists.

If you want to go further, if you can log or inspect the `ireq` object in piptools/utils.py, line 121, knowing which requirements is in cause would help.

**Comment by elcolie** [comment]
I can reproduce this on my GNU/Linux Debian Stretch
Seems like this issue may comes from `pyenv` itself

```bash
$ pyenv --version
pyenv 1.1.3-5-g7dae197
(soken-web) sarit@sniper:~/Code/soken/soken-web$ uname -a
Linux server 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
(soken-web) sarit@sniper:~/Code/soken/soken-web$ python -V
Python 3.6.2
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip --version
pip 9.0.1 from /home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages (python 3.6)
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip-compile --version
pip-compile, version 1.10.1
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip-compile 
Traceback (most recent call last):
  File "/home/sarit/.pyenv/versions/soken-web/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/scripts/compile.py", line 136, in cli
    for ireq in ireqs
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/scripts/compile.py", line 137, in <dictcomp>
    if is_pinned_requirement(ireq) and key_from_req(ireq.req) not in upgrade_pkgs_key}
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/utils.py", line 121, in is_pinned_requirement
    if len(ireq.specifier._specs) != 1:
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/pip/req/req_install.py", line 287, in specifier
    return self.req.specifier
AttributeError: 'NoneType' object has no attribute 'specifier'
```

**Comment by elcolie** [comment]
Remove `requirements.txt` fix this. Thank you very much.
