### ISSUE TITLE
Unable to pip-compile with `matplotlib`

### ISSUE THREAD

**Issue by elcolie** [jazzband/pip-tools#581]
##### Environment Versions

1. OS Type: `GNU/Linux Debian Stretch`
1. Python version: `3.6.3`
1. pip version:  `pip 9.0.1 from /home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages (python 3.6)`

1. pip-tools version: `pip-compile, version 1.10.1`
1. `requirements.in`
```bash
numpy
matplotlib
```

##### Steps to replicate

1. `pip-compile requirements.in`

##### Expected result

`requirements.txt`generated

##### Actual result

```bash
$ pip-compile requirements.in 
Traceback (most recent call last):
  File "/home/sarit/.pyenv/versions/lazy/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/piptools/resolver.py", line 198, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/piptools/resolver.py", line 284, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 170, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/sarit/.pyenv/versions/3.6.3/envs/lazy/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmppkcqb26pbuild/subprocess32/
```

If `requirements.in` has only `numpy`. It works. It generates `requirements.txt` without any errors.

**Comment by lawrlee** [comment]
I'm having similar problems with `seaborn`, which includes `matplotlib` as a dependency

```
root@c40c070a2024:/app# echo "seaborn" > test.in
root@c40c070a2024:/app# pip-compile test.in
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 198, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/piptools/resolver.py", line 284, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 170, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpif8gdc0fbuild/subprocess32/
root@c40c070a2024:/app# python --version
Python 3.6.3
```

**Comment by hassy-6thsense** [comment]
I also have the same problem with matplotlib.

The problem seems to be occurring when trying to install `subprocess32`.
`matplotlib` depends on `subprocess32` only in **Python 2.7**.
However, here we are executing in **Python 3.4**, but because we are trying to get `subprocess32`, we have failed.
Maybe, `pip-tools` always refers to package dependencies with **Python 2.7**.

#### On CentOS
* OS Type: CentOS 7.4.1708 x86_64
* Python version: 3.4.5 (python34-3.4.5-4.el7.x86_64)
* pip version: pip 9.0.1 from /tmp/piptools-test/venv/lib64/python3.4/site-packages (python 3.4)
* pip-tools version: pip-compile, version 1.10.1


#### On Ubuntu
* OS Type: Ubuntu 16.04.3 LTS amd64
* Python version: 3.5.1 (python3-3.5.1-3)
* pip version: pip 9.0.1 from /tmp/piptools-test/venv/lib/python3.5/site-packages (python 3.5)
* pip-tools version: pip-compile, version 1.10.1


- requirements.in
  ```
  matplotlib
  ```

- Results (on CentOS)
  ```bash
  % pip-compile --dry-run --rebuild --verbose
  Using indexes:
    https://pypi.python.org/simple

                            ROUND 1
  Current constraints:
    matplotlib

  Finding the best candidates:
    found candidate matplotlib==2.1.0 (constraint was <any>)

  Finding secondary dependencies:
    matplotlib==2.1.0 not in cache, need to check index
    matplotlib==2.1.0         requires backports.functools-lru-cache, cycler>=0.10, numpy>=1.7.1, pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1, python-dateutil>=2.0, pytz, six>=1.10, subprocess32

  New dependencies found in this round:
    adding ['backports.functools-lru-cache', '', '[]']
    adding ['cycler', '>=0.10', '[]']
    adding ['numpy', '>=1.7.1', '[]']
    adding ['pyparsing', '!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1', '[]']
    adding ['python-dateutil', '>=2.0', '[]']
    adding ['pytz', '', '[]']
    adding ['six', '>=1.10', '[]']
    adding ['subprocess32', '', '[]']
  Removed dependencies in this round:
  Unsafe dependencies in this round:
  ------------------------------------------------------------
  Result of round 1: not stable

                            ROUND 2
  Current constraints:
    backports.functools-lru-cache
    cycler>=0.10
    matplotlib
    numpy>=1.7.1
    pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
    python-dateutil>=2.0
    pytz
    six>=1.10
    subprocess32

  Finding the best candidates:
    found candidate backports.functools-lru-cache==1.4 (constraint was <any>)
    found candidate cycler==0.10.0 (constraint was >=0.10)
    found candidate matplotlib==2.1.0 (constraint was <any>)
    found candidate numpy==1.13.3 (constraint was >=1.7.1)
    found candidate pyparsing==2.2.0 (constraint was >=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6)
    found candidate python-dateutil==2.6.1 (constraint was >=2.0)
    found candidate pytz==2017.2 (constraint was <any>)
    found candidate six==1.11.0 (constraint was >=1.10)
    found candidate subprocess32==3.2.7 (constraint was <any>)

  Finding secondary dependencies:
    subprocess32==3.2.7 not in cache, need to check index
  Traceback (most recent call last):
    File "/tmp/piptools-test/venv/bin/pip-compile", line 11, in <module>
      sys.exit(cli())
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/click/core.py", line 722, in __call__
      return self.main(*args, **kwargs)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/click/core.py", line 697, in main
      rv = self.invoke(ctx)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/click/core.py", line 895, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/click/core.py", line 535, in invoke
      return callback(*args, **kwargs)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/piptools/scripts/compile.py", line 184, in cli
      results = resolver.resolve(max_rounds=max_rounds)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/piptools/resolver.py", line 101, in resolve
      has_changed, best_matches = self._resolve_one_round()
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/piptools/resolver.py", line 198, in _resolve_one_round
      for dep in self._iter_dependencies(best_match):
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/piptools/resolver.py", line 284, in _iter_dependencies
      dependencies = self.repository.get_dependencies(ireq)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/piptools/repositories/pypi.py", line 170, in get_dependencies
      self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/pip/req/req_set.py", line 634, in _prepare_file
      abstract_dist.prep_for_dist()
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
      self.req_to_install.run_egg_info()
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/pip/req/req_install.py", line 439, in run_egg_info
      command_desc='python setup.py egg_info')
    File "/tmp/piptools-test/venv/lib64/python3.4/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
      % (command_desc, proc.returncode, cwd))
  pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp_eh5egjsbuild/subprocess32/
  ```

**Comment by vphilippon** [comment]
Thanks for the reports. That's a known issue, fixed on master (try it out).

We're eagerly waiting for the ability to make a 1.10.2 bugfix release (see https://github.com/jazzband/pip-tools/issues/531, pypi upload deactivated for Jazzband projects).

Sorry for the wait, it's in the hands of Jazzband's admin/roadies at the moment.

**Comment by bnaul** [comment]
I tried this on master with Python 3.6.3 and am seeing the same issue:
```
➜  /tmp pip install -e git+https://github.com/jazzband/pip-tools.git#egg=pip-tools
Obtaining pip-tools from git+https://github.com/jazzband/pip-tools.git#egg=pip-tools
  Updating ./src/pip-tools clone
Requirement already satisfied: click>=6 in /Users/brettnaul/miniconda3/lib/python3.6/site-packages (from pip-tools)
Requirement already satisfied: first in /Users/brettnaul/miniconda3/lib/python3.6/site-packages (from pip-tools)
Requirement already satisfied: six in /Users/brettnaul/miniconda3/lib/python3.6/site-packages (from pip-tools)
Requirement already satisfied: setuptools in /Users/brettnaul/miniconda3/lib/python3.6/site-packages (from pip-tools)
Installing collected packages: pip-tools
  Running setup.py develop for pip-tools
Successfully installed pip-tools
➜  /tmp echo "matplotlib" > requirements.in
➜  /tmp pip-compile
Traceback (most recent call last):
  File "/Users/brettnaul/miniconda3/bin/pip-compile", line 11, in <module>
    load_entry_point('pip-tools', 'console_scripts', 'pip-compile')()
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/private/tmp/src/pip-tools/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/private/tmp/src/pip-tools/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/private/tmp/src/pip-tools/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/private/tmp/src/pip-tools/piptools/resolver.py", line 285, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/private/tmp/src/pip-tools/piptools/repositories/pypi.py", line 152, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/brettnaul/miniconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/kb/5p7n5tds71v3rsmjtjqm2w4r0000gn/T/tmppd0qfxz1build/subprocess32/
```

**Comment by vphilippon** [comment]
Thanks for the report.

Could you try clearing your cache with `pip-compile --rebuild`?

If it doesn't work, give me the `--verbose` output.

**Comment by bnaul** [comment]
Ah looks like it works with the rebuilt cache, thanks!

**Comment by vphilippon** [comment]
👍
