### ISSUE TITLE
How to compile and install frm URL?

### ISSUE THREAD

**Issue by elcolie** [jazzband/pip-tools#593]
I want to let pip-compile reserve my URL after each `pip-compile`

##### Environment Versions

1. OSX 10.13.1
1. 3.6.3
1. pip 9.0.1 from /Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages (python 3.6)
1. pip-compile, version 1.10.1

I want to install `pip install https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip`
But to follow the `pip-tools` I want to keep it in the `requirements.in` since my project is on going and many libraries will be added to the file

##### Steps to replicate

1. Put `-e git+https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip` to the `requirements.in`
2. pip-compile requirements.in

##### Expected result

requirements.txt has `https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip`

##### Actual result

```bash
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/poink/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/scripts/compile.py", line 176, in cli
    src_file, finder=repository.finder, session=repository.session, options=pip_options))
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_file.py", line 168, in process_line
    wheel_cache=wheel_cache
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_install.py", line 144, in from_editable
    editable_req, default_vcs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_install.py", line 1197, in parse_editable
    "Could not detect requirement name, please specify one with #egg="
pip.exceptions.InstallationError: Could not detect requirement name, please specify one with #egg=
```

Is it possible to achieve my goal?
If so. Am I miss something here?

**Comment by vphilippon** [comment]
You simply missed a part of the exception message:
> Could not detect requirement name, please specify one with #egg=

So, at the end of your url, add `#egg=django`.

**Comment by elcolie** [comment]
I have put the live my `requirements.in`
`-e git+https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip#egg=django`

Error is
```bash
remote: Not Found
fatal: repository 'https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip/' not found
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/poink/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/scripts/compile.py", line 184, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/resolver.py", line 198, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/resolver.py", line 272, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 170, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_set.py", line 516, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/req/req_install.py", line 586, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/vcs/git.py", line 142, in obtain
    self.run_command(['clone', '-q', url, dest])
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/vcs/__init__.py", line 325, in run_command
    spinner)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "git clone -q https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip /var/folders/h5/lj3c5_050j3_yjd77zqxcn7r0000gp/T/tmp1ay6spspsource/django" failed with error code 128 in None
```

`pip-compile` add `slash` at the end of the `url`. Any ideas?

**Comment by vphilippon** [comment]
Well, first, my bad, I was confused by the last part of the url. The `#egg=` part should be the name of the package, so in this case: `#egg=django-geoposition-django`.

And by taking a closer look, I realized you're not using a VCS url, you're directly using a zip/tar archive which isn't yet supported.

So you workaround at the moment would be to point so a branch/commit of your repo instead.
Poke me again if you need any clarifications :).

**Comment by elcolie** [comment]
It's mean I have to manually put line `https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip` to the `requirements.txt` everytime myself isn't it?

**Comment by vphilippon** [comment]
I've looked at the linked issue, and I see why you want to do this. In your case, I might have a better alternative for your.

The best alternative I can give you is that you could download the archive and use the `--find-links` option, if you're going to use that precise archive for a while.
If I've looked at this properly, you would put `django-geoposition>=3.0.1` in you requirements.in, and the do `pip-compile --find-links /path/to/dir-containing-the-archive`.

That's the best workaround I can think of right now, until `pip-tools` supports tar/zip archive urls directly.
I hope this helps.

**Comment by elcolie** [comment]
Thank you very much.
