### ISSUE TITLE
[Windows/Python 3] -e `<vcs-url>` causes tempfile leak.

### ISSUE THREAD

**Issue by vphilippon** [jazzband/pip-tools#616]
Putting `-e <vcs-url>` in a requirements.in will cause `pip-compile` to fail to cleanup its temporary files.
This does not cause the operation to fail, but will leave unwanted files in the temp directory and print a stacktrace.

This happens since 1.10.0. This does not happen on 1.9.0.

##### Environment Versions

1. OS Type: Windows
1. Python version: `3.6.3`
1. pip version:  `9.0.1`
1. pip-tools version: from `1.10.0` to `1.10.2`

##### Steps to replicate

1. `echo "-e git+https://github.com/django/django.git@1.11.1#egg=django" > requirements.in`
1. `pip-compile`

##### Expected result
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#

-e git+https://github.com/django/django.git@1.11.1#egg=django
pytz==2017.3
```
and no leaking tempfiles.

##### Actual result
```
Exception ignored in: <finalize object at 0x41f5bb8; dead>
Traceback (most recent call last):
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\vphilippon\projects\pip-tools\venv\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'F:\\tmp\\tmpw8d_ff4usource\\django\\.git\\objects\\pack\\pack-5a811c728beb67cf071486bbbaac198b5c2b66b7.idx'
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#

-e git+https://github.com/django/django.git@1.11.1#egg=django
pytz==2017.3
```
and leaking tempfiles. But the compile still succeed.

**Comment by techalchemy** [comment]
FYI there is nothing you can do about this except maybe grab our temporarydirectory handler and its cascading permissions calls which try to assign permissions but fail with a warning instead of an error... this relates specifically to git index permission assignment on windows in nested subprocess trees.
