### ISSUE TITLE
pip-tools is not compatible with pip >= 10.0.0

### ISSUE THREAD

**Issue by cyrilleverrier** [jazzband/pip-tools#648]
pip-tools is not compatible with pip >= 10.0.0

##### Environment Versions

1. OS Type: `Linux/Ubuntu`
1. Python version: `Python 2.7.12`
1. pip version:  `$ pip 10.0.0b2`
1. pip-tools version: `$ pip-compile, version 1.11.0`

##### Steps to replicate

1. `. /usr/share/virtualenvwrapper/virtualenvwrapper.sh`
2. `mkvirtualenv -p /usr/bin/python2 test-pip-tools
3.` (test-pip-tools) pip install -U pip ``
4. `(test-pip-tools) pip install pip-tools`
5. `echo Flask > requirements.in`
5. `(test-pip-tools) pip-compile requirements.in`

##### Expected result
`six` python package is installed

##### Actual result

```
Traceback (most recent call last):
  File "/home/xxx/.virtualenvs/test-pip-tools/bin/pip-compile", line 7, in <module>
    from piptools.scripts.compile import cli
  File "/home/xxx/.virtualenvs/test-pip-tools/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from pip.req import InstallRequirement, parse_requirements
ImportError: No module named req
```

##### Workaround

1. `(test-pip-tools) pip install -U pip==9.0.3`

**Comment by vphilippon** [comment]
Hi @cyrilleverrier, thanks for taking the time to report.

We've got that covered in https://github.com/jazzband/pip-tools/issues/580 and the solution is current merged in master, you can test it out if you want. It'll be released in `pip-tools` 2.0.0 soon™️. I've got a changes I'd like to get in first, but I don't intend to delay it too much.

(Keeping open for now, as I expect others to hit this.)

**Comment by cyrilleverrier** [comment]
Thanks @vphilippon. Looking forward to test it.

**Comment by leonsmith** [comment]
Is there an expected release date for 2.0?

I'm just trying to triage updating lots of projects to pin the pip version as all our builds have just started failing :(

**Comment by vphilippon** [comment]
Done:
https://pypi.org/project/pip-tools/2.0.0/

**Comment by vphilippon** [comment]
FYI 2.0.1 coming up shortly: There was missing package_data in there, which will make pip-compile fail with an error like:
```
IOError: Could not find a suitable TLS CA certificate bundle, invalid path: <path_to_virtualenv>\lib\site-packages\piptools\_vendored\pip\_vendor\certifi\cacert.pem
```

**Comment by leonsmith** [comment]
wow awesome! thats saved me a huge headache, really appreciated!
