### ISSUE TITLE
pip-compile fails when using -f in requirements.in

### ISSUE THREAD

**Issue by graingert** [jazzband/pip-tools#66]
``` pytb
Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/test/bin/pip-compile", line 150, in <module>
    main()
  File "/home/graingert/.virtualenvs/test/bin/pip-compile", line 141, in main
    compile_specs(src_files, dry_run=args.dry_run)
  File "/home/graingert/.virtualenvs/test/bin/pip-compile", line 81, in compile_specs
    top_level_specs = list(collect_source_specs(source_files))
  File "/home/graingert/.virtualenvs/test/bin/pip-compile", line 75, in collect_source_specs
    for spec in walk_specfile(filename):
  File "/home/graingert/.virtualenvs/test/bin/pip-compile", line 66, in walk_specfile
    spec = Spec.from_line(line, source='{0}:{1}'.format(filename, lineno))
  File "/home/graingert/.virtualenvs/test/local/lib/python2.7/site-packages/piptools/datastructures.py", line 67, in from_line
    req = Requirement.parse(line)
  File "/home/graingert/.virtualenvs/test/local/lib/python2.7/site-packages/pkg_resources.py", line 2914, in parse
    reqs = list(parse_requirements(s))
  File "/home/graingert/.virtualenvs/test/local/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/graingert/.virtualenvs/test/local/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', '-f http://example.com/pypi/', 'at', ' http://example.com/pypi/')
```

**Comment by blueyed** [comment]
For reference: #93 is also about this.
