### ISSUE TITLE
pip-tools does not seem to support relative file: uris

### ISSUE THREAD

**Issue by ztane** [jazzband/pip-tools#681]
pip-tools doesn't support relative file: uris for `-e`. Sometimes a file: uri is required so that the distribution name can be provided. Unfortunately, it is not possible to use relative file: uris - pip-tools expects the path to be always absolute and if the relative uri contains a directory part,  both pip-compile and pip-tools will first change directory to the given, and then try to load `setup.py` - still using the relative URI.

##### Environment Versions

1. Linux Ubuntu 18.04
1. Python version: 3.6.5
1. pip version:  18.0
1. pip-tools version: 2.0.2

##### Steps to replicate

1. have a `requirements.in` or `requirements.txt` with `-e file:ham/bacon#egg=spam` (provided that there is a package with setup.py in `ham/bacon` with `setup.py` and name `spam`)
2. run `pip-sync` or `pip-compile`

##### Expected result

It would work properly

##### Actual result

```
Traceback (most recent call last):
  File ".../venv/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File ".../venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../venv/lib/python3.6/site-packages/piptools/scripts/compile.py", line 187, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File ".../venv/lib/python3.6/site-packages/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File ".../venv/lib/python3.6/site-packages/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File ".../venv/lib/python3.6/site-packages/piptools/resolver.py", line 273, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File ".../venv/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 146, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File ".../venv/lib/python3.6/site-packages/piptools/_vendored/pip/req/req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File ".../venv/lib/python3.6/site-packages/piptools/_vendored/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File ".../venv/lib/python3.6/site-packages/piptools/_vendored/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File ".../venv/lib/python3.6/site-packages/piptools/_vendored/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd)) 
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in ham/bacon` in `piptools/_vendored/pip/utils/__init__.py
```

I dug into the code, and the error message itself is bogus; it is just that an interpreter is spawned that tries to read the file `ham/bacon/setup.py` when the working directory is `ham/bacon` already.

Apparently this was fixed in pip 10 already; pip 9 still crashes. the vendored pip doesn't have the fixes.

**Comment by vphilippon** [comment]
Can you give it a try with `pip>=10` and `pip-tools==3.0.0rc1`? In that pre-release version, we unvendored `pip`, so if all it needed was a fix from `pip 10`, it should work now.

**Comment by ztane** [comment]
Ooh shiny @vphilippon it seems to work. Awesome!

**Comment by vphilippon** [comment]
Allright, good to hear. I aim to release 3.0.0 officially next Monday (2018-09-24).

**Comment by vphilippon** [comment]
@ztane pip-tools 3.0.0 is officially out. Cheers!
