### ISSUE TITLE
piptools installs incompatible versions where pip doesn't

### ISSUE THREAD

**Issue by jaraco** [jazzband/pip-tools#683]
Describe the issue briefly here.

##### Environment Versions

1. macOS 10.13.6
1. Python version: `3.7.0`
1. pip version:  `18.0`
1. pip-tools version: `$ pip-compile --version`

##### Steps to replicate

Create `.in` file

```
$ cat requirements-dev.in
flake8
```

Run pip tools on it.

```
$ rwt pip-tools -- -m piptools compile --output-file requirements-dev.txt requirements-dev.in --upgrade
Collecting pip-tools
  Using cached https://files.pythonhosted.org/packages/4c/69/4f33fea6c50ff873b7905abc404d8c26aab2accf8c099d67a35aebc09871/pip_tools-2.0.2-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/71/12/1b24a85f543658804027de982f7e5cb80543ea33ec396c887c099c75274c/first-2.0.1-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Installing collected packages: six, first, click, pip-tools
Successfully installed click-6.7 first-2.0.1 pip-tools-2.0.2 six-1.11.0
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements-dev.txt requirements-dev.in
#
flake8==3.5.0
mccabe==0.6.1             # via flake8
pycodestyle==2.4.0        # via flake8
pyflakes==1.6.0           # via flake8
```

Note `pycodestyle==2.4.0` is incompatible with `flake8==3.5.0`.

```
$ rwt -r requirements-dev.txt -- -c "import pkg_resources; pkg_resources.require('flake8')"
Collecting flake8==3.5.0 (from -r requirements-dev.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting mccabe==0.6.1 (from -r requirements-dev.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle==2.4.0 (from -r requirements-dev.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/e5/c6/ce130213489969aa58610042dff1d908c25c731c9575af6935c2dfad03aa/pycodestyle-2.4.0-py2.py3-none-any.whl
Collecting pyflakes==1.6.0 (from -r requirements-dev.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/d7/40/733bcc64da3161ae4122c11e88269f276358ca29335468005cb0ee538665/pyflakes-1.6.0-py2.py3-none-any.whl
Installing collected packages: mccabe, pyflakes, pycodestyle, flake8
flake8 3.5.0 has requirement pycodestyle<2.4.0,>=2.0.0, but you'll have pycodestyle 2.4.0 which is incompatible.
Successfully installed flake8-3.5.0 mccabe-0.6.1 pycodestyle-2.4.0 pyflakes-1.6.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pycodestyle 2.4.0 (/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-3w9_r0ta), Requirement.parse('pycodestyle<2.4.0,>=2.0.0'), {'flake8'})
```

##### Expected result

If you instead `pip install flake8`, you get pycodestyle 2.3.x.

```
$ ~/.envs/rwt/bin/rwt flake8
Collecting flake8
  Using cached https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8)
  Using cached https://files.pythonhosted.org/packages/d7/40/733bcc64da3161ae4122c11e88269f276358ca29335468005cb0ee538665/pyflakes-1.6.0-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8)
  Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
Successfully installed flake8-3.5.0 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.6.0
```

pip-compile should produce a comparable result.

**Comment by suutari-ai** [comment]
Can you run the pip-compile command with `-v` flag added and post the output here?

**Comment by jaraco** [comment]
```
draft $ pip-compile --output-file requirements.txt requirements.in -vv
Using indexes:
  https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  flake8

Finding the best candidates:
  found candidate flake8==3.5.0 (constraint was <any>)

Finding secondary dependencies:
  flake8==3.5.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<1.7.0,>=1.5.0

New dependencies found in this round:
  adding ['mccabe', '<0.7.0,>=0.6.0', '[]']
  adding ['pycodestyle', '<2.5.0,>=2.4.0', '[]']
  adding ['pyflakes', '<1.7.0,>=1.5.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  flake8
  mccabe<0.7.0,>=0.6.0
  pycodestyle<2.5.0,>=2.4.0
  pyflakes<1.7.0,>=1.5.0

Finding the best candidates:
  found candidate flake8==3.5.0 (constraint was <any>)
  found candidate mccabe==0.6.1 (constraint was >=0.6.0,<0.7.0)
  found candidate pycodestyle==2.4.0 (constraint was >=2.4.0,<2.5.0)
  found candidate pyflakes==1.6.0 (constraint was >=1.5.0,<1.7.0)

Finding secondary dependencies:
  pycodestyle==2.4.0        requires -
  flake8==3.5.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<1.7.0,>=1.5.0
  pyflakes==1.6.0           requires -
  mccabe==0.6.1             requires -
------------------------------------------------------------
Result of round 2: stable, done

#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
flake8==3.5.0
mccabe==0.6.1             # via flake8
pycodestyle==2.4.0        # via flake8
pyflakes==1.6.0           # via flake8
```

**Comment by jaraco** [comment]
Other members on my team can't replicate this issue. It seems to be unique to my environment.

I suspect there's something cached on my system.

**Comment by suutari** [comment]
The output shows that your pip-compile has somehow cached the
requirements of flake8 as `mccabe<0.7.0,>=0.6.0,
pycodestyle<2.5.0,>=2.4.0, pyflakes<1.7.0,>=1.5.0`, but looking into
to the released packages in PyPI the pycodestyle requirement is there
`<2.4.0`.

I think the relevant change to flake8 requirements happened in
https://gitlab.com/pycqa/flake8/commit/0273ca561f0ad03adff41ce5d95a1ec31b10fe5a

So maybe you have tried to add flake8 as Git URL to your
requirements.in and then pip-tools cached the development
requirements? Check the contents of
`~/.cache/pip-tools/depcache-py3.7.json` to verify this. If this is
the case, then removing that file should resolve your issue.

**Comment by jaraco** [comment]
I didn't have a ~/.cache/pip-tools, but I did find the dir:

```
>>> import piptools.locations as loc
>>> loc.CACHE_DIR
'/Users/jaraco/Library/Caches/pip-tools'
```

And indeed that location has the newer deps cached:

```
$ cat ~/Library/Caches/pip-tools/depcache-py3.7.json | jq '.dependencies.flake8'
{
  "3.5.0": [
    "mccabe<0.7.0,>=0.6.0",
    "pycodestyle<2.5.0,>=2.4.0",
    "pyflakes<1.7.0,>=1.5.0"
  ]
}
```

Yet still pip-compile is getting the incompatible version:

```
draft $ rm -rf ~/Library/Caches/pip-compile/*
draft $ python -m venv clean
draft $ clean/bin/pip install pip-tools
Collecting pip-tools
  Using cached https://files.pythonhosted.org/packages/4c/69/4f33fea6c50ff873b7905abc404d8c26aab2accf8c099d67a35aebc09871/pip_tools-2.0.2-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/71/12/1b24a85f543658804027de982f7e5cb80543ea33ec396c887c099c75274c/first-2.0.1-py2.py3-none-any.whl
Installing collected packages: six, click, first, pip-tools
Successfully installed click-6.7 first-2.0.1 pip-tools-2.0.2 six-1.11.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
draft $ clean/bin/pip-compile --output-file requirements.txt requirements.in -vv
Using indexes:
  https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  flake8

Finding the best candidates:
  found candidate flake8==3.5.0 (constraint was <any>)

Finding secondary dependencies:
  flake8==3.5.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<1.7.0,>=1.5.0

New dependencies found in this round:
  adding ['mccabe', '<0.7.0,>=0.6.0', '[]']
  adding ['pycodestyle', '<2.5.0,>=2.4.0', '[]']
  adding ['pyflakes', '<1.7.0,>=1.5.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  flake8
  mccabe<0.7.0,>=0.6.0
  pycodestyle<2.5.0,>=2.4.0
  pyflakes<1.7.0,>=1.5.0

Finding the best candidates:
  found candidate flake8==3.5.0 (constraint was <any>)
  found candidate mccabe==0.6.1 (constraint was >=0.6.0,<0.7.0)
  found candidate pycodestyle==2.4.0 (constraint was >=2.4.0,<2.5.0)
  found candidate pyflakes==1.6.0 (constraint was >=1.5.0,<1.7.0)

Finding secondary dependencies:
  flake8==3.5.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<1.7.0,>=1.5.0
  mccabe==0.6.1             requires -
  pyflakes==1.6.0           requires -
  pycodestyle==2.4.0        requires -
------------------------------------------------------------
Result of round 2: stable, done

#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
flake8==3.5.0
mccabe==0.6.1             # via flake8
pycodestyle==2.4.0        # via flake8
pyflakes==1.6.0           # via flake8
```

I'll see if I can break into pip-tools to learn more.

**Comment by chaoflow** [comment]
@jaraco You seem to cat a different folder than the one you are removing: ``cat ~/Library/Caches/pip-tools/...`` vs ``rm -rf ~/Library/Caches/pip-compile/*``

**Comment by vphilippon** [comment]
> Should there be a command-line option to bypass the cache?

There's the `--rebuild` option that would address that here.

> Would hashes have helped here?

The hashes aren't used as part of the cache key, so it wouldn't have helped in this case. But maybe that's exactly that's something we'd want to change. There's your case here, but also the case where sdist and wheel distributions for a same package end-up giving different dependencies (thank arbitrary code in `setup.py`), or if someone reuploads/overwritte a package, changing the dependencies. That's worth giving this some thought.

> So I've determined what caused the cache to get the wrong value. In my system site-packages, I have an untagged post release of 3.5.0, so when I run pip compile from my main Python environment, I get dependencies resolved as part of that environment (and cached):

You mean that `pip-compile` will use the package installed in the current environment as part of the "source" it can check? That rings a bell (I feel it was something you reported before @suutari, no?). Can I ask how you installed that untagged post release of 3.5.0 of flake8 exactly (i.e. with `pip install -e`, or non-editable with a file uri, or something else)?
This is worth some investigation, but I think we should test that again with `pip-tools 3.0.0rc1` (or `3.0.0`, I should get it officially out soon :tm:), which unvendors `pip`.

**Comment by jaraco** [comment]
> Can I ask how you installed that untagged post release of 3.5.0 of flake8 exactly 

I don't recall, but since I don't have a local checkout of flake8, I almost certainly did `pip install git+https://github.com/PyCQA/flake8` possibly but unlikely `@somerev`.

**Comment by atugushev** [comment]
This should be fixed with the new backtracking resolver.
