### ISSUE TITLE
distutils.core.setup was never called

### ISSUE THREAD

**Issue by jaraco** [jazzband/pip-tools#684]
Attempting to run pip-compile on a project results in `RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?`

##### Environment Versions

1. macOS
1. Python version: 3.7.0
1. pip version:  10.0.1
1. pip-tools version: 2.0.2

##### Steps to replicate

```
draft $ cat > setup.py
__name__ == '__main__' and __import__('setuptools').setup()
draft $ python -m piptools compile
```

##### Expected result

pip-tools should produce the pinned requirements.txt for the project, such as it does for a simpler setup.py.

```
draft $ cat > setup.py
__import__('setuptools').setup()
draft $ python -m piptools compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt setup.py
#
```

##### Actual result

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/piptools/__main__.py", line 16, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/piptools/scripts/compile.py", line 166, in cli
    dist = run_setup(src_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 227, in run_setup
    script_name)
RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?
```

The issue is probably that other installers will invoke `setup.py` as a script with `__name__` set to `"__main__"`, but apparently that's not the case when pip-tools invokes it.

Many projects guard on `__name__`. I do it as a [matter of course](https://github.com/jaraco/skeleton/blob/f8a537f300727a87c1a4a663a5df8b6e05e1020d/setup.py#L63-L64) in my projects. I do that so that tools like flake8 and doctest runners can import and inspect the module without executing it. 

Obviously, you can't depend on everyone guarding on `__name__`, but you should be able to set it when loading the module so the module loads in the same context as it would if someone were to run it.

**Comment by jaraco** [comment]
At the point where `setup.py` is executed, `__name__ == 'builtins'`.

**Comment by jaraco** [comment]
Change setup.py to `__name__ in ['__main__', 'builtins'] and __import__('setuptools').setup()` works around the issue.

**Comment by jaraco** [comment]
To support Python 2 invocation of pip-compile, you need `__name in ['__main__', 'builtins', '__builtin__']`.

**Comment by atugushev** [comment]
Hello @jaraco,

I'll close this since you've found a workaround. Please let us know if you have any other issues. Thanks for the issue!
