### ISSUE TITLE
In setuptools_markdown: AttributeError: 'NoneType' object has no attribute 'f_code'

### ISSUE THREAD

**Issue by bzamecnik** [jazzband/pip-tools#695]
When I run `pip-compile` in project with `setuptools_markdown` it fails with the error below. When I comment it out in `setup.py`, it works.

```
#setup_requires=['setuptools-markdown'],
#long_description_markdown_filename='README.md',
```

##### Environment Versions

1. OS Type: Ubuntu 16.04
1. Python version: `$ python -V` 2.7.12
1. pip version:  `$ pip --version`: 18.0
1. pip-tools version: `$ pip-compile --version`: 3.1.0

##### Steps to replicate

```bash
git clone https://github.com/rossumai/nvgpu.git
cd nvgpu/
pip-compile
```

##### Expected result

```
No handlers could be found for logger "pip._internal.req.req_install"
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt setup.py
#
--extra-index-url https://***:***@pypi.rossum.ai/simple/

aniso8601==4.0.1          # via flask-restful
ansi2html==1.5.2
arrow==0.12.1
backports.functools-lru-cache==1.5  # via arrow
certifi==2018.10.15       # via requests
chardet==3.0.4            # via requests
click==7.0                # via flask
flask-restful==0.3.6
flask==1.0.2
idna==2.7                 # via requests
itsdangerous==1.1.0       # via flask
jinja2==2.10              # via flask
markupsafe==1.0           # via jinja2
numpy==1.15.3             # via pandas
nvidia-ml-py==375.53
pandas==0.23.4
psutil==5.4.8
python-dateutil==2.7.5    # via arrow, pandas
pytz==2018.7              # via flask-restful, pandas
requests==2.20.0
six==1.11.0               # via ansi2html, flask-restful, python-dateutil
tabulate==0.8.2
termcolor==1.1.0
urllib3==1.24.1           # via requests
werkzeug==0.14.1          # via flask
```

##### Actual result

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/foo/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 170, in cli
    dist = run_setup(src_file)
  File "/usr/lib/python2.7/distutils/core.py", line 218, in run_setup
    exec f.read() in g, l
  File "<string>", line 141, in <module>
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/setuptools/dist.py", line 363, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/setuptools/dist.py", line 519, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/setuptools_markdown.py", line 17, in long_description_markdown_filename
    frame = _get_code_object()
  File "/home/user/.virtualenvs/foo/local/lib/python2.7/site-packages/
.py", line 32, in _get_code_object
    code = frame.f_back.f_code
AttributeError: 'NoneType' object has no attribute 'f_code'
```

**Comment by atugushev** [comment]
Hi @bzamecnik,

It looks like the bug is related to how `setuptools-markdown` deals with `distutils.core.run_setup`.  It's better to open the issue on the setuptools-markdown tracker.

**Comment by atugushev** [comment]
@bzamecnik 

As a workaround use `-e .`, for exmaple:

``` bash
$ echo "-e ." | pip-compile - -qo-
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=- -
#
-e file:///private/tmp/tmp2/nvgpu
aniso8601==8.0.0          # via flask-restful
ansi2html==1.5.2
arrow==0.15.2
certifi==2019.9.11        # via requests
chardet==3.0.4            # via requests
click==7.0                # via flask
flask-restful==0.3.7
flask==1.1.1              # via flask-restful
idna==2.8                 # via requests
itsdangerous==1.1.0       # via flask
jinja2==2.10.1            # via flask
markupsafe==1.1.1         # via jinja2
numpy==1.17.2             # via pandas
pandas==0.25.1
psutil==5.6.3
pynvml==8.0.3
python-dateutil==2.8.0    # via arrow, pandas
pytz==2019.2              # via flask-restful, pandas
requests==2.22.0
six==1.12.0               # via ansi2html, flask-restful, python-dateutil
tabulate==0.8.3
termcolor==1.1.0
urllib3==1.25.5           # via requests
werkzeug==0.16.0          # via flask
```

**Comment by atugushev** [comment]
`setuptools-markdown` is deprecated, see https://github.com/msabramo/setuptools-markdown/pull/20
