### ISSUE TITLE
crash on generic pip sample setup.py

### ISSUE THREAD

**Issue by majuscule** [jazzband/pip-tools#719]
##### Environment Versions

1. `Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
1. `Python 3.6.6`
1. `pip 19.0.1`
1. `pip-compile, version 3.2.0`

##### Steps to replicate

1. wget 'https://raw.githubusercontent.com/pypa/sampleproject/master/setup.py`
2. pip-compile

##### Expected result

`requirements.txt` generated

##### Actual result

```
Traceback (most recent call last):
  File ".../bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File ".../lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python3.6/site-packages/piptools/scripts/compile.py", line 130, in cli
    repository = PyPIRepository(pip_options, session)
  File ".../lib/python3.6/site-packages/piptools/repositories/pypi.py", line 62, in __init__
    process_dependency_links=pip_options.process_dependency_links,
AttributeError: 'Values' object has no attribute 'process_dependency_links'

```

Might have something to do with https://github.com/pypa/pip/issues/5433 ?

**Comment by atugushev** [comment]
Duplicates to #714

**Comment by majuscule** [comment]
whoops, thanks!
