### ISSUE TITLE
InstallationError: Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by y3g0r** [jazzband/pip-tools#738]
When dependency is specified using `-e git+git@git.example.com:MyProject#egg=MyProject` [form](https://pip.pypa.io/en/stable/reference/pip_install/#git) in `.in` file, `download_dir` is not set to None, which makes `python setup.py egg_info` fail, when
[setuptools_scm](https://github.com/pypa/setuptools_scm) is used.
Basically it's the old *partially* fixed issue https://github.com/jazzband/pip-tools/issues/369 with one corner case not being fixed.

##### Environment Versions

1. Ubuntu 18.10
1. Python version: `3.5.6`
1. pip version:  `19.0.2`
1. pip-tools version: `3.4.0`

##### Steps to replicate

1. add requirement: `echo '-e git+git@github.com:jazzband/pip-tools#egg=pip-tools' > requirements.in`
2. try to compile: `pip-compile requirements.in`

##### Expected result

`requirements.txt` file generated (like it would if we used [any other editable git dependency form](https://pip.pypa.io/en/stable/reference/pip_install/#git), i.e. `-e git+http://github.com/jazzband/pip-tools#egg=pip-tools`)

##### Actual result

```
$ pip-compile requirements.in                                                    
Traceback (most recent call last):
  File "/home/yegor/.pyenv/versions/lab1/bin/pip-compile", line 11, in <module>
    load_entry_point('pip-tools', 'console_scripts', 'pip-compile')()
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/scripts/compile.py", line 197, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/resolver.py", line 198, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/resolver.py", line 272, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/repositories/local.py", line 65, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/repositories/pypi.py", line 225, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/yegor/.pyenv/versions/3.5.6/envs/35/envs/lab1/src/pipcompiletest/piptools/repositories/pypi.py", line 191, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/resolve.py", line 226, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 382, in prepare_editable_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 609, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/yegor/.pyenv/versions/35/envs/lab1/lib/python3.5/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpyhkzvnvasource/pip-tools/
```

**Comment by atugushev** [comment]
Hello @y3g0r,

Thank you for the report! Funny to know that pip-tools can't compile itself :) 

/cc @blueyed

**Comment by blueyed** [comment]
> Basically it's the old _partially_ fixed issue #369 with one corner case not being fixed.

Do you have a suggested fix?  (sorry, have not investigated, but it sounds like you know the corner case from debugging already)

**Comment by atugushev** [comment]
I've tried to investigate this issue and find that the main problem is here, see a stacktrace:

```
  /Users/albert/Projects/pip-tools/.venv/bin/pip-compile(11)<module>()
     10     sys.exit(
---> 11         load_entry_point('pip-tools', 'console_scripts', 'pip-compile')()
     12     )

  /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/click/core.py(764)__call__()
    763         """Alias for :meth:`main`."""
--> 764         return self.main(*args, **kwargs)
    765

  /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/click/core.py(717)main()
    716                 with self.make_context(prog_name, args, **extra) as ctx:
--> 717                     rv = self.invoke(ctx)
    718                     if not standalone_mode:

  /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/click/core.py(956)invoke()
    955         if self.callback is not None:
--> 956             return ctx.invoke(self.callback, **ctx.params)
    957

  /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/click/core.py(555)invoke()
    554             with ctx:
--> 555                 return callback(*args, **kwargs)
    556

  /Users/albert/Projects/pip-tools/piptools/scripts/compile.py(197)cli()
    196                             clear_caches=rebuild, allow_unsafe=allow_unsafe)
--> 197         results = resolver.resolve(max_rounds=max_rounds)
    198         if generate_hashes:

  /Users/albert/Projects/pip-tools/piptools/resolver.py(101)resolve()
    100             log.debug(magenta('{:^60}'.format('ROUND {}'.format(current_round))))
--> 101             has_changed, best_matches = self._resolve_one_round()
    102             log.debug('-' * 60)

  /Users/albert/Projects/pip-tools/piptools/resolver.py(198)_resolve_one_round()
    197         for best_match in best_matches:
--> 198             for dep in self._iter_dependencies(best_match):
    199                 if self.allow_unsafe or dep.name not in UNSAFE_PACKAGES:

  /Users/albert/Projects/pip-tools/piptools/resolver.py(272)_iter_dependencies()
    271         if ireq.editable:
--> 272             for dependency in self.repository.get_dependencies(ireq):
    273                 yield dependency

  /Users/albert/Projects/pip-tools/piptools/repositories/local.py(65)get_dependencies()
     64     def get_dependencies(self, ireq):
---> 65         return self.repository.get_dependencies(ireq)
     66

  /Users/albert/Projects/pip-tools/piptools/repositories/pypi.py(211)get_dependencies()
    210                 download_dir = None
--> 211             elif ireq.link and not ireq.link.is_artifact:
    212                 # No download_dir for VCS sources.  This also works around pip

  /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/pip/_internal/models/link.py(160)is_artifact()
    159
--> 160         if self.scheme in vcs.all_schemes:
    161             return False

> /Users/albert/Projects/pip-tools/.venv/lib/python3.6/site-packages/pip/_internal/models/link.py(74)scheme()
     73         # type: () -> str
---> 74         return urllib_parse.urlsplit(self.url)[0]
     75

ipdb> urllib_parse.urlsplit(self.url)
SplitResult(scheme='', netloc='', path='git+git@github.com:jazzband/pip-tools', query='', fragment='egg=pip-tools')
```

For an `ireq.link.is_artifact` is True, this block

https://github.com/jazzband/pip-tools/blob/6d871f2461f2e11c24fc36a251b95c0db20775d8/piptools/repositories/pypi.py#L211-L214

is not reachable anymore. The scheme `git+git@` causes the bug.

**Comment by y3g0r** [comment]
@atugushev exactly, the issue is on that line. In my [fork](https://github.com/jazzband/pip-tools/compare/master...y3g0r:feature/fix-git-git-vcs-requirements) I have a quick fix, but it's too dirty to use it for PR.

After some investigation I realized that the issue is in fact on pip side, because `Link.is_artifact` is supposed to return true only if the link is something like a link to a tarbal. 

So we can raise/ping ticket on pip side and create a quick fix on pip-tools side or just wait until it's fixed in pip

**Comment by atugushev** [comment]
@y3g0r i've already reported a bug report to the pip project. Let's see where it goes.

**Comment by jedie** [comment]
I ran into the same Problem, isn't it?
```
  File ".../lib/python3.6/site-packages/piptools/repositories/pypi.py", line 208, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File ".../lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File ".../lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File ".../lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File ".../lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File ".../lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File ".../lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 609, in run_egg_info
    command_desc='python setup.py egg_info')
  File ".../lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpay192pcubuild/psycopg2/
```

Is there any work-a-round?

**Comment by atugushev** [comment]
@jedie how do you install `psycopg2`?

**Comment by jedie** [comment]
It's while i run `pip-compile --upgrade foobar.in` 
Last output line from pip-compile is: `psycopg2==2.8.1 not in cache, need to check index`

I i change `psycopg2<=2.8` then it works. So i think its a problem in `psycopg2` not in pip-tools.

**Comment by atugushev** [comment]
@jedie i see. Huh, we need more output in `pip-tools` to see what's happening.

**Comment by atugushev** [comment]
URLs pattern `git+git@` declared as deprecated in pip, see https://github.com/pypa/pip/pull/7543. Thanks for the issue!
