### ISSUE TITLE
@ delimiter for url is not supported

### ISSUE THREAD

**Issue by desaintmartin** [jazzband/pip-tools#854]
[PEP 508](https://www.python.org/dev/peps/pep-0508/) describes an urlspec beginning with `@` allowing to define requirements like `name@http://foo.com`.

This is not supported by pip-tools as of 3.9.0.

##### Environment Versions

1. OS Type: macos 10.14.4
1. Python version: Python 3.7.2
1. pip version:  pip 19.1.1
1. pip-tools version: 3.9.0

##### Steps to replicate

1. Define a setup.py file with:
```
from setuptools import setup

setup(
    name="foo",
    install_requires=[
        "itsdangerous @ https://github.com/pallets/itsdangerous/archive/1.1.0.zip",
    ],
)
```

2. run `pip install .`, it works
3. run `pip-compile`, it fails trying to get a local file that does not exist,  with:

```
Requirement 'itsdangerous@ https://github.com/pallets/itsdangerous/archive/1.1.0.zip' looks like a filename, but the file does not exist
Traceback (most recent call last):
  File "/home/foo/venv/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/home/foo/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/foo/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/foo/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/foo/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/foo/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 350, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/resolver.py", line 335, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 270, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/home/foo/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 229, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/download.py", line 873, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/download.py", line 807, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 628, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/foo/venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 503, in unzip_file
    zipfp = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/foo/itsdangerous@ https:/github.com/pallets/itsdangerous/archive/1.1.0.zip'
```

Funnily enough, running `pip install -r requirements.txt` with a requirements.txt with:
```
itsdangerous @ https://github.com/pallets/itsdangerous/archive/1.1.0.zip
```
Does not work as well.

**Comment by desaintmartin** [comment]
Note that this is probably related to https://github.com/pypa/pip/issues/6097 and its related PR https://github.com/pypa/pip/pull/6203

**Comment by atugushev** [comment]
Hello @desaintmartin,

Thanks for the report! Right, It's not supported by `pip`. Looks like the fix will be merged soon. I'll close this issue since it's not related to `pip-tools` directly and we can do nothing with it, but wait for a fix on pip side. Feel free to reopen though.

**Comment by atugushev** [comment]
@desaintmartin excellent! 🎉
