### ISSUE TITLE
pip-compile can't find existing project and crashes

### ISSUE THREAD

**Issue by knaperek** [jazzband/pip-tools#865]
pip-compile crashes when compiling dependencies for the web3[tester] package (potentially others too).

##### Environment Versions

1. OS Type: Ubuntu 18.04
1. Python version: Python 3.6.8
1. pip version:  9.0.1
1. pip-tools version: 4.0.0 (but the same behavior observed before)

##### Steps to replicate

With a simple `requirements.in` file:
```
web3[tester]
```
run: `$ pip-compile --dry-run requirements.in`
and see it crash with:
`KeyError: "No project with the name 'eth-tester'"`
Which is obviously not true. If you install the .in file with pip directly, you can see the package installed:
```
$ pip3 install -r requirements.in && pip3 freeze |grep eth-tester
eth-tester==0.1.0b39
```
Is it perhaps the letters in the version that confuse pip-compile so match that it crashes?

##### Expected result

It should not crash :-)

##### Actual result

```
Ignoring eth-tester: markers 'extra == "tester"' don't match your environment
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/piptools/scripts/compile.py", line 345, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/lib/python3.6/dist-packages/piptools/resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/dist-packages/piptools/resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/lib/python3.6/dist-packages/piptools/resolver.py", line 354, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/dist-packages/piptools/repositories/pypi.py", line 254, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/usr/local/lib/python3.6/dist-packages/piptools/repositories/pypi.py", line 176, in resolve_reqs
    results = reqset._prepare_file(self.finder, ireq)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 711, in _prepare_file
    add_req(subreq, extras_requested=available_requested)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 684, in add_req
    extras_requested=extras_requested))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 303, in add_requirement
    parent_req = self.get_requirement(parent_req_name)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 340, in get_requirement
    raise KeyError("No project with the name %r" % project_name)
KeyError: "No project with the name 'eth-tester'"
```

**Comment by atugushev** [comment]
Hello @knaperek,

Thanks for the detailed report! I'm afraid you have to upgrade pip (at least to 10.0), since then the issue with extra markers (which i presume) was fixed.

**Comment by knaperek** [comment]
Thanks @atugushev for your swift response, it worked. I wouldn't have guessed it was pip's fault since it did resolve and install the dependencies correctly when run with `pip install -r`.
Anyway, thanks heaps!
