### ISSUE TITLE
UnicodeEncodeError in download_package: creates 0-byte cached file

### ISSUE THREAD

**Issue by blueyed** [jazzband/pip-tools#87]
1. I have run `pip-compile` (from the future branch), and it failed on the `dj-database-url` package when writing the file contents.

The problem appears to be that pip's `get_file_content` returns a unicode string.

If have tried encoding it as `utf-8`, but that results in an invalid/broken zip/whl file.

```
===> Resolving full tree
- Finding best package matching ['dj-database-url']
    PIP said: Getting page https://pypi.python.org/simple/dj-database-url/
    PIP said: URLs to search for versions for dj-database-url:
    PIP said: * https://pypi.python.org/simple/dj-database-url/
    PIP said: Analyzing links from page https://pypi.python.org/simple/dj-database-url/
    PIP said:   Found link https://pypi.python.org/packages/2.7/d/dj-database-url/dj_database_url-0.3.0-py2.py3-none-any.whl#md5=58211401b11c49ba27deca8183c3061d (from https://pypi.python.org/simple/dj-database-url/), version: 0.3.0
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.1.2.tar.gz#md5=8b285dba950c9ca6e3f6082be64b2faf (from https://pypi.python.org/simple/dj-database-url/), version: 0.1.2
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.1.3.tar.gz#md5=175111400fee7c1f6ce4a4829c8b26ee (from https://pypi.python.org/simple/dj-database-url/), version: 0.1.3
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.1.4.tar.gz#md5=ee1f46a6b0ca3329e6701b5578b2aee6 (from https://pypi.python.org/simple/dj-database-url/), version: 0.1.4
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.2.0.tar.gz#md5=faaf1e1f06f738f72ef964696c46e379 (from https://pypi.python.org/simple/dj-database-url/), version: 0.2.0
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.2.1.tar.gz#md5=63ad283bb5931e8d3842e5b9edd7a1fd (from https://pypi.python.org/simple/dj-database-url/), version: 0.2.1
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.2.2.tar.gz#md5=ca96735f7e068a3e3414d3167122f927 (from https://pypi.python.org/simple/dj-database-url/), version: 0.2.2
    PIP said:   Found link https://pypi.python.org/packages/source/d/dj-database-url/dj-database-url-0.3.0.tar.gz#md5=28f89d403b565ee62dc25582852ae241 (from https://pypi.python.org/simple/dj-database-url/), version: 0.3.0
    PIP said:   Skipping link http://www.12factor.net/backing-services (from https://pypi.python.org/simple/dj-database-url/); not a file
    PIP said: Using version 0.3.0 (newest of versions: 0.3.0, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.4, 0.1.3, 0.1.2)
  Found best match: 0.3.0 (from PyPI)
- Getting dependencies for dj-database-url-0.3.0
    - Getting package location for dj-database-url==0.3.0
          Archive cache miss, downloading dj_database_url-0.3.0-py2.py3-none-any.whl...
        - Downloading package from https://pypi.python.org/packages/2.7/d/dj-database-url/dj_database_url-0.3.0-py2.py3-none-any.whl
Traceback (most recent call last):
  File "venv/bin/pip-compile", line 182, in <module>
    main()
  File "venv/bin/pip-compile", line 173, in main
    compile_specs(src_files, include_sources=args.include_sources, dry_run=args.dry_run)
  File "venv/bin/pip-compile", line 120, in compile_specs
    pinned_spec_set = resolver.resolve()
  File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 44, in resolve
    if not self.resolve_one_round():
  File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 28, in resolve_one_round
    new_deps = self.find_new_dependencies()
  File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 91, in find_new_dependencies
    all_deps = self.find_all_dependencies()
  File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 74, in find_all_dependencies
    pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
  File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 336, in get_dependencies
    path = self.get_or_download_package(pinned_spec)
  File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 377, in get_or_download_package
    self.download_package(link, fullpath)
  File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 417, in download_package
    f.write(content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd3' in position 10: ordinal not in range(128)
```
1. This error then caused an empty cache file to be created, which `pip-compile` also does not handle gracefully (e.g. by re-downloading it):
   
   $ echo dj-database-url > test.in
   $ pip-compile test.in 
   Traceback (most recent call last):
     File "venv/bin/pip-compile", line 182, in <module>
       main()
     File "venv/bin/pip-compile", line 173, in main
       compile_specs(src_files, include_sources=args.include_sources, dry_run=args.dry_run)
     File "venv/bin/pip-compile", line 120, in compile_specs
       pinned_spec_set = resolver.resolve()
     File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 44, in resolve
       if not self.resolve_one_round():
     File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 28, in resolve_one_round
       new_deps = self.find_new_dependencies()
     File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 91, in find_new_dependencies
       all_deps = self.find_all_dependencies()
     File "venv/local/lib/python2.7/site-packages/piptools/resolver.py", line 74, in find_all_dependencies
       pkg_deps = pkgmgr.get_dependencies(spec.pin(version))
     File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 337, in get_dependencies
       deps = self.extract_dependencies(path)
     File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 503, in extract_dependencies
       self.unpack_archive(path, unpack_dir)
     File "venv/local/lib/python2.7/site-packages/piptools/package_manager.py", line 425, in unpack_archive
       archive = zipfile.ZipFile(path)
     File "/usr/lib/python2.7/zipfile.py", line 770, in **init**
       self._RealGetContents()
     File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
       raise BadZipfile, "File is not a zip file"
   zipfile.BadZipfile: File is not a zip file

Python 2.7.6

**Comment by blueyed** [comment]
Yes, it appears to be fixed in Python 2, but not for Python 3: #137
