### ISSUE TITLE
Running tox fails

### ISSUE THREAD

**Issue by georgek** [jazzband/pip-tools#938]
When I try to run `tox` on a local clone, specifically the `checkqa` part fails due to not finding certain dependencies.

#### Environment Versions

1. OS Type: GNU/Linux
1. Python version: 3.6.9
1. pip version:  19.2.3
1. pip-tools version: master

#### Steps to replicate

1. Activate fresh virtualenv
2. `pip install -e .`
3. `pip install -r dev-requirements.txt`
4. `pip install tox`
5. `tox -e checkqa`

#### Expected result

All tests pass.

#### Actual result

Test fails with the following output:

```
(venv) gk@gk-pc ~/code/pip-tools (master) $ tox -e checkqa
checkqa recreate: /home/gk/code/pip-tools/.tox/checkqa
checkqa installdeps: pre-commit
checkqa installed: aspy.yaml==1.3.0,cfgv==2.0.1,identify==1.4.7,importlib-metadata==0.23,importlib-resources==1.0.2,more-itertools==7.2.0,nodeenv==1.3.3,pip-tools==4.2.0,pre-commit==1.18.3,PyYAML==5.1.2,six==1.12.0,toml==0.10.0,virtualenv==16.7.5,zipp==0.6.0
checkqa run-test-pre: PYTHONHASHSEED='2045719492'
checkqa run-test-pre: commands[0] | pip --version
pip 19.2.3 from /home/gk/code/pip-tools/.tox/checkqa/lib/python3.6/site-packages/pip (python 3.6)
checkqa run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
black....................................................................Passed
isort....................................................................Failed
hookid: isort

Traceback (most recent call last):
  File "/home/gk/.cache/pre-commit/repoz0nmzqaw/py_env-python3.7/bin/isort", line 6, in <module>
    from isort.main import main
ModuleNotFoundError: No module named 'isort'
Traceback (most recent call last):
  File "/home/gk/.cache/pre-commit/repoz0nmzqaw/py_env-python3.7/bin/isort", line 6, in <module>
    from isort.main import main
ModuleNotFoundError: No module named 'isort'

flake8...................................................................Failed
hookid: flake8

Traceback (most recent call last):
  File "/home/gk/.cache/pre-commit/repo9z9ih1f6/py_env-python3.7/bin/flake8", line 6, in <module>
    from flake8.main.cli import main
ModuleNotFoundError: No module named 'flake8'

bandit...................................................................Failed
hookid: bandit

Traceback (most recent call last):
  File "/home/gk/.cache/pre-commit/repow88fv026/py_env-python3.7/bin/bandit", line 6, in <module>
    from bandit.cli.main import main
ModuleNotFoundError: No module named 'bandit'
Traceback (most recent call last):
  File "/home/gk/.cache/pre-commit/repow88fv026/py_env-python3.7/bin/bandit", line 6, in <module>
    from bandit.cli.main import main
ModuleNotFoundError: No module named 'bandit'

ERROR: InvocationError for command /home/gk/code/pip-tools/.tox/checkqa/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
________________________________________________ summary _________________________________________________
ERROR:   checkqa: commands failed
```

**Comment by atugushev** [comment]
@georgek 

Thanks for filing this! Could you run `virtualenv venv && venv/bin/pip install isort && venv/bin/isort --version` and paste here the output?

**Comment by georgek** [comment]
```
gk@gk-pc ~/code/pip-tools (master) $ venv/bin/isort --version

/#######################################################################\

     `sMMy`
     .yyyy-                                                      `
    ##soos##                                                    ./o.
          `     ``..-..`         ``...`.``         `   ```` ``-ssso```
     .s:-y-   .+osssssso/.     ./ossss+:so+:`    :+o-`/osso:+sssssssso/
     .s::y-   osss+.``.``     -ssss+-.`-ossso`   ssssso/::..::+ssss:::.
     .s::y-   /ssss+//:-.`   `ssss+     `ssss+   sssso`       :ssss`
     .s::y-   `-/+oossssso/  `ssss/      sssso   ssss/        :ssss`
     .y-/y-       ````:ssss`  ossso.    :ssss:   ssss/        :ssss.
     `/so:`    `-//::/osss+   `+ssss+-/ossso:    /sso-        `osssso/.
       \/      `-/oooo++/-      .:/++:/++/-`      ..           `://++/.


         isort your Python imports for you so you don't have to

                            VERSION 4.3.21

\########################################################################/
```

**Comment by georgek** [comment]
OK, I think I have fixed it. If I install and run `pre-commit` before I run `tox` then the tests pass.

So I think this is just a documentation issue as I have never heard of or used pre-commit before so I had no idea that I would have to install that first. I think adding this bit about installing tox, pre-commit and running pre-commit before being able to run tox should be added to `CONTRIBUTING.md`.

**Comment by atugushev** [comment]
> OK, I think I have fixed it. If I install and run `pre-commit` before I run `tox` then the tests pass.

Interesting, how does it work in CIs then?

**Comment by georgek** [comment]
Good question. There is this part in the `.travis.yml`:
```
    # QA checks.
    - env: TOXENV=checkqa
      python: 3.7
      after_success: skip  # No need coverage
      cache:
        directories:
          - $HOME/.cache/pre-commit
```

Is that `$HOME/.cache` possibly persistent between CI runs?

**Comment by atugushev** [comment]
> Is that `$HOME/.cache` possibly persistent between CI runs?

That's right, but I don't remember any issues before we'd added this cache.

**Comment by atugushev** [comment]
Hm, it's failed on py36, see: https://github.com/atugushev/pip-tools/commit/9d543d510a73a04f33f45463ec43f565cbdbfc09/checks?check_suite_id=262207218

**Comment by georgek** [comment]
I am not able to reproduce this any more. I started again from a fresh clone and fresh virtualenv and it works just by installing tox as described in the steps in my initial post (no explicit installation of pre-commit). My only guess is that my old clone was quite old and had some subtle residual state that made it break.

**Comment by atugushev** [comment]
I'll close this then based on above. Feel free to reopen if you have any other issues. Thanks!
