### ISSUE TITLE
pip-compile brokern with pip 19.3.1

### ISSUE THREAD

**Issue by Ayub-Khan** [jazzband/pip-tools#980]
#### Environment Versions

1. OS Type 
Ubuntu
1. Python version: `$ python -V` 
2.7
1. pip version:  `$ pip --version` 
19.3.1
1. pip-tools version: `$ pip-compile --version`
3.8.0

#### Steps to replicate

1. ... pip install -U pip
2. ... pip-compile -U
3. ...
```
Traceback (most recent call last):
  File "/home/ayub/Documents/edly/custom-devstack/xu2/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 306, in cli
    dist = run_setup(src_file)
  File "/usr/lib/python2.7/distutils/core.py", line 218, in run_setup
    exec f.read() in g, l
  File "<string>", line 64, in <module>
  File "<string>", line 22, in get_version
NameError: global name 'os' is not defined
```
4. ... my case https://github.com/edx/xss-utils
```
pip install -qr requirements/pip-tools.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
# Make sure to compile files after any other files they include!
pip-compile --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
Traceback (most recent call last):
  File "/home/ayub/Documents/edly/custom-devstack/xu2/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from .._compat import install_req_from_line, parse_requirements
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/piptools/_compat/__init__.py", line 7, in <module>
    from .pip_compat import (
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/piptools/_compat/pip_compat.py", line 32, in <module>
    is_file_url = do_import("download", "is_file_url")
  File "/home/ayub/Documents/edly/custom-devstack/xu2/local/lib/python2.7/site-packages/piptools/_compat/pip_compat.py", line 24, in do_import
    return getattr(imported, package)
AttributeError: 'module' object has no attribute 'is_file_url'
Makefile:43: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1

```

Works fine for pip version 19.1

**Comment by atugushev** [comment]
Hello @Ayub-Khan,

Thanks for the issue! You should upgrade pip-tools to the latest `4.2.0` version.

**Comment by Ayub-Khan** [comment]
@atugushev thanks.

**Comment by atugushev** [comment]
I'll close this then, but please let us know if it doesn't resolve your issue. Thanks!

**Comment by Ayub-Khan** [comment]
That fixed the issue.
